In [1]:
import sys
from pathlib import Path

# Add the project root directory (one level up from tests/)
sys.path.append(str(Path.cwd().parent))
import pandas as pd
import os

In [21]:
%load_ext autoreload
%autoreload 2

from config.producer_config import configs
from src.utils.data_mapper import filter_data, read_xml
from src.schemas.medicine_schema import MedicineRecord

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
raw_data_path = r'C:\Users\ducngh\OneDrive - fpts.com.vn\Work\Dược\data\raw\data_Duoc_full\raw\kqtt'

    # filepath = os.path.join(raw_data_path, file)
def read_raw_data(filepath):
    """Read and validate data

    Args:
        filepath (_type_): _description_

    Returns:
        _type_: _description_
    """
    # print(filepath)
    data = read_xml(filepath).to_dict(orient='records')
    valid_data = []
    failed_rows = []

    for idx, row in enumerate(data):
        try:
            valid_data.append(MedicineRecord(**row).model_dump())
        except Exception as e:
            failed_rows.append({"index": idx, "error": str(e), "data": row})
            print(e)

    clean_df = pd.DataFrame(valid_data)
    date_cols = ['congbo', 'tungay_hd', 'denngay_hd', 'created_date', 'tungay', 'denngay']
    clean_df[date_cols] = clean_df[date_cols].apply(pd.to_datetime, errors='coerce')

    return clean_df, failed_rows

In [5]:
df = read_xml(
    r'C:\Users\ducngh\OneDrive - fpts.com.vn\Work\Dược\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls'
)

In [ ]:
configs_test = {
    "input_col":'nhasx',
    "output_col":"ticker",
    'filter':[
        # {
        #     "output_value": "IMP",
        #     "include_keyword": ["imexpharm"],
        #     "exclude_keyword": ["agimexpharm"]
        # },
        # {
        #     "output_value": "Pharbaco",
        #     "include_keyword": ["pharbaco"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "Minh Dân",
        #     "include_keyword": ["minh dan"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "Tenamyd",
        #     "include_keyword": ["tenamyd"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "ACS Dobfar",
        #     "include_keyword": [
        #         r"cssx\s*:\s*acs dobfar",
        #         r"^acs dobfar"
        #     ],
        #     "exclude_keyword": [],
        #     'is_regex':True
        # },
        # {
        #     "output_value": "Pymepharco",
        #     "include_keyword": ["pymepharco"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "VCP",
        #     "include_keyword": ["vcp"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "Polfa Tarchomin",
        #     "include_keyword": ["tarchomin"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "Tarchomin Pharmaceutical",
        #     "include_keyword": ["tarchomin"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "S.C. Antibiotice",
        #     "include_keyword": ["antibiotice"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "S.C. Antibiotice",
        #     "include_keyword": ["antibiotice"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "Wyeth Lederle S.R.L",
        #     "include_keyword": ["wyeth lederle s.r.l"],
        #     "exclude_keyword": []
        # },
        # {
        #     "output_value": "Wyeth Lederle S.R.L",
        #     "include_keyword": ["wyeth lederle s.r.l"],
        #     "exclude_keyword": []
        # },
        {
            "output_value": "Fareva Mirabel",
            "is_regex": True,
            "include_keyword": [
                r"cssx\s*:\s*fareva mirabel",
                r"^fareva mirabel"
            ],
            "exclude_keyword": []
        }
    ]
}

In [24]:
df

,loai_thau,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma,ma_gy,ten,hoatchat,...,tieuchuan,nhomthau,loai,sttpheduyet,hieuluc,congbo,ht_thau,tungay_hd,denngay_hd,created_date
0,3.thau_rieng_le,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.162,40.162,SM.Cefadroxil 500,Cefadroxil,...,,N4,Tân dược,,1,2025-04-11 00:00:00,1,2025-04-11 00:00:00,2025-07-10 00:00:00,2025-10-25 22:21:51
1,3.thau_rieng_le,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,40.883,"Natri Clorid 0,9%",Natri clorid,...,,N4,Tân dược,,1,2025-04-11 00:00:00,1,2025-04-11 00:00:00,2025-07-10 00:00:00,2025-10-25 22:21:51
2,3.thau_rieng_le,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,40.883,"Natri Clorid 0,9%",Natri clorid,...,,N4,Tân dược,,1,2025-04-11 00:00:00,1,2025-04-11 00:00:00,2025-07-10 00:00:00,2025-10-25 22:21:51
3,3.thau_rieng_le,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.512,40.512,SaVi Losartan 50,Losartan Kali,...,,N3,Tân dược,,1,2025-04-11 00:00:00,1,2025-04-11 00:00:00,2025-07-10 00:00:00,2025-10-25 22:21:51
4,3.thau_rieng_le,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,40.883,"Natri Clorid 0,9%",Natri clorid,...,,N4,Tân dược,,1,2025-04-11 00:00:00,1,2025-04-11 00:00:00,2025-07-10 00:00:00,2025-10-25 22:21:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74436,3.thau_rieng_le,62,Tỉnh Kon Tum,Tyt Đăk Cấm,62027,Tyt Đăk Cấm,40.206,40.206,"Tobramycin 0,3%",Tobramycin,...,,N4,Tân dược,,1,2025-05-16 00:00:00,3,2025-05-16 00:00:00,2025-06-16 00:00:00,2025-10-25 22:21:51
74437,3.thau_rieng_le,62,Tỉnh Kon Tum,Tyt Đăk Cấm,62027,Tyt Đăk Cấm,40.1050,40.1050,Vitamin 3B extra,Vitamin B1 + B6 + B12,...,,N4,Tân dược,,1,2025-05-16 00:00:00,3,2025-05-16 00:00:00,2025-06-16 00:00:00,2025-10-25 22:21:51
74438,3.thau_rieng_le,62,Tỉnh Kon Tum,Tyt Đăk Cấm,62027,Tyt Đăk Cấm,40.1057,40.1057,Vitamin C 500mg,Vitamin C,...,,N4,Tân dược,,1,2025-05-16 00:00:00,3,2025-05-16 00:00:00,2025-06-16 00:00:00,2025-10-25 22:21:51
74439,3.thau_rieng_le,62,Tỉnh Kon Tum,Tyt Đăk Cấm,62027,Tyt Đăk Cấm,40.576,40.576,Kacetam,Piracetam,...,,N3,Tân dược,,1,2025-05-16 00:00:00,3,2025-05-16 00:00:00,2025-06-16 00:00:00,2025-10-25 22:21:51
74440,3.thau_rieng_le,62,Tỉnh Kon Tum,Tyt Đăk Cấm,62027,Tyt Đăk Cấm,40.988,40.988,Ambroxol,Ambroxol,...,,N4,Tân dược,,1,2025-05-16 00:00:00,3,2025-05-16 00:00:00,2025-06-16 00:00:00,2025-10-25 22:21:51

In [37]:
filter_data(
    df=df, 
    config=configs_test
)['nhasx'].unique().tolist()

=== BÁO CÁO MATCH DỮ LIỆU ===
Cột gán nhãn:       'ticker'
Tổng số dòng:       74,441
Đã match (gán nhãn): 23 (0.03%)
Chưa match:         74,418 (99.97%)

Chi tiết theo 'ticker':
ticker
Fareva Mirabel    23
==============================

['Fareva Mirabel']

In [10]:
data.head(10).to_clipboard()

In [27]:
filter_data(
    df=df, 
    config=configs, 
)

=== BÁO CÁO MATCH DỮ LIỆU ===
Cột gán nhãn:       'ticker'
Tổng số dòng:       104,732
Đã match (gán nhãn): 1,822 (1.74%)
Chưa match:         102,910 (98.26%)

Chi tiết theo 'ticker':
ticker
IMP    1822
==============================

,loai_thau,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma,ma_gy,ten,hoatchat,...,nhomthau,loai,sttpheduyet,hieuluc,congbo,ht_thau,tungay_hd,denngay_hd,created_date,ticker
264,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.158,40.158,Nerusyn 750,Ampicilin + sulbactam,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
265,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.158,40.158,"Nerusyn 1,5g",Ampicilin + sulbactam,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
267,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.175,40.175,Cefoxitin 1g,Cefoxitin,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
270,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.191,40.191,Piperacillin 2g,Piperacilin,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
295,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.158,40.158,Nerusyn 750,Ampicilin + sulbactam,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104263,3.thau_rieng_le,95,Tỉnh Bạc Liêu,Tyt Vĩnh Hậu A,95063,Tyt Vĩnh Hậu A,40.163,40.163,Cephalexin 500mg,Cefalexin,...,N3,Tân dược,,1,2025-06-03 00:00:00,1,2025-06-03 00:00:00,2026-02-20 00:00:00,2025-10-25 22:21:51,IMP
104330,3.thau_rieng_le,26,Tỉnh Vĩnh Phúc,Tyt Thị Trấntứ Trưng,26508,Tyt Thị Trấntứ Trưng,40.163,40.163,Cephalexin 500mg,Cefalexin,...,N3,Tân dược,,1,2025-09-10 00:00:00,1,2025-09-10 00:00:00,2026-09-10 00:00:00,2025-10-25 22:21:51,IMP
104446,3.thau_rieng_le,26,Tỉnh Vĩnh Phúc,Tyt Tề Lỗ,26615,Tyt Tề Lỗ,40.163,40.163,Cephalexin 500mg,Cefalexin,...,N3,Tân dược,,1,2025-06-09 00:00:00,1,2025-06-09 00:00:00,2026-06-09 00:00:00,2025-10-25 22:21:51,IMP
104603,3.thau_rieng_le,46,Tỉnh Thừa Thiên Huế,Tyt Phú Lộc,46147,Tyt Phú Lộc,40.154,40.154,Amoxicillin 250 mg,Amoxicilin,...,N3,Tân dược,,1,2025-06-27 00:00:00,1,2025-06-27 00:00:00,2026-06-26 00:00:00,2025-10-25 22:21:51,IMP
104627,3.thau_rieng_le,01,Thành phố Hà Nội,Pkđkkv Xuân Mai Trực Thuộc Tyt Xã Xuân Mai,01100,Pkđkkv Xuân Mai Trực Thuộc Tyt Xã Xuân Mai,40.155,40.155,"Amoxicillin/ Acid clavulanic 250mg/ 31,25mg",Amoxicilin + acid clavulanic,...,N1,Tân dược,,1,2025-09-30 00:00:00,5,2025-09-30 00:00:00,2026-09-30 00:00:00,2025-10-25 22:21:51,IMP

In [ ]:
# result_df.to_excel('outputs/IMP.xlsx', index=False)