In [1]:
import sys
from pathlib import Path

# Add the project root directory (one level up from tests/)
sys.path.append(str(Path.cwd().parent))
import pandas as pd
import os

In [6]:
%load_ext autoreload
%autoreload 2

from config.producer_config import configs
from src.utils.data_mapper import filter_data, read_xml
from src.schemas.medicine_schema import MedicineRecord

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
raw_data_path = r'C:\Users\ducngh\OneDrive - fpts.com.vn\Work\Dược\data\raw\data_Duoc_full\raw\kqtt'

all_data = []

for file in os.listdir(raw_data_path):
    if not file.endswith('xls'):
        continue

    filepath = os.path.join(raw_data_path, file)
    print(filepath)

    data = read_xml(filepath).to_dict(orient='records')
    valid_data = []
    failed_rows = []

    for idx, row in enumerate(data):
        try:
            valid_data.append(MedicineRecord(**row).model_dump())
        except Exception as e:
            failed_rows.append({"index": idx, "error": str(e), "data": row})

    all_data.append(valid_data)

C:\Users\ducngh\OneDrive - fpts.com.vn\Work\Dược\data\raw\data_Duoc_full\raw\kqtt\202201-202202.xls

In [ ]:
clean_df = pd.DataFrame(all_data)
date_cols = ['congbo', 'tungay_hd', 'denngay_hd', 'created_date', 'tungay', 'denngay']
clean_df[date_cols] = clean_df[date_cols].apply(pd.to_datetime, errors='coerce')

In [14]:
clean_df

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,loai,sttpheduyet,hieuluc,ht_thau,tungay,denngay,congbo,tungay_hd,denngay_hd,created_date
0,3.thau_rieng_le,40.491,Stadovas 5 CAP,Amlodipin,35,Tỉnh Hà Nam,Tyt Nguyên Lý,35132,Tyt Nguyên Lý,40.491,...,Tân dược,None,1,NaN,2022-01-06,NaT,2022-01-06,NaT,NaT,2025-10-25 22:21:51
1,3.thau_rieng_le,40.41,Mebilax 15,Meloxicam,35,Tỉnh Hà Nam,Tyt Nguyên Lý,35132,Tyt Nguyên Lý,40.41,...,Tân dược,None,1,NaN,2022-01-05,NaT,2022-01-05,NaT,NaT,2025-10-25 22:21:51
2,3.thau_rieng_le,40.17,Oxy nhỏ 1m3,Oxy dược dụng,68,Tỉnh Lâm Đồng,Ttyt Khu Vực Lâm Hà,68510,Ttyt Khu Vực Lâm Hà,40.17,...,Tân dược,None,1,NaN,2022-01-20,NaT,2022-01-20,NaT,NaT,2025-10-25 22:21:51
3,3.thau_rieng_le,40.17,Oxy lỏng,Oxy dược dụng,68,Tỉnh Lâm Đồng,Ttyt Khu Vực Lâm Hà,68510,Ttyt Khu Vực Lâm Hà,40.17,...,Tân dược,None,1,NaN,2022-01-20,NaT,2022-01-20,NaT,NaT,2025-10-25 22:21:51
4,3.thau_rieng_le,40.178,Doncef,Cefradin,01,Thành phố Hà Nội,Tyt Thị Trấn Phú Minh (Ttyt H. Phú Xuyên),01M51,Tyt Thị Trấn Phú Minh (Ttyt H. Phú Xuyên),40.178,...,Tân dược,None,1,1,2022-01-17,NaT,2022-01-17,NaT,2023-01-16,2025-10-25 22:21:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43397,3.thau_rieng_le,40.83,Anticlor,Dexchlorpheniramin,66,Tỉnh Đắk Lắk,Pkđk An Bình,66247,Pkđk An Bình,40.83,...,Tân dược,None,1,NaN,2022-02-23,NaT,2022-02-23,NaT,NaT,2025-10-25 22:21:51
43398,3.thau_rieng_le,40.699,Duspatalin retard,Mebeverin hydroclorid,66,Tỉnh Đắk Lắk,Pkđk An Bình,66247,Pkđk An Bình,40.699,...,Tân dược,None,1,NaN,2022-02-23,NaT,2022-02-23,NaT,NaT,2025-10-25 22:21:51
43399,3.thau_rieng_le,40.235,Oflovid Ophthalmic Ointment,Ofloxacin,66,Tỉnh Đắk Lắk,Pkđk An Bình,66247,Pkđk An Bình,40.235,...,Tân dược,None,1,NaN,2022-02-23,NaT,2022-02-23,NaT,NaT,2025-10-25 22:21:51
43400,3.thau_rieng_le,40.154,Moxacin,Amoxicilin,36,Tỉnh Nam Định,Tyt Hải Lộc,36939,Tyt Hải Lộc,40.154,...,Tân dược,None,1,NaN,2022-02-18,NaT,2022-02-18,NaT,NaT,2025-10-25 22:21:51
43401,3.thau_rieng_le,40.491,Stadovas 5 Tab,Amlodipin,19,Tỉnh Thái Nguyên,Tyt Hương Sơn,19115,Tyt Hương Sơn,40.491,...,Tân dược,None,1,NaN,2022-02-17,NaT,2022-02-17,NaT,NaT,2025-10-25 22:21:51

In [9]:
data = data.replace("", None)
data.isna().any()

loai_thau       False
ma_tinh          True
ten_tinh         True
ten_don_vi       True
ma_cskcb         True
ten_cskcb        True
ma              False
ma_gy            True
ten             False
hoatchat        False
duongdung       False
maduongdung     False
madd_gy          True
dangbaoche       True
hamluong         True
donggoi          True
sodk             True
nhasx            True
nuocsx           True
donvitinh        True
soluong          True
gia             False
thanhtien        True
tennhathau       True
quyetdinh        True
tungay          False
denngay          True
goithau          True
tieuchuan        True
nhomthau         True
loai            False
sttpheduyet      True
hieuluc         False
congbo           True
ht_thau          True
tungay_hd        True
denngay_hd       True
created_date    False
dtype: bool

In [10]:
data.head(10).to_clipboard()

In [27]:
filter_data(
    df=df, 
    config=configs, 
)

=== BÁO CÁO MATCH DỮ LIỆU ===
Cột gán nhãn:       'ticker'
Tổng số dòng:       104,732
Đã match (gán nhãn): 1,822 (1.74%)
Chưa match:         102,910 (98.26%)

Chi tiết theo 'ticker':
ticker
IMP    1822
==============================

,loai_thau,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma,ma_gy,ten,hoatchat,...,nhomthau,loai,sttpheduyet,hieuluc,congbo,ht_thau,tungay_hd,denngay_hd,created_date,ticker
264,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.158,40.158,Nerusyn 750,Ampicilin + sulbactam,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
265,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.158,40.158,"Nerusyn 1,5g",Ampicilin + sulbactam,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
267,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.175,40.175,Cefoxitin 1g,Cefoxitin,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
270,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.191,40.191,Piperacillin 2g,Piperacilin,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
295,3.thau_rieng_le,38,Tỉnh Thanh Hóa,Pkđk Xuân Bình,38805,Pkđk Xuân Bình,40.158,40.158,Nerusyn 750,Ampicilin + sulbactam,...,N2,Tân dược,,1,2025-06-06 00:00:00,1,2025-06-06 00:00:00,2026-06-06 00:00:00,2025-10-25 22:21:51,IMP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104263,3.thau_rieng_le,95,Tỉnh Bạc Liêu,Tyt Vĩnh Hậu A,95063,Tyt Vĩnh Hậu A,40.163,40.163,Cephalexin 500mg,Cefalexin,...,N3,Tân dược,,1,2025-06-03 00:00:00,1,2025-06-03 00:00:00,2026-02-20 00:00:00,2025-10-25 22:21:51,IMP
104330,3.thau_rieng_le,26,Tỉnh Vĩnh Phúc,Tyt Thị Trấntứ Trưng,26508,Tyt Thị Trấntứ Trưng,40.163,40.163,Cephalexin 500mg,Cefalexin,...,N3,Tân dược,,1,2025-09-10 00:00:00,1,2025-09-10 00:00:00,2026-09-10 00:00:00,2025-10-25 22:21:51,IMP
104446,3.thau_rieng_le,26,Tỉnh Vĩnh Phúc,Tyt Tề Lỗ,26615,Tyt Tề Lỗ,40.163,40.163,Cephalexin 500mg,Cefalexin,...,N3,Tân dược,,1,2025-06-09 00:00:00,1,2025-06-09 00:00:00,2026-06-09 00:00:00,2025-10-25 22:21:51,IMP
104603,3.thau_rieng_le,46,Tỉnh Thừa Thiên Huế,Tyt Phú Lộc,46147,Tyt Phú Lộc,40.154,40.154,Amoxicillin 250 mg,Amoxicilin,...,N3,Tân dược,,1,2025-06-27 00:00:00,1,2025-06-27 00:00:00,2026-06-26 00:00:00,2025-10-25 22:21:51,IMP
104627,3.thau_rieng_le,01,Thành phố Hà Nội,Pkđkkv Xuân Mai Trực Thuộc Tyt Xã Xuân Mai,01100,Pkđkkv Xuân Mai Trực Thuộc Tyt Xã Xuân Mai,40.155,40.155,"Amoxicillin/ Acid clavulanic 250mg/ 31,25mg",Amoxicilin + acid clavulanic,...,N1,Tân dược,,1,2025-09-30 00:00:00,5,2025-09-30 00:00:00,2026-09-30 00:00:00,2025-10-25 22:21:51,IMP

In [ ]:
# result_df.to_excel('outputs/IMP.xlsx', index=False)