In [1]:
'''
Chỉnh working directory
'''

import sys
from pathlib import Path
# Add the project root directory (one level up from tests/)
sys.path.append(str(Path.cwd().parent))
import pandas as pd
import os

In [2]:
%load_ext autoreload
%autoreload 2

'''
Load các thư viện, function cần thiết.
    producer_config: cài đặt filter do chuyên viên nhập và điều chỉnh
    LoadMedicalData: class sử dụng để load, xử lý và tính toán
'''

from config.filter_config import config
from src.utils.data_loader import LoadMedicalData
from config.statics import DRUG_TYPES_TEMPLATE

# Load dữ liệu

Có thể load dữ liệu từ file .xls gốc từ APD, hoặc sử dụng file tổng hợp .parquet để xem toàn bộ dữ liệu trong quá khứ.

_Note_: File [data](/data/raw/data.parquet) được tổng hợp từ APD, kéo dài từ 2021 - nay

In [ ]:
# Option 1: Load từ file .xls
test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls' # đưa PATH đến data ở đây. 

loader = LoadMedicalData(
    test_path, 
    config=config,
    drug_types_path=DRUG_TYPES_TEMPLATE
)

c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:210: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = clean_series.str.contains(include_pat, na=False)
c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:212: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = cond & (~clean_series.str.contains(exclude_pat, na=False))

In [3]:
# Option 2: Load từ file .parquet
all_data = pd.read_parquet('../data/raw/data.parquet') # PATH đến file dữ liệu
loader = LoadMedicalData(
    datasource=all_data,
    config=config,
    drug_types_path=DRUG_TYPES_TEMPLATE
)

c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:227: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = clean_series.str.contains(include_pat, na=False)
c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:229: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = cond & (~clean_series.str.contains(exclude_pat, na=False))

In [4]:
# Hiện toàn bộ dữ liệu

loader.show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,3.thau_rieng_le,40.798,Dorobay 50mg,Acarbose,37,Tỉnh Ninh Bình,Pkđk Hợp Lực-Hà Nội,37097,Pkđk Hợp Lực-Hà Nội,40.798,...,2022-10-28,2022-05-23,NaT,NaT,DMC,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
1,2.thau_tinh,40.798,Dorobay 100 mg,Acarbose,33,Tỉnh Hưng Yên,Tỉnh Hưng Yên,None,None,None,...,2022-10-31,2022-08-30,NaT,NaT,DMC,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
2,3.thau_rieng_le,40.798,Dorobay 100 mg,Acarbose,79,Thành phố Hồ Chí Minh,Bv Đhyd Tp Hồ Chí Minh,79431,Bv Đhyd Tp Hồ Chí Minh,40.798,...,NaT,2026-07-20,2026-07-20,2028-01-19,DMC,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
3,3.thau_rieng_le,40.798,SaVi Acarbose 100,Acarbose,79,Thành phố Hồ Chí Minh,Bv Quận 8-Cs 2 (Pkđk Xóm Củi),79053,Bv Quận 8-Cs 2 (Pkđk Xóm Củi),40.798,...,NaT,2022-05-12,NaT,NaT,None,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
4,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,79,Thành phố Hồ Chí Minh,Tyt Tây Thạnh-Quận Tân Phú,79170,Tyt Tây Thạnh-Quận Tân Phú,40.798,...,NaT,2022-05-24,NaT,NaT,None,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
424585,3.thau_rieng_le,40.344,M-Prib-3.5,Bortezomib,48,Thành phố Đà Nẵng,Bv Ub Đà Nẵng,48126,Bv Ub Đà Nẵng,40.344,...,NaT,2022-10-31,NaT,NaT,None,None,None,NaN,NaN,NaN
424586,3.thau_rieng_le,40.783.1,Saizen,Somatropin,46,Tỉnh Thừa Thiên Huế,Bv Tw Huế,46001,Bv Tw Huế,40.783.1,...,NaT,2026-04-13,2026-04-13,2026-07-13,None,None,None,NaN,NaN,NaN
424587,3.thau_rieng_le,40.30.379,TS-One Capsule 20,Tegafur + gimeracil + oteracil kali,79,Thành phố Hồ Chí Minh,Bv Lê Văn Thịnh,79075,Bv Lê Văn Thịnh,40.30.379,...,NaT,2026-06-26,2026-06-26,2028-06-26,None,None,None,NaN,NaN,NaN
424588,3.thau_rieng_le,40.30.379,TS-One Capsule 25,Tegafur + gimeracil + oteracil kali,79,Thành phố Hồ Chí Minh,Bv Lê Văn Thịnh,79075,Bv Lê Văn Thịnh,40.30.379,...,NaT,2026-06-26,2026-06-26,2028-06-26,None,None,None,NaN,NaN,NaN
424589,3.thau_rieng_le,40.582,Differin Cream 0.1%,Adapalen,79,Thành phố Hồ Chí Minh,Bv Lê Văn Thịnh,79075,Bv Lê Văn Thịnh,40.582,...,NaT,2026-06-26,2026-06-26,2028-06-26,None,None,None,NaN,NaN,NaN

# Lọc (filter) dữ liệu

_Lưu ý:_ Cần sử dụng .show_data() ở sau các bước để hiện dữ liệu

In [ ]:
# Filter theo nhà sản xuất
loader.filter(column='ticker', value='IMP').show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,3.thau_rieng_le,40.30.66,Andol S,Paracetamol + chlorpheniramin + phenylephrin,42,Tỉnh Hà Tĩnh,Bệnh Viên Đa Khoa Tth Hà Tĩnh,42337,Bệnh Viên Đa Khoa Tth Hà Tĩnh,40.30.66,...,NaT,2022-03-24,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
1,2.thau_tinh,40.49,Cobimol,Paracetamol + chlorpheniramin,82,Tỉnh Tiền Giang,Tỉnh Tiền Giang,None,None,None,...,2025-07-30,2023-07-31,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
2,2.thau_tinh,40.30.66,Andol S,Paracetamol + chlorpheniramin + phenylephrin,82,Tỉnh Tiền Giang,Tỉnh Tiền Giang,None,None,None,...,2025-02-23,2023-07-31,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
3,2.thau_tinh,40.30.66,Andol S,Paracetamol + chlorpheniramin + phenylephrin,82,Tỉnh Tiền Giang,Tỉnh Tiền Giang,None,None,None,...,2025-07-30,2023-07-31,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
4,2.thau_tinh,40.49,Cobimol,Paracetamol+Chlorpheniramin,92,Thành phố Cần Thơ,Thành phố Cần Thơ,None,None,None,...,2025-10-19,NaT,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18102,3.thau_rieng_le,20.194,Imecef,Ceftazidime + Avibactam,01,Thành phố Hà Nội,Bv K Cơ Sở Chính,01253,Bv K Cơ Sở Chính,20.194,...,NaT,2026-07-08,2026-07-08,2027-07-08,IMP,Việt Nam,None,NaN,NaN,NaN
18103,3.thau_rieng_le,40.196,"Ticarlinat 3,2g",Ticarcillin + kali clavulanat,79,Thành phố Hồ Chí Minh,Bvđk Tân Phú,79054,Bvđk Tân Phú,40.196,...,NaT,2026-06-23,2026-06-05,2028-06-04,IMP,Việt Nam,None,NaN,NaN,NaN
18104,3.thau_rieng_le,20.194,Imecef,Ceftazidime + Avibactam,01,Thành phố Hà Nội,Bv K Cơ Sở 2-Viện Chăm Sóc Giảm Nhẹ,01254,Bv K Cơ Sở 2-Viện Chăm Sóc Giảm Nhẹ,20.194,...,NaT,2026-07-08,2026-07-08,2027-07-08,IMP,Việt Nam,None,NaN,NaN,NaN
18105,3.thau_rieng_le,40.155,"Imefed 250mg/31,25mg.",Acid clavulanic (dưới dạng Kali clavulanat - s...,37,Tỉnh Ninh Bình,Bv Bạch Mai Cơ Sở Ninh Bình,37470,Bv Bạch Mai Cơ Sở Ninh Bình,40.155,...,NaT,2026-06-26,2025-12-09,2027-12-08,IMP,Việt Nam,None,NaN,NaN,NaN
18106,3.thau_rieng_le,20.194,Imecef,Ceftazidime + Avibactam,01,Thành phố Hà Nội,Bv K Cơ Sở 1-Viện Ung Thư Quốc Gia (Viện Nghiê...,01906,Bv K Cơ Sở 1-Viện Ung Thư Quốc Gia (Viện Nghiê...,20.194,...,NaT,2026-07-08,2026-07-08,2027-07-08,IMP,Việt Nam,None,NaN,NaN,NaN

In [ ]:
# Filter theo quốc gia sản xuất
loader.filter(column='country', value='Hoa Kỳ').show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,2.thau_tinh,40.455,Flexbumin 20%,Albumin người,24,Tỉnh Bắc Giang,Tỉnh Bắc Giang,NaN,NaN,NaN,...,2026-02-28,2025-05-30,NaT,NaT,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
1,2.thau_tinh,40.455,Albutein,Albumin người,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,2025-05-15,NaT,NaT,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
2,2.thau_tinh,40.455,Albutein,Albumin người,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,NaT,NaT,NaT,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
3,3.thau_rieng_le,40.455,Albutein 20%,Albumin,26,Tỉnh Vĩnh Phúc,Pkđk Trực Thuộc Bv Sản-Nhi Tỉnh Vĩnh Phúc,26117,Pkđk Trực Thuộc Bv Sản-Nhi Tỉnh Vĩnh Phúc,40.455,...,NaT,2025-05-09,2025-05-09,2026-05-09,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
4,3.thau_rieng_le,40.455,Flexbumin 20%,Albumin người,02,Tỉnh Hà Giang,Bvđk Huyện Mèo Vạc,02012,Bvđk Huyện Mèo Vạc,40.455,...,NaT,2025-04-09,2025-04-09,2026-04-09,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,3.thau_rieng_le,40.22,Seaoflura,Sevofluran,40,Tỉnh Nghệ An,Bv Đại Học Y Khoa Vinh,40550,Bv Đại Học Y Khoa Vinh,40.22,...,NaT,2025-05-12,2025-05-12,2027-05-11,None,Hoa Kỳ,Sevofluran,"1. Gây tê, gây mê, giãn cơ",1.1. Thuốc gây tê gây mê,Sevofluran
166,3.thau_rieng_le,40.22,Seaoflura,Sevofluran,31,Thành phố Hải Phòng,Bv Nhi Hải Phòng,31032,Bv Nhi Hải Phòng,40.22,...,NaT,2025-04-09,2025-04-09,2025-09-08,None,Hoa Kỳ,Sevofluran,"1. Gây tê, gây mê, giãn cơ",1.1. Thuốc gây tê gây mê,Sevofluran
167,2.thau_tinh,40.30.144,Bridion,Sugammadex,75,Tỉnh Đồng Nai,Tỉnh Đồng Nai,NaN,NaN,NaN,...,2027-02-27,NaT,NaT,NaT,None,Hoa Kỳ,Sugammadex,4. Thuốc giải độc và các thuốc dùng trong trườ...,4. Thuốc giải độc và các thuốc dùng trong trườ...,Sugammadex
168,3.thau_rieng_le,40.30.144,Bridion,Sugammadex,01,Thành phố Hà Nội,Ct Bv Gtvt,01010,Ct Bv Gtvt,40.30.144,...,NaT,2025-04-26,2025-04-26,2026-04-25,None,Hoa Kỳ,Sugammadex,4. Thuốc giải độc và các thuốc dùng trong trườ...,4. Thuốc giải độc và các thuốc dùng trong trườ...,Sugammadex
169,3.thau_rieng_le,40.1004,Survanta,Surfactant (Phospholipid chiết xuất từ phổi bò),37,Tỉnh Ninh Bình,Bv Sản Nhi Tỉnh,37074,Bv Sản Nhi Tỉnh,40.1004,...,NaT,2025-05-20,2025-05-20,2025-06-20,None,Hoa Kỳ,Surfactant (Phospholipid chiết xuất từ phổi lợ...,25. Thuốc tác dụng trên đường hô hấp,25.3. Thuốc khác,Surfactant (Phospholipid chiết xuất từ phổi lợ...

In [ ]:
# Filter theo nhóm thầu
loader.filter(column='nhomthau', value='N1').show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,3.thau_rieng_le,40.798,Glucobay 50mg,Acarbose,79,Thành phố Hồ Chí Minh,Bvđk Bưu Điện,79023,Bvđk Bưu Điện,40.798,...,NaT,2025-05-13,2025-05-13,2026-05-15,None,Đức,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
1,3.thau_rieng_le,40.798,Bluecabose 50mg,Acarbose,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.798,...,NaT,2025-05-14,2025-05-14,2026-11-14,None,Bồ Đào Nha,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
2,3.thau_rieng_le,40.798,Bluecabose 50mg,Acarbose,40,Tỉnh Nghệ An,Bvđk Nghi Lộc,40009,Bvđk Nghi Lộc,40.798,...,NaT,2025-04-15,2025-04-15,2027-03-25,None,Bồ Đào Nha,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
3,2.thau_tinh,40.798,Acarbose Friulchem,Acarbose,79,Thành phố Hồ Chí Minh,Thành phố Hồ Chí Minh,NaN,NaN,NaN,...,2026-12-31,2025-04-01,NaT,NaT,None,Ý,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
4,2.thau_tinh,40.798,Acarbose Friulchem,Acarbose,79,Thành phố Hồ Chí Minh,Thành phố Hồ Chí Minh,NaN,NaN,NaN,...,2026-12-31,NaT,NaT,NaT,None,Ý,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6448,2.thau_tinh,40.991,Neo-Codion,Codein camphosulfonat + Sulfogaiacol + Cao mềm...,52,Tỉnh Bình Định,Tỉnh Bình Định,NaN,NaN,NaN,...,2026-12-31,2025-04-15,NaT,NaT,None,Pháp,None,NaN,NaN,NaN
6449,3.thau_rieng_le,40.929,Prismasol B0,Khoang A: Mỗi 1000ml chứa Calcium clorid dihyd...,37,Tỉnh Ninh Bình,Bv Sản Nhi Tỉnh,37074,Bv Sản Nhi Tỉnh,40.929,...,NaT,2025-04-25,2025-04-25,2025-05-25,None,Ý,None,NaN,NaN,NaN
6450,3.thau_rieng_le,40.929,Prismasol B0,Khoang A: Mỗi 1000ml chứa Calcium clorid dihyd...,37,Tỉnh Ninh Bình,Bv Sản Nhi Tỉnh,37074,Bv Sản Nhi Tỉnh,40.929,...,NaT,2025-05-05,2025-05-05,2025-06-05,None,Ý,None,NaN,NaN,NaN
6451,3.thau_rieng_le,40.929,Prismasol B0,Khoang A: Mỗi 1000ml chứa Calcium clorid dihyd...,37,Tỉnh Ninh Bình,Bv Sản Nhi Tỉnh,37074,Bv Sản Nhi Tỉnh,40.929,...,NaT,2025-05-13,2025-05-13,2025-06-13,None,Ý,None,NaN,NaN,NaN
6452,3.thau_rieng_le,40.163,Cephalexin PMP 500,Cephalexin,22,Tỉnh Quảng Ninh,Tyt-Công Ty Công Nghiệp Hoá Chất Mỏ Cẩm Phả,22038,Tyt-Công Ty Công Nghiệp Hoá Chất Mỏ Cẩm Phả,40.163,...,NaT,2025-05-13,2025-05-13,2026-03-31,Pymepharco,Việt Nam,None,NaN,NaN,NaN

In [6]:
# Filter nhiều bước
loader.filter(
    column='Loại thuốc 1', 
    value='6. Thuốc điều trị ký sinh trùng, chống nhiễm khuẩn'
).filter(
    column='country',
    value='Hoa Kỳ'
).show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,3.thau_rieng_le,40.249,Colistimethate for Injection U.S.P.,Colistin*,92,Thành phố Cần Thơ,Bvđk Hoàn Mỹ Cửu Long,92088,Bvđk Hoàn Mỹ Cửu Long,40.249,...,NaT,2022-03-23,NaT,NaT,None,Hoa Kỳ,Colistin*,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.10. Thuốc KS khác,Colistin*
1,3.thau_rieng_le,40.249,Colistimethate for Injection U.S.P,Colistin*,01,Thành phố Hà Nội,Bv Đại Học Y Hà Nội Cs Hoàng Mai,01273,Bv Đại Học Y Hà Nội Cs Hoàng Mai,40.249,...,NaT,2022-05-31,NaT,NaT,None,Hoa Kỳ,Colistin*,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.10. Thuốc KS khác,Colistin*
2,3.thau_rieng_le,40.249,Colistimethate for Injection U.S.P,Colistin*,01,Thành phố Hà Nội,Bv Bưu Điện (Bộ Bưu Chính V.Thông),01009,Bv Bưu Điện (Bộ Bưu Chính V.Thông),40.249,...,NaT,2022-03-03,NaT,2022-12-31,None,Hoa Kỳ,Colistin*,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.10. Thuốc KS khác,Colistin*
3,3.thau_rieng_le,40.249,Colistimethate for Injection U.S.P.,Colistin*,92,Thành phố Cần Thơ,Bv Trường Đhyd Cần Thơ,92115,Bv Trường Đhyd Cần Thơ,40.249,...,NaT,2022-03-23,NaT,2023-03-23,None,Hoa Kỳ,Colistin*,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.10. Thuốc KS khác,Colistin*
4,3.thau_rieng_le,40.249,Colistimethate for Injection U.S.P.,Colistin*,79,Thành phố Hồ Chí Minh,Bv Nguyễn Tri Phương,79013,Bv Nguyễn Tri Phương,40.249,...,NaT,2022-04-15,2022-04-15,2023-04-25,None,Hoa Kỳ,Colistin*,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.10. Thuốc KS khác,Colistin*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,79,Thành phố Hồ Chí Minh,Bv Quân Y 7a/Cục Hậu Cần-Kỹ Thuật/Quân Khu 7,79016,Bv Quân Y 7a/Cục Hậu Cần-Kỹ Thuật/Quân Khu 7,40.232,...,NaT,2026-07-23,2026-07-31,2027-07-30,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.6. (cont) Thuốc điều trị lao kháng thuốc,Moxifloxacin
89,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,44,Tỉnh Quảng Bình,Bv Hữu Nghị Việt Nam-Cuba Đồng Hới,44005,Bv Hữu Nghị Việt Nam-Cuba Đồng Hới,40.232,...,NaT,2026-07-10,2026-07-10,2027-07-10,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.7. Thuốc KS nhóm quinolon,Moxifloxacin
90,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,44,Tỉnh Quảng Bình,Bv Hữu Nghị Việt Nam-Cuba Đồng Hới,44005,Bv Hữu Nghị Việt Nam-Cuba Đồng Hới,40.232,...,NaT,2026-07-10,2026-07-10,2027-07-10,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.6. (cont) Thuốc điều trị lao kháng thuốc,Moxifloxacin
91,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,01,Thành phố Hà Nội,Bv E,01007,Bv E,40.232,...,NaT,2026-07-01,2026-07-01,2027-06-30,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.7. Thuốc KS nhóm quinolon,Moxifloxacin
92,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,01,Thành phố Hà Nội,Bv E,01007,Bv E,40.232,...,NaT,2026-07-01,2026-07-01,2027-06-30,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.6. (cont) Thuốc điều trị lao kháng thuốc,Moxifloxacin

# Tính tổng, giá trị trung bình

In [5]:
# Tính tổng số lượng theo quốc gia
loader.average(
    value_col='soluong',
    groupby='country'
)

country
Ai Cập             9500.000000
Anh               19559.678322
Argentina          5948.571429
Ba Lan            54061.115880
Bangladesh        19846.243094
Belarus            3257.583333
Brazil             2108.527778
Bulgaria          29374.845161
Bắc Macedonia      1547.034483
Bỉ                 6112.687500
Bồ Đào Nha        28655.265690
Canada            16098.536585
Chile               575.000000
Croatia           21115.312500
Cuba                825.480000
Hoa Kỳ            12026.163955
Hungary           31953.149847
Hy Lạp            15811.761329
Hà Lan             8278.419355
Hàn Quốc          75491.292904
Iceland            3000.000000
Indonesia         12267.955224
Ireland           30512.307418
Latvia            25923.381579
Litva             35050.000000
Malaysia           9364.375000
Malta             38636.671642
Na Uy              4314.565657
New Zealand        2000.000000
Nga                1054.784091
Nhật Bản           4770.867689
Pakistan          63079.945946
Phillipines       20000.000000
Pháp              28651.505051
Phần Lan          24322.000000
Puerto Rico       32714.262626
Romania          108855.135229
Singapore          9532.589404
Slovakia          14762.955882
Slovenia          88653.711409
Séc               36774.962963
Síp               32121.719198
Thái Lan          15807.365297
Thổ Nhĩ Kỳ         3142.793548
Thụy Sĩ            6355.555885
Thụy Điển         21493.690112
Triều Tiên         1000.000000
Trung Quốc        15782.409524
Tây Ban Nha       40777.925672
Ukraine           40020.703822
Việt Nam        97323.286949
Việt Nam          97405.203378
Yemen             90000.000000
Áo                 4142.575545
Úc                20902.651072
Ý                 12124.241817
Đan Mạch          12516.831373
Đài Loan          25527.423267
Đức               37824.647735
Ấn Độ             53361.344693
Name: soluong, dtype: float64

In [6]:
# Tính tổng số lượng theo quốc gia trong khoảng thời gian công bố nhất định
loader.filter(
    column='congbo',
    value=pd.to_datetime('2026-04-24')
).average(
    value_col='soluong',
    groupby='country'
)

country
Anh             6632.833333
Ba Lan          1766.666667
Bỉ             14025.000000
Bồ Đào Nha         0.000000
Hoa Kỳ         14093.800000
Hungary         1475.000000
Hy Lạp         12943.333333
Hà Lan          1050.000000
Hàn Quốc         800.000000
Ireland        10053.750000
Na Uy            140.000000
Nhật Bản         904.857143
Pakistan           0.000000
Pháp           33586.565217
Puerto Rico    84750.000000
Romania        22933.333333
Slovenia       80000.000000
Séc              150.000000
Thụy Sĩ         6834.400000
Thụy Điển       1855.000000
Tây Ban Nha    12346.750000
Việt Nam     93897.571823
Việt Nam       93897.571823
Úc             52500.000000
Ý               4131.208333
Đài Loan       28010.000000
Đức            77426.357143
Ấn Độ           2684.250000
Name: soluong, dtype: float64

In [ ]:
# Tính giá trung bình theo nhóm
loader.average(
    value_col='gia',
    groupby='Loại thuốc 2'
)

Loại thuốc 2
1.1. Thuốc gây tê gây mê                       1.788695e+05
10. Thuốc chống parkinson                      1.067775e+04
11.1. Thuốc chống thiếu máu                    9.507248e+02
11.2. Thuốc tác dụng lên quá trình đông máu    2.039030e+04
11.3. Máu và chế phẩm máu                      8.682206e+05
                                                   ...
8.1. Hóa chất                                  2.672811e+05
8.2. Thuốc điều trị đích                       2.964832e+06
8.3. Thuốc điều trị nội tiết                   1.173762e+06
8.4. Thuốc điều hòa miễn dịch                  4.892872e+04
9. Thuốc điều trị bệnh đường tiết niệu         7.181130e+03
Name: gia, Length: 78, dtype: float64

# Kiểm tra các giá trị chưa được lọc

In [ ]:
# Các giá trị nhà sản xuất đã qua bộ lọc
loader.get_matched(config_type='producer')

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,3.thau_rieng_le,40.798,Dorobay 50mg,Acarbose,37,Tỉnh Ninh Bình,Pkđk Hợp Lực-Hà Nội,37097,Pkđk Hợp Lực-Hà Nội,40.798,...,2022-10-28,2022-05-23,NaT,NaT,DMC,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
1,2.thau_tinh,40.798,Dorobay 100 mg,Acarbose,33,Tỉnh Hưng Yên,Tỉnh Hưng Yên,None,None,None,...,2022-10-31,2022-08-30,NaT,NaT,DMC,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
2,3.thau_rieng_le,40.798,Dorobay 100 mg,Acarbose,79,Thành phố Hồ Chí Minh,Bv Đhyd Tp Hồ Chí Minh,79431,Bv Đhyd Tp Hồ Chí Minh,40.798,...,NaT,2026-07-20,2026-07-20,2028-01-19,DMC,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
3,3.thau_rieng_le,40.798,Dorobay 50mg,Acarbose,37,Tỉnh Ninh Bình,Pkđk Hợp Lực-Hà Nội,37097,Pkđk Hợp Lực-Hà Nội,40.798,...,2022-10-28,2022-05-23,NaT,NaT,DMC,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
4,2.thau_tinh,40.798,Dorobay 100 mg,Acarbose,33,Tỉnh Hưng Yên,Tỉnh Hưng Yên,None,None,None,...,2022-10-31,2022-08-30,NaT,NaT,DMC,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263619,3.thau_rieng_le,HD.150,Hoastex,"Húng chanh, Núc nác, Cineol",46,Tỉnh Thừa Thiên Huế,Tyt Khe Tre Cơ Sở 4,46157,Tyt Khe Tre Cơ Sở 4,HD.150,...,NaT,2026-05-05,2026-05-05,2027-05-05,OPC,Việt Nam,None,NaN,NaN,NaN
263620,3.thau_rieng_le,HD.222.18,Dầu nóng mặt trời,"Camphor, Tinh dầu bạc hà, Tinh dầu quế, Methyl...",95,Tỉnh Bạc Liêu,Tyt Hoà Bình,95069,Tyt Hoà Bình,HD.222.18,...,NaT,2026-05-20,2024-01-23,2025-01-23,OPC,Việt Nam,None,NaN,NaN,NaN
263621,3.thau_rieng_le,HD.222.18,Dầu nóng mặt trời,"Camphor, Tinh dầu bạc hà, Tinh dầu quế, Methyl...",95,Tỉnh Bạc Liêu,Tyt Hoà Bình,95069,Tyt Hoà Bình,HD.222.18,...,NaT,2026-04-20,2024-01-23,2025-01-23,OPC,Việt Nam,None,NaN,NaN,NaN
263622,3.thau_rieng_le,HD.150,Hoastex,"Húng chanh, Núc nác, Cineol",95,Tỉnh Bạc Liêu,Tyt Hoà Bình,95069,Tyt Hoà Bình,HD.150,...,NaT,2026-05-20,2024-01-23,2025-01-23,OPC,Việt Nam,None,NaN,NaN,NaN
263623,3.thau_rieng_le,HD.150,Hoastex-S,"Húng chanh, Núc nác, Cineol",96,Tỉnh Cà Mau,Bvđk Phú Tân,96066,Bvđk Phú Tân,HD.150,...,NaT,2026-04-07,2026-04-07,2028-04-07,OPC,Việt Nam,None,NaN,NaN,NaN

In [ ]:
# Kiểm tra các giá trị hoạt chất chưa được filter 
loader.get_unmatched(config_type='ingred')

['Cephalexin',
 'Mỗi gói 1g chứa Cefpodoxim (dưới dạng Cefpodoxim proxetil) 100mg',
 'Cephalexin (dưới dạng Cephalexin monohydrat)',
 'Ticarcillin + kali clavulanat',
 'Cephalexin (dưới dạng Cephalexin monohydrat compacted)',
 'Sultamicilin',
 'Mỗi chai 250ml chứa: Moxifloxacin (dưới dạng Moxifloxacin hydroclorid)',
 'Cephalexin (dưới dạng Cephalexin monohydrat) 500 mg',
 'Mỗi gói 1g chứa Amoxicilin (dưới dạng amoxicillin trihydrat) 250mg',
 'Amoxcilin+Sulbactam',
 'Sultamicilin (dưới dạng Sultamicilin tosilat dihydrat)',
 'Escin',
 'Amoxicilin( dưới dạng Amoxicilin tryhydrat powder)+ Acid clavunalic ( dưới dạng clavunalat kali: syloid 1:1)',
 'Mỗi gói\xa01g chứa Cefpodoxim (dưới dạng Cefpodoxim proxetil) 100mg',
 'Mỗi chai 250 ml chứa: Moxifloxacin (dưới dạng Moxifloxacin hydroclorid) 400 mg',
 'Mỗi gói 2 g chứa: Cefixim (dưới dạng Cefixim trihydrat) 100mg',
 'Amoxcilin +\nSulbactam',
 'Mỗi gói\xa01g chứa Cefixim (dưới dạng Cefixim trihydrat)',
 'Natri aescinat',
 'Mỗi gói 1g chứa Amoxicilin (Dưới dạng Amoxicillin trihydrat)',
 'Mỗi gói 1g chứa Amoxicilin ( Dưới dạng Amoxicillin trihydrat)',
 'Mỗi 20ml chứa Ciprofloxacin 200mg',
 'Acid Clavulanic (dưới dạng kali Clavulanat - Avicel (1:1)) 62,5mg; Amoxicilin (dưới dạng Amoxicilin trihydrat) 500mg',
 'Acid clavulanic (dưới dạng Kali clavulanat - syloid (1:1)) 31,25mg; Amoxicilin (dưới dạng Amoxicilin trihydrat powder) 250mg',
 'Ceftazidime + Avibactam',
 'Acid clavulanic (dưới dạng clavulanat kali : syloid 1:1) 62,5mg; Amoxicilin (dưới dạng amoxicilin trihydrat powder) 250mg',
 'Prescription medicine',
 'Piperacilin + tazobacta',
 'Acid Clavulanic (dưới dạng Kali Clavulanat kết hợp với Avicel 1:1) 42,9mg +Amoxicilin (dưới dạng Amoxicilin trihydrat) 600mg',
 'Acid clavulanic (dưới dạng Kali clavulanat - Syloid (1:1)) 31,25mg+ Amoxicilin (dưới dạng Amoxicilin trihydrat powder) 250mg',
 'Ethamsylat',
 'Cephalexin 250mg/gói',
 'Mỗi gói 3g thuốc bột chứa: Cefadroxil ( dưới dạng Cefadroxil monohydrat compact) 250mg',
 'Cloramphenicol',
 'Streptomycin',
 'Mỗi gói 1,5g chứa: Albendazol',
 'Mỗi gói 3g thuốc bột chứa: Cefadroxil (dưới dạng Cefadroxil monohydrat compact) 250 mg',
 'Mỗi lọ 100 ml chứa: Levofloxacin 500 mg',
 'Cephalexin 250 mg',
 'Mỗi ống 1ml dung dịch chứa: Morphin Sulfat 10 mg',
 'Cephalexin (dưới dạng Cephalexin monohydrat compacted) 500mg',
 'Amoxiccilin (dưới dạng Amoxicilin trihydrat)',
 'L-ornithin L-aspartat',
 'Tinidazole',
 'Cephalexin (dưới \ndạng Cephalexin \nmonohydrat \ncompacted)',
 'Mỗi lọ 200ml chứa Ciprofloxacin (dưới dạng Ciprofloxacin lactat)',
 'Metformin hydroclorid + Vildagliptin',
 'Pentoxifylin',
 'Acid zoledronic',
 'Cephalexin (dưới \ndạng Cephalexin monohydrat \ncompacted)',
 'Mỗi 5ml hỗn dịch sau pha chứa Azithromycin (dưới dạng Azithromycin TM granules 7,5% w/w)',
 'Cephalexin (dưới dạng Cephalexinmonohydrat compacted)',
 'L-Ornithin L-Aspartat',
 'Acid alpha lipoic',
 'Mỗi lọ 250ml chứa Moxifloxacin (dưới dạng Moxifloxacin hydroclorid) 400mg',
 'Metformin hydroclorid 1000mg; Vildagliptin 50mg',
 'Acid Clavulanic (dưới dạng Kali clavulanat + cellulose vi tinh thể tỷ lệ 1:1); Amoxicilin (dưới dạng Amoxicilin trihydrat)',
 'Phenoxy methylpenicilin',
 'Adrenalin (Dưới dạng Adrenalin bitartrat)',
 'Leucovorin (folinic acid)',
 'Benzylpenicillin natri',
 'Cephalothin (dưới dạng cephalothin natri)',
 'Phenoxy methyl penicilin',
 'Folinic acid',
 'Ampicillin',
 'Phenoxy methyl penicillin kali',
 'Irbesartan+Hydrochorothiazid',
 'Ampicillin (dưới dạng Ampiccillin Natri)',
 'Sulfamethoxazol, Trimethoprim',
 '"Cefazolin\n(dưới dạng Cefazolin natri)"',
 'Acid ursodeoxycholic',
 'Imipenem + Cilastalin',
 'Sulfamethoxazol 400mg+ Trimethoprim 80mg',
 'Acid clavulanic (dưới dạng Kali clavulanat) 0,2g+ Amoxicilin (dưới dạng Amoxicilin natri) 1g',
 'Acid clavulanic (dùng dạng kali clavulanat + cellulose vi tinh thể; tỉ lệ 1:1) 62,5mg; Amoxicilin (dùng dạng Amoxicilin trihydrat) 500mg',
 'Adrenalin (dưới dạng adrenalin bitartrat) (tương đương 1,8mg)',
 'Acid clavulanic (dưới dạng Kali clavulanat) 0,2g+ Ticarcillin (dưới dạng Ticarcillin natri) 3g',
 'Amoxicilin+ Acid Clavunalic',
 'Mỗi 5 ml chứa: Moxifloxacin (dưới dạng Moxifloxacin hydroclorid) 25 mg',
 'Mỗi lọ 5 ml chứa Tobramycin (dưới dạng Tobramycin Sulfat) 15 mg',
 'Mỗi ống 2ml dung dịch tiêm chứa Tobramycin (dưới dạng tobramycin sulfat) 80 mg',
 'Cephalexin\n(dưới dạng Cephalexin monohydrat)',
 'Adrenalin (dưới dạng Adrenalin bitartrat)',
 'Mỗi gói 2,1 g chứa: Cefdinir 100 mg',
 'Mỗi gói 1,4g chứa Cefixim (dưới dạng cefixim trihydrat)',
 'Mỗi gói 1,4g chứa Cefixim (dưới dạng cefixim trihydrat) 100 mg',
 'Adrenalin (dưới dạng Adrenalin bitartrat) (tương đương 1,8mg)',
 'Mỗi gói 3,5g chứa Cefuroxim (dưới dạng Cefuroxim axetil) 125mg',
 'Mõi gói 2,1 g chứa Cefadroxil (dưói dang Cefadroxil monohydrat)',
 'Ampicillin (dùng dạng Ampicillin natri)',
 'Cilastatin \n(dưới dạng\nCilastatin natri) + Imipenem \n(dưới dạng\nImipenem monohydrat)',
 'Cephalexin\n(dạng Cephalexin monohydrat)',
 'Mỗi 5ml dung dịch chứa: Ciprofloxacin (dưới dạng Ciprofloxacin Hydroclorid) 15mg',
 'Mỗi ml dung dịch chứa: Timolol (dưới dạng Timolol maleat)',
 'Acid clavulanic (dạng kali clavulanat + avicel (1:1)) 62,5mg; Amoxicilin (dưới dạng amoxicilin trihydrat) 500mg',
 'Mỗi 5ml hỗn dịch chứa: Cefpodoxim (dạng cefpodoxim) 100mg',
 'Acid clavulanic (dùng dạng kali clavulanat + cellulose vi tinh thể; tỉ lệ 1 :1) 31,25mg; Amoxicilin (dùng dạng amoxicilin trihydrat) 250mg',
 'Mỗi lọ chứa: Oxacilin (dưới dạng Oxacilin natri) 1g',
 'Ampicillin (dùng dạng Ampicillin natri) 1g',
 'Mỗi 5ml chứa Timolol \n(dưới dạng Timolol maleat) 25ml',
 'Cephalexin (dạng Cephalexin monohydrat)',
 'Acid clavulanic (dưới dạng kali clavulanat + avicel tỉ lệ (1:1)); Amoxicilin (dưới dạng amoxicilin trihydrat)',
 'Eszopiclon',
 'Acid clavulanic (dưới dạng kali clavulanat + avicel (1:1)); Amoxicilin (dưới dạng amoxicilin trihydrat)',
 'Acid clavulanic (dưới dạng kali clavulanat + avicel (1 :1)); Amoxicilin (dưới dạng amoxicilin trihydrat)',
 'Acid clavulanic (dùng dạng kali clavulanat + avicel (1 :1)); Amoxicilin (dùng dạng amoxicilin trihydrat)',
 'Acid clavulanic (dưới dạng kali clavulanat + avicel (1 :1)) 125mg; Amoxicilin (dưới dạng amoxicilin trihydrat) 875mg',
 'Cephalothin',
 'Mỗi 15g chứa: Metronidazol 150mg',
 'Mỗi 5g chứa: Promethazin hydroclorid 100mg',
 'Ceftazidime',
 'Cephalothin (dưới dạng Cephalothin natri) 1000mg',
 'Cephalothin (dưới dạng Cephalothin natri)',
 'Cefazoline',
 'ceftazidime (dưới dạng ceftazidime pentahydrate) 500mg',
 'Acid folic+sắt (II) sulfat',
 'Acid folic + sắt sulfat',
 'Sofosbuvir',
 'Nevirapin',
 'Galantamine',
 'Mỗi lọ chứa Cephradin (dưới dạng hỗn hợp vô khuẩn Cephradin với L-Arginin)',
 'Ceftibuten',
 'Felodipine 5mg',
 'Ranitidin',
 'Acetaminophen + Tramadol HCl',
 'DL-alpha-Tocopheryl acetat',
 'Acetaminophen+ Tramadol HCl',
 'Cephalexin monohydrat',
 'Mỗi gói 2g chứa: Cefaclor (dưới dạng Cefaclor monohydrat)',
 'Mỗi lọ chứa: Cephradin (dưới dạng hỗn hợp vô khuẩn Cephradin với L-Arginin)',
 'Cephradin',
 'Mỗi gói chứa 2g: Cefaclor (dưới dạng cefaclor monnohydrat)',
 'Cephalexin (dưói dang Cephalexin monohydrat)',
 'Milrinone',
 'Acid Zoledronic',
 'Mỗi gói 1,5 g chứa: Cefixim (dưới dạng Cefixim trihydrat)',
 'Cefepime',
 'Hydroclorothiazide + Losartan potassium',
 'Acetaminophen 325mg; tramadol hydrochloride 37,5mg',
 'Desloratadine',
 'Acetaminophen + Tramadol hydrochloride',
 'Felodipine',
 'Hydroclorothiazid 25mg + Losartan kali 100mg',
 'Fexofenadine hydrochloride',
 'Acetaminophen 325mg; Tramadol hydrochloride 37,5mg',
 'Acid folic 0,35mg; Sắt (dưới dạng sắt (II) Sulfat khan) 50mg',
 'Sắt + acid folic',
 'Hydroclorothiazide; Losartan potassium',
 'Tatanol',
 'Đan sâm, Tam thất, Borneol',
 'Benzathin benzylpenicilin',
 'Acid fusidic + Hydrocortison acetat',
 'Desonid',
 'Ampicillin (dưới dạng Ampicillin natri)',
 'Mỗi 1g kem chứa Terbinafin hydroclorid',
 'Acid fusidic + Betamethason',
 'Ticarcillin + Kali clavulanat',
 'Betamethason (dưới dạng betamethason dipropionat) + Calcipotriol (dưới dạng monohydrat)',
 'Calcipotriol (dưới dạng monohydrat) + Betamethason (dưới dạng betamethason dipropionat)',
 'Mỗi tuýp 10g chứa: Betamethason (dưới dạng Betamethason dipropionat) 5 mg; Clotrimazol 100 mg',
 'Mỗi tuýp 15g kem chứa Acid fusidic (dưới dạng hemihydrat) 2%; Betamethason (dưới dạng este valerat) 0,1%',
 'Cao khô silybum marianum (Extractum Silybi mariani siccum) (tương đương silymarin 140mg)',
 'Hydrocortisone',
 'Cao khô silybum marianum (Extractum Silybi mariani siccum) (tương đương silymarin 140mg) 312mg',
 'Natri clorid + natri citrat + kali clorid + glucose khan',
 'Clarith romycin',
 'Natri clorid + Natri citrat dihydrat + Kali clorid + Glucose khan',
 'Mỗi tuýp 10g chứa: Erythromycin base 0,4g',
 'Mỗi gói 1,5 g chứa: Kẽm (dưới dạng Kẽm gluconat 70mg) lOmg',
 'Gói 2g thuốc chứa: Acid clavulanic (dưới dạng kali clavulanat  silicon dioxyd) + Amoxicilin (dưới dạng amoxicilin trihydrat)',
 'Metformin hydroclorid + Sitagliptin (dưới dạng Sitagliptin phosphat monohydrat)',
 'Acid clavulanic (dưới dạng kali clavulanat  silicon dioxyd) + Amoxicilin (dưới dạng amoxicilin trihydrat)',
 'Spiramycin; Metronidazol',
 'Gói 1,5g thuốc chứa: Amoxicilin (dưới dạng amoxicilin trihydrat)',
 'Mỗi 4,1g thuốc bột chứa: Natri clorid 520mg; Natri citrat dihydrat 580mg; Kali clorid 300mg; Glucose khan 2,7gam',
 'Methyprednisolon',
 'Fucidic acid',
 'Calci glucoheptonat+ Vitamin D3',
 'Simethicone 125 mg',
 'Sắt III (dưới dạng Sắt (III) Hydroxid Polymaltose complex)',
 'Calci glucoheptonat + vitamin D3',
 'Calci glucoheptonate + vitamin D3',
 'Mỗi 15g thuốc mỡ chứa: Calcipotriol ( Dưới dạng Calcipotriol monohydrat) 0,75mg + Betamethason dipropionat ( dưới dạng Betamethason dipropionat) 7,5mg',
 'Cefpodoxime ( dưới dạng CefpodoximmeProxetil) 100mg/5ml',
 'Cefpodoxime (dưới dạng Cefpodoxime proxetil)',
 'Calci glucoheptonate + Vitamin D3',
 'Calci+ (Vitamin B1; Vitamin B2; Vitamin B6; Vitamin D3; Vitamin E; Vitamin PP; Vitamin B5)+ Lysin HCl',
 'Lysin + Vitamin B1 + Vitamin B2 + Vitamin B6 + Vitamin D3 + Vitamin E +Vitamin PP + Vitamin B5 + Calci',
 'Alendronat natri +cholecalciferol (Vitamin D3)',
 'Calci glucoheptonat + Vitamin D3',
 'Neomycin (sulfat)',
 'Calcipotriol (dưới dạng Calcipotriol monohydrat) + Betamethason (dưới dạng Betamethason dipropionat)',
 'Mỗi gói 2,5g chứa (Magnesi hydroxyd 400mg + nhôm hydroxyd 400mg)',
 'Acid ascorbic',
 'Glycerin trinitrat',
 'Mỗi 7,5 ml chứa: Calci (dưới dạng calci lactat pentahydrat) 65 mg+ Vitamin B1 1,5 mg; Vitamin B2 1,75 mg; Vitamin B6 3,0 mg; Vitamin D3 200 IU; Vitamin E 7,5 IU; Vitamin PP 10 mg; Vitamin B5 5 mg+Lysin HCl 150 mg',
 'Cefpodoxime (dướidạng Cefpodoximeproxetil) 200 mg',
 'Vitamin (B1 + B6 + B12)',
 'Mỗi 5 ml hỗn dịch chứa: Sulfamethoxazol 200mg; Trimethoprim 40mg',
 'Nhôm hydroxid  + Magnesi hydroxid + Simethicon',
 'Mỗi ống 5 ml chứa: Sắt III (dưới dạng Sắt (III) Hydroxid Polymaltose complex)',
 'Calci (dưới dạng calci lactat pentahydrat) + Vitamin B1 + Vitamin B2 + Vitamin B6 + Vitamin D3 + Vitamin E + Vitamin PP +  Vitamin B5 + Lysin HCl',
 'Mỗi 60 ml chứa: Dexclorpheniramin maleat 24 mg+ Betamethason 3 mg',
 'Acid Ascorbic (dưới dạng Natri ascorbat)',
 'Vitamin A (Retinol palmitat) 4000 IU; Vitamin D3 (cholecalciferol) 400 IU',
 'Vitamin A (Retinol palmitat) 4000 IU + Vitamin D3 (cholecalciferol) 400 IU',
 'Carbocystein',
 'Vitamin A (Retinyl palmitat) + Vitamin D3 (Colecalciferol)',
 'Mỗi gói 2,5g chứa Cefradin 250mg',
 'Simethicone',
 'Mỗi tuýp 20g gel chứa: Natri diclofenac 0,2g',
 'Natri diclofenac',
 'Cinarizin',
 'Vitamin B2',
 'Vitamin A (Retinyl palmitat) + Vitamin D2 (Ergocalciferol)',
 'Mỗi 5ml: Dexamethason (dưới dạng Dexamethason Natri phosphat) 2mg',
 'Mỗi gói chứa (Magnesi hydroxyd 400mg + nhôm hydroxyd 400mg)',
 'Vitamin A (Retinol palmitat); Vitamin D3 (Cholecalciferol)',
 'Betamethason (dưới dạng Betamethason dipropionat) + Calcipotriol (dưới dạng Calcipotriol monohydrat)',
 'Vitamin A (Retinyl palmitat); Vitamin D2 (Ergocalciferol)',
 'Ifosfamid',
 'Dung dịch thẩm phân màng bụng (phúc mạc) và lọc máu',
 'Vinorelbin',
 'Epirubicin hydroclorid',
 'Glucose khan (dưới dạng glucose monohydrate) + Natri clorid+ Kali clorid + Trinatri citrat khan (dưới dạng Trinatri citrat. 2H20)',
 'Mỗi 25ml dung dịch chứa: Epirubicin hydroclorid 50mg',
 'Mỗi lọ 25ml chứa: Paclitaxel 150mg',
 'Nước cất',
 'Natri clorid + Kali Clorid + Trinatricitrat khan + Glucose khan',
 'Cồn 70° ( Cồn 94% 804,3ml/1000ml)',
 'Cồn 70',
 'Fludarabin phosphat',
 'Mỗi ống 10ml chứa: Sắt gluconat ( tương ứng với Sắt 50mg) 399 mg+ Đồng gluconat (tương đương với Đồng 0,7mg) 5mg+ Mangan gluconat (tương đương với Mangan 1,33mg) 10,77mg',
 'Mỗi lọ 5ml chứa; Doxorubicin hydroclorid 10mg',
 'Mỗi lọ 5ml chứa: Etoposid 100mg',
 'Gemcitabine',
 'N-Acetyl-DL-Leucin',
 'Epirubicin hydrochloride',
 'Meclofenoxat HCL',
 'Vinorelbin (dưới dạng Vinorelbin tartrat)',
 'Glucose khan (dưới dạng glucose monohydrate) + Natri clorid + Kali clorid + Trinatri citrat khan (dưới dạng Trinatri citrat. 2H20)',
 'Epirubicin hydrochlorid',
 'Epirubicin hydrocloride',
 'Meclofenoxat HCl',
 'Methotrexate 25mg/1ml',
 'Natri clorid + Kali clorid + Calci clorid.2H2O + Magnesi clorid.6H2O + Acid acetic',
 'Natri clorid, Kali clorid, Calci clorid.2H2O, Magnesi clorid.6H2O, Acid acetic',
 'Glucose khan + Natri clorid + Kali clorid + Trinatri citrat khan',
 'Natri clorid + Tri natricitrat khan (dưới dạng Tri natricitrat dihydrat)+ Kali Clorid+ Glucose khan (dưới dạng Glucose monohydrat)',
 'Methotrexate',
 'Dextrose monohydrat; Natri clorid; Natri lactat; Calci clorid 2H2O; Magnesi clorid 6H2O',
 'Natri clorid + Kali clorid+ Magnesi clorid.6H2O+ Acid  acetic+ Calci clorid.2H2O',
 'Natri clorid; Kali clorid; Magnesi clorid.6H2O; Acid  acetic; Calci clorid.2H2O',
 '5-FU',
 'Glucose khan (dưới dạng glucose monohydrate) + Natri clorid + Kali clorid + Trinatri citrat khan (dưới dạng Trinatri citrat. 2H2O)',
 'Meclofenoxat hydroclorid',
 'Sắt (dưới dạng sắt II sulfat khô) + Folic acid',
 'Mỗi lọ 5ml chứa: Levofloxacin (dưới dạng Levofloxacin hemihydrat) 25mg',
 'Glucose khan (dưới dạng glucose monohydrate) 2,7 g+ Natri clorid 0,52g+ Kali clorid 0,3g+ Trinatri citrat khan (dưới dạng Trinatri citrat. 2H20) 0,509 g',
 'Epirubicin hydroclorid 50mg/25ml',
 'L-Glutathion reduced 300mg',
 'N-Acetyl- DL-Leucin',
 'L-Glutathion reduced',
 'Glucose khan (dưới dạng Glucose monohydrate) + Natri clorid + Kali clorid + Trinatri citrat khan (dưới dạng Trinatri citrat.2H2O)',
 'Mỗi lít dung dịch chứa: Natri clorid 161mg + Kali clorid 5,5mg + Magnesi clorid.6H2O 3,7g + Acid acetic 8,8g + Calci clorid.2H2O 9,7g',
 'N-Acetyl DL-Leucin',
 'Glucose khan + Natri clorid + Kali clorid + Tri Natricitrat dihydrat',
 'Vinorelbin (dưới dạng vinorelbin tartrat)',
 'Natri clorid + Kali clorid + Magnesi clorid.6H2O + Acid acetic + Calci clorid.2H2O',
 'Glucose khan (dưới dạng glucose monohydrate) + Kali Clorid + Natri Clorid + Trinatri citrat khan (dưới dạng Trinatri citrat .2H2O)',
 'Natri Clorid+ Kali clorid+ Calci Clorid.2H2O+ Magnesi clorid.6H2O+ Acid acetic+ Dextrose',
 'Glucose khan (dưới dạng glucose monohydrate) +Kali Clorid+ Natri Clorid + Trinatri citrat khan (dưới dạng Trinatri citrat. 2H20)',
 'L-Ornithine-L-Aspartat',
 'Mỗi ống 10ml chứa: Sắt gluconat (tương ứng với Sắt 50mg) 399mg; Đồng gluconat (tương ứng với Đồng 0,7mg) 5mg; Mangan gluconat (tương ứng với Mangan 1,33mg) 10,77mg',
 'Glucose khan (dưới dạng Glucose monohydrat) 20g; Kali clorid 1,5g; Natri clorid 3,5g; Trinatricitrat khan (dưới dạng Tri natricitrat dihydrat) 2,545g',
 'Ô đầu, Địa liền, Đại hồi, Quế nhục, Thiên niên kiện, Uy Linh tiên, Mã tiền, Huyết giác, Xuyên khung, Methyl salicylat, Tế tân',
 'Ô đầu, Địa liền, Đại hồi,Quế chi, Thiên niên kiện, Uy Linh tiên, Mã tiền, Huyết giác, Xuyên khung, Methyl salicylat, Tế tân',
 'Chè dây',
 'Actiso,Rau đắng đất, Bìm bìm',
 'Cao xương hỗn hợp, Hoàng bá, Tri mẫu, Trần bì, Bạch thược, Can khương, Thục địa',
 'Ô đầu, Địa liền, Đại hồi, Quế nhục, Thiên niên kiện, Huyết giác, Methyl salicylat, Tế tân, Riềng',
 'Ô đầu, Địa liền, Đại hồi, Quế nhục, Thiên niên kiện, Uy Linh tiên, Mã tiền, Huyết giác, Xuyên khung, Methyl salicylat, Tế tân, Riềng',
 'Ô đầu, Địa liền, Đại hồi, Quế nhục, Thiên niên kiện,Uy Linh tiên, Mã tiền, Huyết giác, Xuyên khung, Methyl salicylat, Tế tân',
 'Ô đầu, Địa liền, Đại hồi,Quế chi, Thiên niên kiện, Huyết giác, Camphora, Riềng',
 'Betamethason dipropionat + Acid Salicylic',
 'Ô đầu; Địa liền; Đại hồi; Quế nhục; Thiên niên kiện; Uy linh tiên; Mã tiền; Huyết giác; Xuyên khung; Tế tân; Methyl salicylat',
 'Actiso, Rau đắng đất, Bìm bìm',
 'Acid Ursodeoxycholic',
 'Betamethason dipropionat + Acid salicylic',
 'Thục địa, Hoài sơn, Trạch tả, Cúc hoa, Thảo quyết minh, Hạ khô thảo, Hà thủ ô đỏ, Đương quy',
 'Sinh địa, Mạch môn, Huyền sâm, Bối mẫu, Bạch thược, Mẫu đơn bì, Cam thảo',
 'Metformin hydrochlorid + Sitagliptin (dưới dạng sitagliptin phosphat monohydrat)',
 'Natriclorid',
 'Đinh lăng, Bạch quả',
 'Telmisartan+Rosuvastatin',
 'Mỗi 10ml chứa: Natri clorid 90mg+Mỗi 10ml chứa: Natri clorid 90mg',
 'Sitagliptin (dưới dạng sitagliptin phosphat monohydrat) + Metformin hydrochlorid',
 'Irbersatan + hydroclorthiazid',
 'Cephalexin (dưới dạng cephalexin monohydrat)',
 'Calci lactat gluconat + Calci carbonat',
 'Magnesi trisilicat khan+ nhôm hydroxyd',
 'Magnesi trisilicat khan + Nhôm hydroxyd',
 'Sắt (II) clorid tetrahydrat+ Kẽm clorid + Mangan (II) clorid tetrahydrat + Đồng (II) clorid dihydrat+ Crom (III) Clorid hexahydrat + Natri molypdat dihydrat+ Natri selenit pentahydrat + Natri fluorid + Kali iodid',
 'Magnesi trisilicat khan + nhôm hydroxyd',
 'Mỗi 1ml chứa: Carbocistein 75mg',
 'Bacillusclausii',
 'Polyethylene glycol 400 + Propylene glycol',
 'Acetyl leucin (Acetyl-DL- Leucin/N-Acetyl-DL- leucin',
 'Calci polystyren sulfonat',
 'Cafein',
 'Polystyrene',
 'Clonidin',
 'Glycerin',
 'Calci Polystyren sulfonat',
 'Biotin (Vitamin H)',
 'Magnesi trisilicat khan +\nNhôm hydroxyd',
 'Fondaparinux sodium',
 'Sắt III hydroxyd polymaltose',
 'Calcipotriol (dưới dạng calcipotriol monohydrat) + Betamethason (dưới dạng betamethason dipropionat)',
 'Magnesi trisilicat khan +Nhôm hydroxyd',
 'Adrenalin (dưới \ndạng Adrenalin \ntartrat)',
 'Mỗi lọ 3 ml chứa: Amiodaron hydroclorid 150 mg',
 'Sắt (II) clorid tetrahydrat + Kẽm clorid + Mangan (II) clorid tetrahydrat + Đồng (II) clorid dihydrat + Crom (III) Clorid hexahydrat + Natri molypdat dihydrat + Natri selenit pentahydrat + Natri fluorid + Kali iodid',
 'Mỗi 1 ml chứa Digoxin 0,25mg',
 'Mỗi ống 2 ml dung dịch chứa: Piroxicam 40 mg',
 'Adrenalin (dưới \n dạng Adrenalin \n tartrat)',
 'Polyethylene glycol+ Propylene glycol',
 'Polystyren/ Calci polystyren sulfonat',
 'Magnesi trisilicat khan+ Nhôm hydroxyd',
 'Mỗi ml chứa Propranolol hydroclorid 1 mg',
 'Mỗi lọ 10 ml dung dịch chứa: Acetyl leucin 1g',
 'Mỗi lọ 1ml dung dịch chứa: Carboprost (dưới dạng Carboprost tromethamin 332 mcg) 250 mcg',
 'Mỗi ml dung dịch chứa: Ketotiíen (dưới dạng Ketotifen íumarat)',
 'Dibasic natri phosphat (dưới dạng Dibasic natri phosphat.7H2O) + Monobasic natri phosphat (dưới dạng Monobasic natri phosphat.H2O)',
 'Naloxone hydrochloride (dưới dạng naloxone hydrochloride dihydrate)',
 'Mỗi 1g chứa: Lidocain 25 mg + Prilocain 25 mg',
 'Vitamin C (dưới dạng ascorbat natri)',
 'Acetylleucine',
 'Adenosin',
 'Pilocarpin hydroclorid',
 'Lọ 133ml chứa: Dibasic natri phosphat (dưới dạng Dibasic natri phosphat.7H2O) 7,89g + Monobasic natri phosphat (dưới dạng Monobasic natri phosphat.H2O) 21,41g',
 'Acetylleucin',
 'Pilocarpin',
 'Terbinafine hydrochloride',
 'Pilocarpin hydroclorid 2% (w/v) (tương đương pilocarpin 1,7% (w/v))',
 'Vitamin H/Vitamin B8',
 'Vitamin H (biotin)',
 'Naloxone hydroclorid (dưới dạng Naloxone hydrocloride dihydrate)',
 'Naloxone hydrochloride (dưới dạng Naloxone hydrochloride \ndihydrate)',
 'Kali clorid; Macrogol; Natri bicarbonat; Natri clorid; Natri sulfat',

In [ ]:
# Quốc gia sản xuất
loader.get_unmatched(config_type='country')

['CTCP Dược phẩm Pharbaco Thái Bình',
 'UPSA SAS',
 '22091',
 'GN4.22385',
 'Grifols Biologicals LLC',
 'Medochemie Ltd - Central Factory. Cyprus',
 'CSSX Hàn Quốc, CSĐG Hà Lan',
 'Pharbaco,',
 'Pharbaco',
 'Công ty cổ phần Dược phẩm Pharbaco Thái Bình',
 '000',
 'Công ty cổ phần dược phẩm Hà Tây',
 'Công ty Cổ phần Vắc xin và Sinh phẩm Nha Trang',
 'Nước ngoài',
 'TD',
 'McNeil AB',
 'Cenexi - Pháp',
 'Ferring GmbH',
 'Factory C; Cyprus',
 'CTCP Dược phẩm Trung ương I – Pharbaco',
 'RomaniaGN1.22077',
 'Viên',
 'AD',
 'Central Factory',
 'OLIC (Thailand) Limited',
 'Công ty TNHH Dược phẩm Shinpoong Daewoo',
 'Công ty cổ phần Dược Vật tư y tế Hải Dương',
 'Rottendorf Pharma GmbH',
 'Baxter Healthcare Corporation',
 'HU',
 'Gedeon Richter Plc. - Hungary',
 'BG',
 'Laboratoice Aguettant',
 'Janssen Pharmaceutica N.V. - Bỉ',
 'Micro Labs Limited. Ấn Độ',
 'Siegfried Hameln Gmbh/ Germany',
 'Công ty Cổ phần XNK Y tế Domesco',
 'Lilly France',
 'Wockhardt-Ấn Độ',
 'Dai Han Pharm',
 'RM',
 'PT. Novell Pharmaceutical Laboratories',
 'Hàn QuốcGN2.22093',
 'Công ty cổ phần dược phẩm Am Vi',
 'Công ty Cổ phần Pymepharco',
 'RomaniaGN1.22151',
 'RO',
 'Ipca Laboratories Ltd. Ấn Độ',
 'Hậu Giang',
 'LB Nga',
 'Siegfried Hameln GmbH/ Germany',
 'Chi nhánh Công ty Cổ phần Dược phẩm Trung ương Vidipha  Bình Dương',
 'Teva Pharmaceutical Works Private Limited Company',
 'Moldova',
 'Laboratoire Aguettant',
 'San Marino',
 'Egis Pharmaceuticals Private Limited Company. Hungary',
 'TS',
 'RomaniaGN1.22084',
 'Việt Vam',
 'Ever.Áo  Đức',
 'AL',
 'Chi nhánh Công ty CPDP Agimexpharm - Bình Hòa',
 'Alcon Research, LLC',
 'Colombia',
 'Novartis Manufacturing NV',
 'Công ty cổ phần dược phẩm An Thiên',
 'Lietuva',
 'Synthon Hispania, SL - Spain',
 'Công ty TNHH Liên doanh Hasan - Dermapharm',
 'Công ty cổ phần dược phẩm Quảng Bình',
 'BỉGN1.22284',
 'Ipsen Pharma Biotech',
 'Hà Tây',
 'BLD',
 'CSSX BTP và ĐGSC: Fresenius Kabi Austria GmbH; CS ĐGTC và XX: Lek Pharmaceuticals d.d',
 'Fresenius Kabi Austria GmbH - Áo',
 'Baxter S.A',
 'Vanuatu',
 'Sun Pharmaceutical Industries Ltd-India',
 'Naprod Life Sciences Pvt. Ltd. - India',
 'CSSX BTP, ĐQSC, KN, XX lô: Merck Serono S.p.A,Ý; CSĐQ TC: Merck Serono S.A, Thuỵ Sỹ',
 'Taiho Pharmaceutical Co., Ltd. Tokushima Plant',
 'Laboratoires Galderma']

In [9]:
loader.get_unmatched(config_type='producer')

['Công ty cổ phần dược phẩm SaVi',
 'Công ty cổ phần dược phẩm SAVI',
 'Công ty cổ phẩn dược phẩm SaVi',
 'Công ty TNHH Hasan - Dermapharm',
 'Cty CPDP SaVi',
 'Công ty CP Dược phẩm SaVi',
 'Agimexpharm',
 'Savipharm',
 'Công ty Cổ phần Dược phẩm SaVi',
 'Chi nhánh công ty cổ phần dược phẩm Agimexpharm- Nhà máy sản xuất dược phẩm Agimexpharm',
 'CN Cty CPDP Agimexpharm - Nhà máy SX DP Agimexpharm',
 'Công ty cổ phần dược phẩm Sa Vi',
 'CN Cty CPDP Agimexpharm - Nhà máy SX DP Agimexpharm',
 'Công ty cổ phần dược phẩm Wealphar',
 'Công ty cổ phần dược phẩm Đạt Vi Phú',
 'Công ty cổ phần dược phẩm Khánh Hòa',
 'Công ty Cổ phần Dược phẩm Khánh Hòa',
 'Công ty cổ phần dược phẩm Sa Vi (Đ/c: Lô Z.01-02-03a KCN trong KCX Tân Thuận, phường Tân Thuận Đông, quận 7, Tp. HCM - Việt Nam)',
 'Công ty cổ phần dược phẩm Savi (Savipharm J.S.C)',
 'Công ty cổ phần dược phẩm Savi',
 'Công ty cổ phần Dược phẩm Khánh Hòa',
 'Công ty cổ phần dược phẩm Reliv',
 'Nhà máy HDPharma EU – Công ty cổ phần Dược vật tư y tế Hải Dương',
 'Nhà máy HDPHARMA EU – Công ty cổ phần Dược vật tư y tế Hải Dương',
 'Công ty Cổ Phần Dược Phẩm Reliv',
 'Nhà máy HDPHARMA EU - Công ty cổ phần Dược vật tư y tế Hải Dương',
 'Bayer AG',
 'Bayer Pharma AG',
 'Bluepharma - Indústria Farmacêutical, S.A.',
 'Bluepharma Industrial Farmaceutical S.A',
 'Bluepharma - Indústria Farmacêutical, S.A',
 'Bluepharma Indústria Farmacêutica, S.A',
 'Bluepharma - Indústria Farmacêutica, S.A.',
 'Bluepharma-Indústria Farmacêutica, S.A.',
 'Bluepharma - Indústria Farmacêutica, S.A',
 'Bluepharma- Indústria Farmacêutica, S.A',
 'Standard Chem.  Pharm. Co., Ltd.; 2nd plant',
 '2nd Plant, Standard Chem.  Pharm. Co., Ltd.. Đài Loan',
 '- Tên cơ sở đóng gói  xuất xưởng: Lamp San Prospero SPA) - Tên cơ sở sản xuất: Famar Italia, S.p.A',
 'Famar Italia S.p.A',
 'Famar Italia, S.p.A',
 'Công ty TNHH Phil Inter Pharma',
 'CTY TNHH Phil Inter Pharma',
 'Công ty Cổ phần Dược Vacopharm',
 'Phil Inter Pharma',
 'Korea United Pharm. Inc.',
 'Korea United Pharm. Inc',
 'Rafarm S.A',
 'Rafarm S.A.',
 'Zim Laboratories limited',
 'Laboratorios Cinfa, S.A - Spain (Cơ sở đóng gói sơ cấp và thứ cấp: Laboratorios Cinfa, S.A. (Địa chỉ: Travesía de Roncesvalles, 1, 31699 Olloki (Navarra), Spain)',
 'CSSX: Laboratorios Cinfa, S.A - Spain; CSĐG sơ cấp và thứ cấp: Laboratorios Cinfa, S.A.',
 'Rivopharm SA',
 'CTCP Dược phẩm Vĩnh Phúc',
 'Công ty CPDP Vĩnh Phúc',
 'Công ty CP DP Vĩnh Phúc',
 'Công ty Cổ phần Dược Phẩm Vĩnh Phúc',
 'Công ty Cổ phần Dược phẩm Vĩnh Phúc',
 'CN Cty CP DP Agimexpharm - NM SX DP Agimexpharm',
 'Công ty cổ phần dược phẩm Agimexpharm',
 'Công ty cổ phần dược phẩm Vĩnh Phúc',
 'Chi nhánh công ty cổ phần dược phẩm Agimexpharm - Nhà máy sản xuất dược phẩm Agimexpharm',
 'Chi nhánh Công ty CPDP Agimexpharm – Nhà máy sản xuất dược phẩm Agimexpharm',
 'Công ty Cổ Phần Dược Phẩm Vĩnh Phúc',
 'Chi nhánh Công ty CPDP Agimexpharm - Nhà máy SX Dược phẩm',
 'Công ty Cổ phần dược phẩm Vĩnh phúc',
 'Chi nhánh CTCP Dược phẩm Agimexpharm - Nhà máy SX dược phẩm Agimexpharm',
 'CN Công ty CPDP Agimexpharm - Nhà máy SX DP Agimexpharm',
 'Công ty cổ phần Dược phẩm Vĩnh Phúc',
 'Công ty TNHH dược phẩm Đạt Vi Phú',
 'Công ty Cổ Phần Dược Phẩm Đạt Vi Phú',
 'Công ty Cổ phần Dược phẩm Đạt Vi Phú',
 'Công ty CP Dược phẩm Vĩnh Phúc',
 'Công ty CPDP SaVi',
 'Công ty cổ phần dược phẩm Bắc Ninh',
 'Công ty CP dược phẩm OPV',
 'Công ty cổ phần Dược Hà Tĩnh',
 'Công ty cổ phần dược phẩm TV.PharmViệt Nam',
 'Cty CPDP Trung ương 2',
 'CN Công ty Cổ phần dược phẩm Trường Thọ',
 'Công ty TNHH Dược phẩm Glomed',
 'Chi nhánh CTCPDPTrường Thọ',
 'Công ty cổ phần vật tư y tế Hải Dương',
 'Cty CPDP Khánh Hòa',
 'Công ty cổ phần dược phẩm Tipharco',
 'Công ty CP Dược phẩm Boston Việt Nam',
 'Công ty Cổ phần Dược phẩm Sao Kim',
 'Cty CPD Hậu Giang',
 'Công ty CP DP Phương Đông',
 'Vidipha',
 'Công ty TNHH Liên doanh Stellapharm - Chi Nhánh 1',
 'Công ty Cổ Phần Hóa-Dược Phẩm Mekophar.',
 'Hà Tây',
 'Công ty Cổ phần Dược Danapha',
 'Công ty cổ phần dược phẩm TV.Pharm',
 'Công ty CP DP Sao Kim',
 'Công ty Cổ phần Dược phẩm Bos Ton Việt Nam',
 'Công ty Cổ phần Dược phẩm Boston Việt Nam',
 'Công ty TNHH Liên Doanh Stellapharm-Chi nhánh 1, Việt Nam',
 'Công ty cổ phần dược phẩm Phương Đông',
 'Công ty cổ phần dược phẩm Me Di Sun',
 'Công ty cổ phần dược phẩm Nam Hà',
 'Công ty TNHH Liên doanh Stellapharm - Chi nhánh 1',
 '"Công ty TNHH Liên doanh Stellapharm - Chi Nhánh 1"',
 'Công ty Cổ Phần Hóa - Dược Phẩm Mekophar',
 'Công ty CP Dược Danapha',
 'Công ty TNHH Liên doanh Stellapharm-Chi nhánh 1',
 'Công ty Cổ phần Dược Medipharco',
 'Công ty cổ phần dược phẩm Sao Kim',
 'Công ty cổ phần Fresenius Kabi Việt Nam',
 'Công ty CP Fresenius Kabi Việt Nam',
 'Công ty TNHH Liên doanh Stellapharm- Chi nhánh 1',
 'Công ty Cổ phần Dược phẩm An Thiên',
 'CT TNHH LD Stellapharm - CN 1',
 'Công ty CP DP SaVi',
 'CTCP Fresenius Kabi Việt Nam',
 'Công ty CP DP Tipharco',
 'Công ty liên doanh Meyer-BPC',
 'Công ty liên doanh Meyer - BPC',
 'Cty TNHH LD Stellapharm-CN 1',
 'Công ty Cổ phần Fresenius Kabi Việt Nam',
 'Công ty Cổ phần SPM',
 'Công ty TNHH Thái Nakorn Patana',
 'Công ty Cổ phần Dược phẩm OPV',
 'Công ty cổ phần Dược phẩm Trung ương 3',
 'Cty liên doanh Meyer-BPC',
 'Công ty CP DP Am Vi',
 'Công ty cổ phần Dược phẩm Phương Đông',
 'Công ty cổ phần dược phẩm An Thiên',
 'Công Ty TNHH Dược Phẩm Allomed',
 'Công ty Cổ phần Dược Phẩm Amvi',
 'Công ty Cổ phần Dược phẩm Bến Tre',
 'Công Ty Cổ Phần Dược Phẩm An Thiên',
 'Công ty Cổ phần Dược phẩm Am Vi',
 'Công ty cổ phần hóa-dược phẩm Mekophar',
 'Công ty cổ phần dược phẩm Am Vi',
 'Công ty Cổ phần Hóa - Dược phẩm Mekophar',
 'Chi nhánh Cty TNHH Stada -VN',
 'Chi nhánh cty TNHH Liên danh Stellapharm-Chi nhánh I',
 'Cty CP Fresenius Kabi - Việt Nam - Việt Nam',
 'Công ty cổ phần dược phẩm TV.Pharm - Việt Nam',
 'Công ty cổ phần Dược phẩm SaVi',
 'Công ty CP hoá-dược phẩm Mekophar',
 'Công ty Cổ Phần Dược Phẩm Sao Kim',
 'Cty CP Fresenius Kabi Việt Nam',
 'Stellapharm',
 'Công ty TNHH Liên doanh Stellapharm-chi nhánh 1',
 'Công ty cổ phần dược phẩm Khánh Hoà',
 'CT TNHH Liên Doanh Stellapharm – Chi nhánh 1',
 'CT CP Dược Phẩm Sao Kim',
 'Công ty TNHH Thai Nakorn Patana',
 'Fresenius Kabi Việt Nam',
 'Công ty TNHH LD Stellapharm - Chi nhánh 1',
 'Công ty cổ phần dược phẩm Tv.Pharm, Việt nam',
 'Công ty CP DP Hà Tây',
 'Công ty cổ phần dược trung ương Mediplantex',
 'Công ty TNHH Liên Doanh Stellapharm – Chi nhánh 1',
 'Công ty TNHH MTV Dược phẩm DHG',
 'Công ty CP Dược phẩm Phương Đông',
 'Công ty cổ phần dược Đồng Nai',
 'Công ty cổ phần dược S.Pharm',
 'CÔNG TY TNHH DP ĐÔ THÀNH',
 'Công ty CP Hóa-Dược phẩm Mekophar',
 'Công ty cổ phần dược phẩm S.Pharm',
 'CTCP Dược Hà Tĩnh',
 'CTCP DP An Thiên',
 'CTCP Dược phẩm Tipharco',
 'Công ty TNHH liên doanh Stellapharm-chi nhánh1',
 'CTCP Dược phẩm 2/9',
 'CôngtyTNHHliêndoanhStellapharm-Chinhánh1',
 'Agimexpharm- Việt Nam',
 'Công ty CPDP An Thiên',
 'Công ty Cổ Phần Dược Phẩm Phương Đông',
 'Công ty cổ phần Dược phẩm Me Di Sun',
 'Công ty cổ phần dược phẩm 2/9',
 'Chi nhánh Công ty cổ phần dược phẩm Agimexpharm - Nhà máy sản xuất dược phẩm Agimexpharm',
 'Cty CP Dược Hà Tĩnh',
 'Công ty Cổ phần dược phẩm Sao Kim',
 'Công ty cổ phần dược Danapha',
 'Công ty TNHH Liên doanh Stellapharm -  Chi nhánh 1',
 'Công ty Cổ phần hóa-dược phẩm Mekophar',
 'Công ty cổ phần SPM',
 'Cty CP Dược Medipharco',
 'Công ty Cổ phần Dược phẩm Tipharco',
 'Công ty Cổ phần Dược VTYT Hải Dương',
 'Công ty cổ phần dược phẩm Vĩnh\nPhúc',
 'CTCP Dược phẩm Bắc Ninh',
 'CTCP Dược phẩm OPV',
 'Hải Dương',
 'Công ty cổ phần dược\n phẩm An Thiên',
 'Chi nhánh Công ty CPDP Agimexpharm - Nhà máy SX DP Agimexpharm',
 'Công ty cổ phần Dược trung ương 3',
 'Chi nhánh công ty cổ phần Dược phẩm Agimexpharm - Nhà máy sản xuất Dược phẩm Agimexpharm',
 'Công ty TNHH Dược phẩm BV Pharma',
 'Công Ty TNHH Liên Doanh Stellapharm - Chi nhánh 1',
 'Công ty cổ phần Hóa - Dược phẩm Mekophar',
 'Công ty Cổ phần Dược Trung ương Mediplantex',
 'CTCP Dược phẩm Sao Kim',
 'Công ty TNHH liên doanh Stellapharm- Chi nhánh 1',
 'Công Ty Cổ Phần Dược Phẩm OPV',
 'Công ty TNHH Dược Phẩm Allomed',
 'CN CT TNHH SX-TM DP Thành Nam. Việt Nam',
 'Công ty cổ phần dược phẩm Vĩnh Phúc. Việt Nam',
 'Công ty TNHH  Liên doanh Stellapharm - Chi nhánh 1',
 'Công ty cổ phần Dược S.Pharm',
 'Công ty TNHH LD Stada-Việt Nam',
 'Công ty cổ phần Dược Đồng Nai',
 'Công ty cổ phần\n dược phẩm Tipharco',
 'Công ty cổ phần dược phẩm  Phương Đông',
 'Công ty cổ phần dược vật tư y tế Hải Dương',
 'Công ty cổ phần dược TW Mediplantex',
 'Công ty cổ phần dược phẩm Công nghệ cao Abipha',
 'Công ty TNHH Thai Nakorn Patana Việt Nam',
 'CTCP Dược phẩm An Thiên',
 'Công ty TNHH dược phẩm Allomed',
 'Công ty Cổ phần Dược phẩm Fremed',
 'Công ty TNHH Liên Doanh Stellapharm - Chi nhánh 1',
 'Công ty TNHH sản xuất dược phẩm Nanogen Lâm Đồng',
 'Công ty Cổ phần Dược Trung ương Mediplantex. Việt Nam',
 'Công ty Liên doanh Meyer-BPC',
 'CTCP DP Phương Đông',
 'Công ty cổ phần dược phẩm Quảng Bình',
 'Công ty cổ phần Dược phẩm Boston Việt Nam. Việt Nam',
 'Công ty cổ phần \nFresenius Kabi Việt Nam',
 'Công ty TNHH Dược phẩm Allomed',
 'Công ty cổ phần Dược phẩm Tipharco',
 'Nhà máy HDPHARMA EU-Công ty cổ phần dược VTYT Hải Dương',
 'Công ty cổ phần Dược Phẩm An Thiên',
 'Công ty cổ phần liên doanh Dược phẩm Éloge France Việt Nam',
 'Công ty cổ phần S.P.M',
 'Nhà máy HDPHARMA EU- Công ty Cổ phần dược vật tư y tế Hải Dương',
 'Kern Pharma S.L.',
 'Công ty CP DP Savi',
 'Công ty cổ phần Dược phẩm Boston Việt Nam',
 'Công ty cổ phần dược phẩm OPV',
 'Nhà máy STADA - Việt Nam',
 'Công ty TNHH Dược phẩm BV pharma',
 'CTCP Dược phẩm Boston Việt Nam',
 'Công ty cổ phần Dược phẩm TV.Pharm',
 'Công ty Cổ phần S.P.M',
 'Công ty cổ phần dược và vật tư y tế Bình Thuận',
 'Công ty cổ phần dược phẩm Boston Việt Nam',
 'Công Ty Cổ phần Dược Phẩm Vĩnh Phúc',
 'Công ty Cổ phần Dược phẩm Bắc Ninh',
 'CTCP Dược Danapha',
 'Công ty CP Dược phẩm Sao Kim',
 'Công ty TNHH Liên Doanh Stellapharm - chi nhanh 1',
 'CN CT TNHH SX-TM DP Thành Nam',
 'Công ty TNHHdược phẩm Allomed',
 'CTCP Hóa dược Việt Nam',
 'CTCP Dược phẩm SaVi',
 'Chi nhánh công ty TNHH SX-TM dược phẩm Thành Nam',
 'Công ty TNHH sản xuất dược phẩm \nNanogen Lâm Đồng',
 'Công ty cổ phần Hóa dược Việt Nam',
 'Công TNHH Liên Doanh Stellapharm- Chi nhánh I',
 'G0285.Công ty Cổ phần Dược phẩm SaVi',
 'G0306.Công ty cổ phần dược phẩm Bắc Ninh',
 'Công ty Cổ phần US Pharma USA',
 'G0276.Công ty cổ phần dược S.Pharm',
 'G0265.Công ty TNHH dược phẩm Allomed',
 'CÔNG TY TNHH MTV DƯỢC PHẨM LA TERRE FRANCE',
 'CTCP Dược phẩm SaVi (Savipharm J.S.C)',
 'Công ty TNHH Sản xuất Thương mại Dược phẩm Thành Nam',
 'Công ty cổ phần Dược Danapha',
 'Công ty cổ phần dược phẩm 2/9 TP HCM',
 'Công Ty TNHH DP Allomed',
 'Công ty Cổ phần Dược phẩm Trung ương 3',
 'Công ty Cổ phần Dược phẩm Soha Vimex',
 'Công ty Cổ phần Medcen',
 'Công ty cổ phần Dược Phúc Vinh',
 'Công ty cổ phần US Pharma USA',
 'Công Ty CPDP 2/9',
 'Công ty CP Dược và VTYT Bình Thuận',
 'Công ty cổ phần dược phẩm SaVi (Savipharm J.S.C)',
 'Công ty TNHH MTV Dưoc pham DHG',
 'Công ty cổ phần dược Hà Tĩnh',
 'Công ty cổ phần Dược phẩm An Thiên',
 'CÔNG TY TNHH MTV DP LA TERRE FRANCE',
 'Nhà máy sản xuất thuốc tân dược - Công ty Cổ Phần Dược Phẩm Tipharco',
 'Chi nhánh công ty cổ phần Dược phẩm Agimexpharm-Bình Hòa',
 'UPSA SAS',
 'Chi nhánh Công ty cổ phần Dược phẩm Agimexpharm - Bình Hòa',
 'Chi nhánh công ty cổ phần dược phẩm Agimexpharm - Bình Hòa',
 'Công ty cổ phần Dược-TTBYT Bình Định',
 'Nhà máy Stada Việt Nam',
 'Chi nhánh Công ty Cổ phần Dược phẩm Agimexpharm - Bình Hòa',
 'GlaxoSmithKline Dungarvan Limited',
 'Fresenius Kabi Deutschland GmbH',
 'GlaxoSmithKline Consumer Healthcare Australia Pty Ltd.',
 'Aspen Pharma Pty., Ltd',
 'Aspen Pharma Pty Ltd',
 'Aspen Pharma Pty Ltd.',
 'GlaxoSmithKline Consumer Healthcare Australia Pty Ltd. - Úc',
 'Aspen Pharma Pty.,Ltd',
 'Aspen Pharma Pty Ltd.. Australia',
 'Pharmaceutical Works Polpharma S.A.',
 'Aflofarm Farmacja Polska Sp.zo.o.',
 'Aflofarm Farmacja Polska Sp. z o.o.',
 'S.M.B Technology SA',
 'S.M.B Technology S.A',
 'SMB Technology S.A',
 'SMB Technology S.A.',
 'S.M.B. Technology S.A.',
 'Standard Chem.  Pharm. Co., Ltd.',
 'Meditop Gyogyszeripari Kft.',
 'Uni-Pharma Kleon Tsetis Pharmaceutical Laboratories S.A.',
 'Demo S.A. Pharmaceutical Industry',
 'Upsa SAS',
 'Carelide',
 'UPSA SAS -Pháp',
 'UPSA SAS, Pháp',
 'UPSA SAS (Upsa SAS, )',
 'Upsa SAS (XX: Upsa SAS- France)',
 'Maco Productions',
 'UPSA SAS (Cơ sở xuất xưởng: Upsa SAS - Pháp)',
 'Aguettant Mouvaux',
 'UPSA SAS (Cơ sở xuất xưởng: UPSA SAS - Pháp)',
 'Upsa Sas',
 'Cơ sở sản xuất, đóng gói: UPSA SAS; Cơ sở xuất xưởng: UPSA SAS',
 'UPSA SAS,  (Cơ sở xuất xưởng: (Upsa SAS, đ/c: 979, Avenue des Pyrénées, 47520 Le Passage, France)',
 'CSSX, ĐG: UPSA SAS (CSXX: UPSA SAS - Pháp)',
 'Laboratoire Aguettant',
 'UPSA SAS - Pháp',
 'UPSA SAS; CSXX: Upsa SAS (đ/c: 979, Avenue des Pyrénées, 47520 Le Passage, France)',
 'UPSA SAS (CSXX: UPSA SAS - Pháp)',
 'KRKA, D.D., Novo Mesto',
 'KRKA, D.D., Novo mesto',
 'KRKA, D.D., . Novo Mesto',
 'B.BRAUN MEDICAL S.A',
 'Altan Pharmaceuticals, SA.',
 'Laboratorios Cinfa, S.A.',
 'Janssen-Cilag',
 'Janssen Cilag S.P.A.',
 'S.M. Farmaceutici SRL',
 'Pháp',
 'Công ty CP DP Dược liệu Pharmedic',
 'Công ty Cổ phần Dược phẩm Dược liệu Pharmedic',
 'Công ty Cổ Phần Dược Phẩm Dược Liệu Pharmedic',
 'Công ty CPDPDL Pharmedic',
 'Công ty cổ phần dược phẩm dược liệu Pharmedic',
 'Công ty cổ phần dược phẩm dược liệu Pharmedic',
 'Công Ty Cổ Phần Dược Phẩm Dược Liệu Pharmedic',
 'Công ty cổ phần dược liệu Pharmedic',
 'Công ty Cổ phần Dược phẩm Wealphar',
 'Cty CP Dược phẩm Vĩnh Phúc',
 'Công ty TNHH Liên doanh Stellapharm - Chi nhánh 1 - Việt Nam',
 'Công ty CPDP Vĩnh Phúc - Việt Nam',
 'Cty Cổ phần dược phẩm Vĩnh Phúc',
 'CÔNG TY cổ phần Dược phẩm Vĩnh Phúc',
 'Công ty CP DP TW CPC1',
 'Công ty Cổ Phần Dược Danapha',
 'Cty CP Dược Phẩm Vĩnh Phúc',
 'Công ty cổ phàn dược phẩm Khánh Hòa',
 'Công ty CPDP Khánh Hòa - Việt Nam',
 'Công ty Cổ phần Dược Phẩm Khánh Hòa',
 'Công ty cổ phần \nDược phẩm \nKhánh Hòa',
 'CTCP Dược VTYT Hải Dương',
 'Công ty cổ phần Dược VTYT Hải Dương',
 'Công ty cổ phần Dược phẩm Savi',
 'Công ty TNHH sản xuất dược phẩm Medlac Pharma Italy',
 'Công ty TNHH MTV Dược phẩm 150 Cophavina',
 'Cophavina',
 'Công ty CP Dược phẩm Savi',
 'Công ty Cổ Phần Dược Phẩm Khánh Hòa',
 'CTCP Dược vật tư y tế Hải Dương',
 'CÔNG TY CỔ PHẦN DƯỢC DANAPHA',
 'Công ty TNHH MTV dược phẩm 150 Cophavina',
 'Công ty Cổ Phần Dược Phẩm An Thiên',
 'Công ty Cổ Phần Dược Phẩm Tipharco',
 'Nhà máy 2 công ty TNHH liên doanh Hasan-Dermapharm',
 'PfMP_France',
 'Pierre Fabre Medicament Production',
 'PIERRE FABRE MEDICAMENT PRODUCTION',
 'Pierre Fabre Medicament production',
 'Pierre Fabre Medicament Production - Pháp',
 'Haupt Pharma',
 'Haupt Pharma. Pháp',
 'Haupt Pharma Livron',
 'Công ty CP DP Trung ương 2',
 'Công ty CP Dược phẩm Trung ương 2',
 'Công ty cổ phần dược phẩm Trung Ương 2',
 'CTCP Dược phẩm Trung ương 2',
 'Công ty TNHH liên doanh Stellapharm - Chi nhánh 1',
 'Công ty TNHH Sản xuất dược phẩm Medlac Pharma Italy',
 'CÔNG TY CỔ PHẦN DƯỢC PHẨM KHÁNH HÒA',
 'Công ty Cổ phần dược phẩm Fremed',
 'Công ty cổ phần  Dược phẩm An Thiên',
 'Công ty Cổ phần Dược phẩm Trung ương 2',
 'Công Ty TNHH Liên Doanh Stellaphar m - Chi nhánh 1',
 'Nhà máy HDPHARMA EU – Công ty cổ phần Dược vật tư y tế Hải Dương - Việt Nam',
 'Công ty cổ phần dược phẩm Trung ương 2',
 'Lindopharm GmbH',
 'CSSX: Lindopharm GmbH CSXX: Salutas Pharma GmbH',
 'Gentle Pharma Co.Ltd , Taiwan',
 'Esseti Farmaceutici S.r.l',
 'Esseti Farmaceutici S.R.L',
 'Esseti Farmaceutici S.r.l.',
 'Công ty Cổ phần Dược phẩm 2/9',
 'Công ty TNHH MTV 120 Armephaco',
 'CN Công ty CP DP TW Vidipha Bình Dương',
 'Công ty Cổ phần Dược phẩm Phương Đông',
 'Cty CP Dược-TTBYT Bình Định',
 'Công ty TNHH Liên doanh Stellapharm - CN1',
 'Công ty TNHH Liên doanh Stellapharm - Chi nhánh 1',
 'Chi nhánh công ty cổ phần dược phẩm trung ương Vidipha Bình Dương',
 'Agimexpharm - Việt Nam',
 'Chi nhánh công ty cổ phần dược phẩm trung ương Vidipha tại Bình Dương',
 'Khapharco Pharm',
 'Công ty cổ phần dược phẩm TW Mediplantex',
 'Công ty TNHH LD Stellapharm-Chi nhánh 1; Việt Nam',
 'Công ty cổ phần Dưoc-TTBYT Bình Định',
 'Công ty cổ phẩn dược và vật tư y tế Bình Thuận',
 'Cn Cty Cpdp Agimexpharm - Nhà MáY Sx Dp Agimexpharm',
 'Công ty cổ phần dược phẩm Phương ông',
 'CN công ty CPDP TW Vidipha Bình Dương',
 'Công ty Cổ phần Dược phẩm Agimexpharm',
 'Công ty Cổ phần Dược phẩm Khánh Hòa - Việt Nam',
 'Công ty TNHH liên doanh Stellapharm-Chi nhánh 1',
 'Công ty TNHH Liên Doanh Stellapharm-chi nhánh 2',
 'Chi nhánh công ty cổ phần dược phẩm Agimexpharm - Nhà máy sản xuất dược phẩm Agimexpharm',
 'Công ty CP dược vật tư y tế Hà Nam',
 'Công Ty Cổ Phần Dược Phẩm Khánh Hòa',
 'Công ty Cổ phần Dược phẩm Phương Đông',
 'Công ty TNHH dược phẩm BV Pharma',
 'Cty CP Dược vật tư y tế Hải Dương',
 'Chi nhánh Cty CPDP trung ương Vidipha Bình Dương',
 'Chi nhánh Công ty cổ phần dược phẩm Agimexpharm – Bình Hòa',
 'Công ty cổ phần Dược TW Mediplantex',
 'Công ty cổ phần  nghiên cứu và sản xuất Dược phẩm Meracine',
 'Công ty CPDP Khánh Hòa',
 'Công Ty Cổ Phần Dược Phẩm Savi',
 'Công ty CP Dược Trung ương Mediplantex',
 'Công Ty Cổ Phần Dược Phẩm SaVi',
 'Công ty cổ phần dược phẩm Fremed',
 'Cty CP nghiên cứu và SX Dược phẩm Meracine (Có cv thay đổi tên nhà sx)',
 'Công ty cổ phần dược phẩm trung ương Vidipha',
 'Công ty CP Dược VTYT Hà Nam',
 'Công ty cổ phần Dược Trung ương Mediplantex',
 'Công Ty Cổ Phần Dược S.Pharm',
 'CN Cty CPDP Agimexpharm - Bình Hoà',
 'Lindopharm GmbH; Xuất xưởng: Salutas Pharma GmbH',
 'Temmler pharma GmbH',
 'Lindopharm GmbH; Xuất xưởng: Salutas Pharma GmbH, Đức',
 'Lindopharm GmbH; Xuất xưởng: Salutas Pharma GmbH - Đức',
 'Lindopharm GmbH - Đức',
 'Lindopharm GmbH (XX: Salutas Pharma GmbH- Germany)',
 'Sản xuất: Lindopharm GmbH; Xuất xưởng: Salutas Pharma GmbH',
 'Lindopharm GMBH; Xuất xưởng: Salutas pharma GMBH',
 'Sản xuất: Lindopharm GmbH; \nXuất xưởng: Salutas Pharma GmbH',
 'SX: Lindopharm GmbH; XX: Salutas Pharma GmbH',
 'CSSX: Lindopharm GmbH\nCSXX: Salutas Pharma GmbH',
 'Sopharitex',
 'Công ty TNHH LD Stellapharm-Chi nhánh 1',
 'Công ty TNHH Liên Doanh Stellapharm-Chi nhánh 1',
 'Công ty Cổ Phần SPM',
 'Công ty cổ phần dược phẩm Trường Thọ',
 'Công ty cổ phần US pharma USA',
 'Công ty TNHH United International Pharma',
 'Công ty cổ phần dược phẩm TRƯỜNG THỌ',
 'Công ty CP DP TV.Pharm',
 'Chi nhánh Công ty cổ phần Dược phẩm Agimexpharm - Nhà máy sản xuất dược phẩm Agimexpharm',
 'CN Công ty CP DP Agimexpharm - Nhà máy SX DP Agimexpharm',
 'Công ty TNHH Liên Doanh Stellapharm - Chi nhán 1',
 'Chi nhánh Công ty cổ phần Dược phẩm Trung ương Vidipha Bình Dương',
 'Công ty Cổ phần US Pharma USA Việt Nam',
 'Chi nhánh công ty CPDP Agimexpharm-Nhà máy SX DP Agimexpharm',
 'Cty TNHH LD Stellapharm - CN 1',
 'Cty Liên Doanh Meyer-BPC',
 'Chi nhánh công ty cổ phần dược phẩm Agimexpharm - Nhà máy sản xuất dược phẩm Agimexpharm',
 'Công ty cổ phần Dược phẩm Sao Kim',
 'Sao Kim',
 'Công ty CPDP Agimexpharm',
 'Công ty cổ phần dược phẩm TV. Pharm',
 'Chi nhánh công ty CP DP TW Vidipha Bình Dương',
 'Công ty Cổ phần Dược phẩm BosTon Việt Nam',
 'Công ty CP dược Phẩm Trường Thọ',
 'Cty Liên Doanh Meyer - BPC',
 'Chi nhánh công ty  TNHH LD Stada - Việt Nam',
 'CTCP Dược phẩm Khánh Hòa',
 'Công ty TNHH  Mekophar',
 'Công ty TNHH Mekophar',
 'CTCP Dược phẩm Wealphar',
 'Công ty Cổ phần dược phẩm Trường Thọ',
 'Công ty cổ phần Armephaco- Xí nghiệp dược phẩm 150',
 'CT TNHH MTV DP 150 Cophavina. Việt Nam',
 'CTCP DP Trường Thọ',
 'CTCP DP Trường Thọ. Việt Nam',
 'Công ty cổ phần dược phẩm SaVi. Việt Nam',
 'Công ty TNHH Mekophar - Việt Nam',
 'C.ty CP DP Khánh Hòa',
 'Công ty Cổ phần Dược phẩm Savi',
 'G2361.Công ty cổ phần dược phẩm Khánh Hòa',