In [1]:
'''
Chỉnh working directory, k cần quan tâm lắm :))
'''

import sys
from pathlib import Path
# Add the project root directory (one level up from tests/)
sys.path.append(str(Path.cwd().parent))
import pandas as pd
import os

In [57]:
'''
Load các thư viện, function cần thiết.
    producer_config: cài đặt filter do chuyên viên nhập và điều chỉnh
    LoadMedicalData: class sử dụng để load, xử lý và tính toán
'''
%load_ext autoreload
%autoreload 2

from config.filter_config import producer_config, country_config
from src.utils.data_loader import LoadMedicalData

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
'''
Đoạn này thử đưa một đoạn dữ liệu vào để load. Sau khi chạy xong thì dữ liệu raw sẽ được lưu trong 'test_data'. Người dùng có thể thực hiện filter hoặc tính tổng từ đây.
'''

test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls' # đưa PATH đến data ở đây. 
test_data = LoadMedicalData(
    test_path, 
    config=producer_config # có thể thay đổi các config để tùy chỉnh bộ lọc
)

In [ ]:
# Hiển thị toàn bộ dữ liệu raw
test_data.show_data()

In [60]:
# Filter dữ liệu tùy theo config đưa vào
test_data.filter().show_data() # Nếu để trống phần filter sẽ trả về toàn bộ các mục mà được liệt kê trong config

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd,ticker
0,3.thau_rieng_le,40.158,"Nerusyn 1,5g",Ampicilin + sulbactam,11,Tỉnh Điện Biên,Ttyt Điện Biên Phủ,11002,Ttyt Điện Biên Phủ,40.158,...,None,1,1,2025-10-25 22:21:51,2025-04-22,NaT,2025-04-22,2025-04-22,2027-04-22,IMP
1,3.thau_rieng_le,40.161,Imeclor 125,Cefaclor,60,Tỉnh Bình Thuận,Tyt Đa Mi,60097,Tyt Đa Mi,40.161,...,None,1,5,2025-10-25 22:21:51,2025-04-29,NaT,2025-04-29,2025-04-29,2026-01-29,IMP
2,3.thau_rieng_le,40.162,Imedroxil 500mg,Cefadroxil,94,Tỉnh Sóc Trăng,Tyt Trường Khánh,94132,Tyt Trường Khánh,40.162,...,None,1,4,2025-10-25 22:21:51,2025-05-16,NaT,2025-05-16,2025-05-16,2026-02-15,IMP
3,3.thau_rieng_le,40.169,Imexime 100,Cefixim,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.169,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,IMP
4,3.thau_rieng_le,40.155,"Amoxicillin 250 mg/ 31,25 mg",Amoxicilin + acid clavulanic,01,Thành phố Hà Nội,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,01839,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,40.155,...,None,1,1,2025-10-25 22:21:51,2025-04-22,NaT,2025-04-22,2025-04-22,2026-04-22,IMP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8636,3.thau_rieng_le,40.1057,Vitamin C-OPC 100mg Hương cam,Vitamin C,27,Tỉnh Bắc Ninh,Bv Quân Y 110,27010,Bv Quân Y 110,40.1057,...,None,1,1,2025-10-25 22:21:51,2025-04-10,NaT,2025-04-10,2025-04-10,2025-10-31,OPC
8637,3.thau_rieng_le,40.1057,Vitamin C-OPC 100mg Hương cam,Vitamin C,27,Tỉnh Bắc Ninh,Bv Quân Y 110,27010,Bv Quân Y 110,40.1057,...,None,1,1,2025-10-25 22:21:51,2025-04-10,NaT,2025-04-10,2025-04-10,2025-10-31,OPC
8638,3.thau_rieng_le,40.69,Leolen Forte,Cytidin-5monophosphat disodium + uridin,01,Thành phố Hà Nội,Bvđk Đống Đa,01004,Bvđk Đống Đa,40.69,...,None,1,1,2025-10-25 22:21:51,2025-04-03,NaT,2025-04-03,2025-04-03,2026-04-02,OPC
8639,3.thau_rieng_le,40.619,Nước oxy già 3%,Nước oxy già,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.619,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2026-11-14,OPC
8640,3.thau_rieng_le,40.619,Nước oxy già 3%,Nước oxy già,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.619,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2026-11-14,OPC

In [61]:
# Filter ra một mục tùy chọn
test_data.filter(by='IMP').show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd,ticker
0,3.thau_rieng_le,40.158,"Nerusyn 1,5g",Ampicilin + sulbactam,11,Tỉnh Điện Biên,Ttyt Điện Biên Phủ,11002,Ttyt Điện Biên Phủ,40.158,...,None,1,1,2025-10-25 22:21:51,2025-04-22,NaT,2025-04-22,2025-04-22,2027-04-22,IMP
1,3.thau_rieng_le,40.161,Imeclor 125,Cefaclor,60,Tỉnh Bình Thuận,Tyt Đa Mi,60097,Tyt Đa Mi,40.161,...,None,1,5,2025-10-25 22:21:51,2025-04-29,NaT,2025-04-29,2025-04-29,2026-01-29,IMP
2,3.thau_rieng_le,40.162,Imedroxil 500mg,Cefadroxil,94,Tỉnh Sóc Trăng,Tyt Trường Khánh,94132,Tyt Trường Khánh,40.162,...,None,1,4,2025-10-25 22:21:51,2025-05-16,NaT,2025-05-16,2025-05-16,2026-02-15,IMP
3,3.thau_rieng_le,40.169,Imexime 100,Cefixim,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.169,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,IMP
4,3.thau_rieng_le,40.155,"Amoxicillin 250 mg/ 31,25 mg",Amoxicilin + acid clavulanic,01,Thành phố Hà Nội,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,01839,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,40.155,...,None,1,1,2025-10-25 22:21:51,2025-04-22,NaT,2025-04-22,2025-04-22,2026-04-22,IMP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,3.thau_rieng_le,40.169,Imexime 100,Cefixim,26,Tỉnh Vĩnh Phúc,Ttyt Khu Vực Tam Đảo,26026,Ttyt Khu Vực Tam Đảo,40.169,...,None,1,1,2025-10-25 22:21:51,2025-04-03,NaT,2025-04-03,2025-04-03,2026-04-02,IMP
758,3.thau_rieng_le,40.172,Bacsulfo 1g/1g,Cefoperazon + sulbactam*,01,Thành phố Hà Nội,Bvđk Vân Đình,01817,Bvđk Vân Đình,40.172,...,None,1,1,2025-10-25 22:21:51,2025-04-04,NaT,2025-04-04,2025-04-04,2026-04-04,IMP
759,3.thau_rieng_le,40.155,"Amoxicillin/ Acid clavulanic 250 mg/ 31,25 mg",Amoxicilin + acid clavulanic,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.155,...,None,1,1,2025-10-25 22:21:51,2025-04-04,2026-04-03,2025-04-04,2025-04-04,2027-04-04,IMP
760,3.thau_rieng_le,40.171,"Cefoperazone 0,5g",Cefoperazon*,01,Thành phố Hà Nội,Bvđk Nông Nghiệp,01013,Bvđk Nông Nghiệp,40.171,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2027-05-14,IMP
761,3.thau_rieng_le,40.174,Cefotiam1g,Cefotiam*,01,Thành phố Hà Nội,Bvđk Nông Nghiệp,01013,Bvđk Nông Nghiệp,40.174,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2027-05-14,IMP

In [62]:
# Tính tổng số lượng
print(f'Tổng số lượng của IMP: {test_data.filter(by='IMP').sum(value_col='soluong'):,.0f}') # Cái ':,.0f' là để hiển thị dấu phẩy hàng nghìn
 
# Tính tổng giá trị
print(f'Tổng giá trị của IMP: {test_data.filter(by='IMP').sum(value_col='thanhtien'):,.0f}')

Tổng số lượng của IMP: 25,647,070
Tổng giá trị của IMP: 288,706,927,665

# Test

In [290]:
%load_ext autoreload
%autoreload 2

from config.filter_config import producer_config, country_config, active_ingred_config
from src.utils.data_loader import read_xml, filter_data

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [291]:
# test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls' # đưa PATH đến data ở đây. 
# test_data = read_xml(test_path)

In [292]:
# sorted([str(x) for x in test_data['hoatchat'].unique().tolist() if not None])

In [293]:
matched, unmatched = filter_data(test_data, active_ingred_config, verbose=True, return_unmatched=True)

c:\Users\ducngh\OneDrive - fpts.com.vn\Work\Dược\src\utils\data_loader.py:201: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  exclude_kws = rule.get('exclude_keyword', rule.get('exclude_keywords', []))
c:\Users\ducngh\OneDrive - fpts.com.vn\Work\Dược\src\utils\data_loader.py:203: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  is_regex = rule.get('is_regex', False)

=== BÁO CÁO MATCH DỮ LIỆU ===
Cột gán nhãn:       'active_ingredient'
Tổng số dòng:       41,472
Đã match (gán nhãn): 40,376 (97.36%)
Chưa match:         1,096 (2.64%)

Chi tiết theo 'active_ingredient':
active_ingredient
Acetaminophen                                                      1157
Paracetamol                                                        1121
Amoxicilin + Acid clavulanic                                       1024
Vitamin B1 + B6 + B12                                               872
Dung dịch Natri clorid                                              802
Nhôm hydroxyd + Magnesi hydroxyd + Simethicon                       721
Piracetam                                                           490
Enalapril + Hydroclorothiazid                                       482
Trimetazidin                                                        467
Metformin                                                           465
Ambroxol                                                            459
Salbutamol                                                          443
Bromhexin                                                           420
Cefalexin                                                           411
Nhôm hydroxyd + Magnesi hydroxyd                                    388
Drotaverin                                                          368
Vitamin A + Vitamin D                                               366
Amoxicilin                                                          357
Lactobacillus acidophilus                                           334
Cinnarizin                                                          333
Acetyl leucin                                                       331
Vitamin C                                                           321
Diosmin + Hesperidin                                                311
Tobramycin                                                          310
Aciclovir                                                           309
Bacillus subtilis                                                   303
Gliclazid                                                           299
Glimepirid + Metformin                                              296
Glibenclamid + Metformin                                            294
Glucose                                                             290
Methylprednisolon                                                   288
Nifedipin                                                           287
Omeprazol                                                           287
Sắt + Acid folic                                                    286
Losartan                                                            284
Cefuroxim                                                           267
Esomeprazol                                                         266
Amlodipin                                                           265
Cefradin                                                            264
Bacillus clausii                                                    262
Meloxicam                                                           258
Cefadroxil                                                          253
Dung dịch bù nước và điện giải (Oresol)                             253
Acetylsalicylic acid                                                250
Kẽm                                                                 249
Diclofenac                                                          231
Spiramycin + Metronidazol                                           231
Chlorpheniramin                                                     229
Saccharomyces boulardii                                             228
Telmisartan + Hydroclorothiazid                                     228
Sorbitol                                                            222
Cetirizin                                                           218
Atorvastatin                                                        217
Indapamid + Perindopril                                             212
Paracetamol + Chlorpheniramin                                       212
Dexamethason + Neomycin + Polymyxin B                               205
Captopril + Hydroclorothiazid                                       203
Metronidazol                                                        203
Bisoprolol                                                          202
Diosmectit                                                          202
Ampicilin + Sulbactam                                               200
Neomycin + Nystatin + Polymyxin B                                   199
Domperidon                                                          196
Simethicon                                                          193
Calci lactat + Calci carbonat                                       192
Codein + Terpin hydrat                                              192
Ciprofloxacin                                                       186
Ofloxacin                                                           185
Magnesi lactat + Pyridoxin (Vitamin B6)                             182
Cefaclor                                                            179
Colchicin                                                           176
Dexamethason + Tobramycin                                           174
Gliclazid + Metformin                                               174
Perindopril                                                         171
Rotundin                                                            171
Perindopril + Amlodipin                                             168
Lisinopril + Hydroclorothiazid                                      166
Calci lactat                                                        164
Attapulgit + Magnesi carbonat + Nhôm hydroxyd                       163
Lisinopril                                                          163
Ramipril                                                            162
Alimemazin                                                          159
Alphachymotrypsin                                                   158
Phenobarbital                                                       150
Felodipin                                                           148
Thiamin (Vitamin B1)                                                144
Irbesartan                                                          141
Acid tranexamic                                                     139
Famotidin                                                           139
Candesartan                                                         138
Metronidazol + Neomycin + Nystatin                                  135
Lovastatin                                                          133
Insulin người                                                       132
Chlorpromazin                                                       131
Glimepirid                                                          131
Losartan + Hydroclorothiazid                                        130
Eperison                                                            127
Bisoprolol + Hydroclorothiazid                                      125
Kali clorid                                                         125
Loratadin                                                           122
Fenofibrat                                                          118
Acid valproic / Natri valproat                                      117
Dextromethorphan                                                    115
Nicotinamid (Vitamin PP)                                            115
Thiocolchicosid                                                     114
Levomepromazin                                                      111
Nước cất pha tiêm                                                   111
Paracetamol + Ibuprofen                                             110
Acid salicylic + Betamethason dipropionat                           109
Phytomenadion (Vitamin K1)                                          108
Alverin + Simethicon                                                107
Metoprolol                                                          107
Paracetamol + Codein                                                106
Loxoprofen                                                          105
Povidon iod                                                         103
Trimebutin                                                           99
Allopurinol                                                          97
Dexchlorpheniramin                                                   97
Diosmin                                                              97
Budesonid                                                            96
Valsartan + Hydroclorothiazid                                        94
Pravastatin                                                          93
Telmisartan                                                          93
Pyridoxin (Vitamin B6)                                               92
Sulfamethoxazol + Trimethoprim                                       92
Ibuprofen                                                            91
Candesartan + Hydroclorothiazid                                      90
Cefixim                                                              89
Enalapril                                                            89
Valsartan                                                            89
Diazepam                                                             88
Erythromycin                                                         87
Rosuvastatin                                                         86
Flunarizin                                                           84
Insulin analog                                                       84
Lidocain                                                             84
Levothyroxin                                                         81
Irbesartan + Hydroclorothiazid                                       80
Tinidazol                                                            80
Sucralfat                                                            78
Nhôm phosphat                                                        77
Cloxacilin                                                           77
Ipratropium bromid + Salbutamol                                      77
Clopidogrel                                                          76
Xylometazolin                                                        76
Glucosamin                                                           74
Khoáng chất đa lượng và vi lượng                                     74
Haloperidol                                                          72
Prednisolon                                                          72
Levofloxacin                                                         71
Spiramycin                                                           71
Dimenhydrinat                                                        70
Morphin                                                              69
Dung dịch Ringer lactat                                              68
Cefpodoxim                                                           67
Adrenalin                                                            66
Oxytocin                                                             65
Calci carbonat + Vitamin D3                                          64
Moxifloxacin                                                         64
Clotrimazol                                                          63
Promethazin                                                          63
Vitamin A                                                            63
Vitamin E                                                            63
Acid amin                                                            62
Fluvastatin                                                          62
Fluticason + Salmeterol                                              61
Furosemid                                                            61
Isosorbid                                                            60
Amlodipin + Atorvastatin                                             59
Glyceryl trinitrat                                                   59
Propranolol                                                          59
Chlorpheniramin + Dextromethorphan                                   58
Fexofenadin                                                          58
Amlodipin + Lisinopril                                               57
Glipizid                                                             56
Bisacodyl                                                            55
Cefazolin                                                            55
Cefoperazon                                                          55
Desloratadin                                                         55
Nystatin                                                             55
Metoclopramid                                                        54
Azithromycin                                                         53
Betahistin                                                           53
Cồn                                                                  53
Etoricoxib                                                           53
Nicorandil                                                           53
Captopril                                                            52
Amlodipin + Indapamid                                                50
Clindamycin                                                          50
Trihexyphenidyl                                                      50
Alfuzosin                                                            49
Bupivacain                                                           47
Diphenhydramin                                                       47
Natri hyaluronat                                                     47
Paracetamol + Diphenhydramin                                         47
Spironolacton                                                        47
Cefdinir                                                             46
Fentanyl                                                             46
Fusidic Acid                                                         45
Amlodipin + Valsartan                                                45
Carbocistein                                                         45
Dexpanthenol                                                         45
Dexamethason                                                         44
Dung dịch lọc ngoài thận                                             44
Gentamicin                                                           44
Lansoprazol                                                          44
Noradrenalin                                                         44
Vitamin D3                                                           44
Amitriptylin                                                         42
Ketoprofen                                                           42
Magnesi sulfat                                                       42
Methimazol                                                           42
Papaverin                                                            42
Nebivolol                                                            41
Sevofluran                                                           41
Acetylcystein                                                        40
Cefoperazon + Sulbactam                                              40
Đồng sulfat                                                          40
Budesonid + Formoterol                                               39
Carvedilol                                                           39
Ceftriaxon                                                           39
Glycerol                                                             39
Hyoscin butylbromid                                                  39
Bạc sulfadiazin                                                      39
Ceftizoxim                                                           38
Celecoxib                                                            38
Gabapentin                                                           38
Olanzapin                                                            38
Simvastatin                                                          38
Acid folic (vitamin B9)                                              37
Albumin                                                              37
Amiodaron                                                            37
Griseofulvin                                                         37
Miconazol                                                            37
Propofol                                                             37
Midazolam                                                            36
Rocuronium                                                           36
Bambuterol                                                           35
Berberin                                                             35
Cefoxitin                                                            35
Clotrimazol + Betamethason                                           34
Ivabradin                                                            34
Ketoconazol                                                          34
Lidocain + Adrenalin                                                 34
Digoxin                                                              33
Tetracyclin                                                          33
Vancomycin                                                           33
Acarbose                                                             32
Amikacin                                                             32
Amlodipin + Losartan                                                 32
Erythropoietin                                                       32
Fluconazol                                                           32
Methylergometrin                                                     32
Sitagliptin                                                          32
Acetylsalicylic acid + Clopidogre                                    31
Carbetocin                                                           31
Nicardipin                                                           31
Amlodipin + Indapamid + Perindopril                                  30
Methyldopa                                                           30
Neostigmin                                                           30
Hydro peroxyd                                                        30
Tenofovir                                                            30
Alverin                                                              29
Betamethason                                                         29
Cefamandol                                                           29
Dapagliflozin                                                        29
Enoxaparin                                                           29
Pregabalin                                                           29
Tenoxicam                                                            29
Atorvastatin + Ezetimibe                                             28
Levodopa + Carbidopa                                                 28
Ondansetron                                                          28
Pantoprazol                                                          28
Phenytoin                                                            28

In [294]:
# Hiển thị toàn bộ dữ liệu raw
sorted([str(x) for x in matched['hoatchat'].unique().tolist() if not None])

['Acarbose',
 'Aceclofenac',
 'Acenocoumarol',
 'Acetaminophen',
 'Acetazolamid',
 'Acetyl leucin',
 'Acetyl leucine',
 'Acetylcystein',
 'Acetylcysteine',
 'Acetylsalicylic Acid',
 'Acetylsalicylic acid',
 'Acetylsalicylic acid (DL-lysin-acetylsalicylat)',
 'Acetylsalicylic acid + clopidogrel',
 'Acetylsalicylic acid+ clopidogrel',
 'Aciclovir',
 'Acid Fusidic',
 'Acid amin',
 'Acid amin + glucose + lipid',
 'Acid amin + glucose + lipid (*)',
 'Acid amin + glucose + điện giải',
 'Acid amin + glucose+ điện giải (*)',
 'Acid amin*',
 'Acid folic (vitamin B9)',
 'Acid folinic',
 'Acid gadoteric',
 'Acid salicylic + Betamethason dipropionat',
 'Acid thioctic (Meglumin thioctat)',
 'Acid tranexamic',
 'Acitretin',
 'Acyclovir',
 'Adalimumab',
 'Adenosin triphosphat',
 'Adenosine',
 'Adrenalin',
 'Aescin',
 'Aescinat natri',
 'Albendazol',
 'Albumin',
 'Albumin người',
 'Alendronic acid (dưới dạng Natri alendronat trihydrat)',
 'Alfuzosin',
 'Alfuzosin HCL',
 'Alfuzosin HCl',
 'Alfuzosin hydroclorid',
 'Alimemazin',
 'Alimemazin (dưới dạng Alimemazin tartrat)',
 'Alimemazin tartrat',
 'Allopurinol',
 'Alpha chymotrypsin',
 'Alphachymotrypsin',
 'Alphachymotrypsine (tương đương alphachymotrypsine 21 microkatal)',
 'Alteplase',
 'Aluminum phosphat',
 'Alverin (citrat)',
 'Alverin (citrat) + simethicon',
 'Alverin citrat',
 'Alverin citrat + simethicon',
 'Alverine citrate + Simethicone',
 'Ambroxol',
 'Ambroxol (dưới dạng Ambroxol HCl)',
 'Ambroxol HCL',
 'Ambroxol HCl',
 'Ambroxol hydrochlorid',
 'Ambroxol hydroclorid',
 'Amikacin',
 'Amikacin ( dưới dạng Amikacin sulfat)',
 'Amikacin (dưới dạng Amikacin sulfate 667,5mg)',
 'Amikacin (dưới dạng Amikacin sulphat)',
 'Amikacin*',
 'Aminophylin',
 'Amiodaron (hydroclorid)',
 'Amiodaron hydroclorid',
 'Amiodarone hydrochloride',
 'Amisulprid',
 'Amitriptylin (hydroclorid)',
 'Amitriptylin hydroclorid',
 'Amlodipin',
 'Amlodipin (dưới dạng Amlodipin besilat)',
 'Amlodipin (dưới dạng Amlodipin besilat) 5mg + Atorvastatin (dưới dạng Atorvastatin calci trihydrat) 10mg',
 'Amlodipin (dưới dạng Amlodipin besylat)',
 'Amlodipin (dưới dạng Amlodipin besylat) + Valsartan',
 'Amlodipin (dưới dạng Amlodipin besylate) 5mg',
 'Amlodipin (dưới dạng amlodipin besilat) + valsartan',
 'Amlodipin + Atorvastatin',
 'Amlodipin + Valsartan',
 'Amlodipin + atorvastatin',
 'Amlodipin + indapamid',
 'Amlodipin + indapamid + perindopril',
 'Amlodipin + lisinopril',
 'Amlodipin + losartan',
 'Amlodipin + telmisartan',
 'Amlodipin + valsartan',
 'Amlodipin + valsartan + hydrochlorothiazid',
 'Amlodipin+ atorvastatin',
 'Amlodipin+ lisinopril',
 'Amlodipin+ losartan',
 'Amlodipine (dưới dạng Amlodipine besilate ) + Losartan kali',
 'Amlodipine (dưới dạng Amlodipine besilate) + Lisinopril (dưới dạng Lisinopril dihydrat)',
 'Amlodipine (dưới dạng Amlodipine besilate) + Losartan kali',
 'Amlodipine +  Indapamide + Perindopril arginine',
 'Amlodipine + Indapamide',
 'Amlodipine + Lisinopril',
 'Amlodipine + Valsartan',
 'Amlodipine+ indapamide',
 'Amoxicilin',
 'Amoxicilin\nAcid clavulanic',
 'Amoxicilin \n+ Acid clavulanic',
 'Amoxicilin  + Acid clavulanic',
 'Amoxicilin (Dưới dạng Amoxillin trihydrate)+\xa0acid\xa0clavulanic (Dưới dạng Kali clavulanat)',
 'Amoxicilin (dùng dạng amoxicilin trihydrat)\n+ Acid clavulanic (dùng\ndạng kali clavulanat; avicel (1 :1))',
 'Amoxicilin (dưói dang Amoxicilin trihydrat)',
 'Amoxicilin (dưói dạng Amoxicilin trihydrat)',
 'Amoxicilin (dưới dạng Amoxicilin trihydrat compacted)',
 'Amoxicilin (dưới dạng Amoxicilin trihydrat compacted) + Acid Clavulanic (dưới dạng Kali Clavulanat - Avicel (1:1))',
 'Amoxicilin (dưới dạng Amoxicilin trihydrat)',
 'Amoxicilin (dưới dạng Amoxicillin trihydrat)',
 'Amoxicilin (dưới dạng amoxicilin natri)+ Acid clavulanic (dưới dạng Kali clavulanat)',
 'Amoxicilin (dưới dạng amoxicilin trihydrat comacted) 500mg',
 'Amoxicilin (dưới dạng amoxicilin trihydrat)\n+ Acid clavulanic (dưới\ndạng kali clavulanat; avicel (1 :1))',
 'Amoxicilin + Acid clavulanic',
 'Amoxicilin + acid clavulanic',
 'Amoxicilin + sulbactam',
 'Amoxicillin',
 'Amoxicillin (dưới dạng Amoxicillin trihydrat compacted 500mg)',
 'Amoxicillin (dưới dạng Amoxicillin trihydrat compacted)',
 'Amoxicillin (dưới dạng Amoxicillin trihydrat compacted) 500mg',
 'Amoxicillin (dưới dạng Amoxicillin trihydrat)',
 'Amoxicillin (dưới dạng Amoxicillin trihydrate) 500mg',
 'Ampicilin (dưới dạng Ampicilin natri)',
 'Ampicilin (dưới dạng Ampicilin natri) + Sulbactam (dưới dạng Sulbactam natri)',
 'Ampicilin (muối natri)',
 'Ampicilin + Sulbactam',
 'Ampicilin + sulbactam',
 'Ampicillin (dưới dạng Ampicillin natri) + Sulbactam (dưới dạng Sulbactam natri)',
 'Amylase + lipase + protease',
 'Anastrozol',
 'Apixaban',
 'Atenolol',
 'Atorvastatin',
 'Atorvastatin (dưới dạng Atorvastatin calci trihydrat)',
 'Atorvastatin (dưới dạng Atorvastatin calci)',
 'Atorvastatin (dưới dạng Atorvastatin calci) 20mg + Ezetimibe 10mg',
 'Atorvastatin (dưới dạng Atorvastatin calcium trihydrate) + Ezetimibe',
 'Atorvastatin (dưới dạng Atorvastatin calcium)',
 'Atorvastatin + ezetimibe',
 'Atosiban',
 'Atracurium besylat',
 'Atropin (sulfat)',
 'Atropin sulfat',
 'Attapulgit hoạt tính + Magnesi carbonat + Nhôm hydroxyd',
 'Attapulgit mormoiron hoạt hoá + Hỗn hợp gel khô magnesi carbonat và nhôm hydroxyd',
 'Attapulgit mormoiron hoạt hóa',
 'Attapulgit mormoiron hoạt hóa + hỗn hợp magnesi carbonat-nhôm hydroxyd',
 'Azithromycin',
 'Bacillus clausii',
 'Bacillus claussii',
 'Bacillus subtilis',
 'Baclofen',
 'Bambuterol',
 'Bambuterol hydrochloride',
 'Beclometason (dipropionat)',
 'Benazepril hydroclorid',
 'Benzylpenicilin',
 'Berberin (hydroclorid)',
 'Berberin clorid',
 'Betahistin',
 'Betahistin dihydrochlorid',
 'Betahistin dihydroclorid',
 'Betahistin.2HCl',
 'Betahistine\ndihydrochloride\n24mg',
 'Betahistine dihydrochloride',
 'Betahistine.2HCL',
 'Betamethason',
 'Betamethason dipropionat',
 'Betamethason dipropionat + clotrimazol + gentamicin',
 'Betamethason dipropionat 19,2mg',
 'Betamethasone (Betamethasone dipropionate), Betamethasone (dưới dạng Betamethasone disodium phosphate)',
 'Betamethasone + dexchlorpheniramin',
 'Bevacizumab',
 'Bezafibrat',
 'Bicalutamid',
 'Bilastine',
 'Bimatoprost',
 'Bisacodyl',
 'Bismuth',
 'Bismuth subsalicylat',
 'Bismuth subsalicylate',
 'Bismuth trioxid (dưới dạng bismuth subcitrat dạng keo)',
 'Bismuth tripotassium dicitrate (tương đương Bismuth trioxid 120mg)',
 'Bisoprolol',
 'Bisoprolol + hydroclorothiazid',
 'Bisoprolol Fumarat',
 'Bisoprolol fumarat',
 'Bisoprolol fumarat + Hydrochlorothiazid',
 'Bisoprolol fumarat + hydroclorothiazid',
 'Bisoprolol fumarate',
 'Bleomycin',
 'Botulinum toxin',
 'Brimonidin tartrat',
 'Brimonidin tartrat + timolol',
 'Brimonidine tartrate + Timolol',
 'Brinzolamid',
 'Brinzolamid + timolol',
 'Brinzolamide',
 'Bromfenac',
 'Bromhexin \nhydroclorid',
 'Bromhexin (hydroclorid)',
 'Bromhexin hydrochlorid',
 'Bromhexin hydroclorid',
 'Budesonid',
 'Budesonid + Formoterol fumarate dihydrate',
 'Budesonid + formoterol',
 'Budesonid +Formoterol fumarate dihydrate',
 'Budesonide',
 'Bupivacain hydroclorid',
 'Bupivacaine hydrochloride',
 'Bột dập thẳng Codried (chứa Nhôm hydroxyd 306mg tương đương với Nhôm oxyd 200mg + magnesi hydroxyd 400 mg) + Bột simethicon 70% (tương đương với simethicon 30mg)',
 'Cafein (citrat)',
 'Cafein citrat',
 'Calci carbonat',
 'Calci carbonat (tương ứng với 300 mg calci) + Vitamin D3',
 'Calci carbonat + Calci lactat gluconat',
 'Calci carbonat + calci gluconolactat',
 'Calci carbonat + vitamin D3',
 'Calci carbonat+ calci gluconolactat',
 'Calci clorid.2H20 0,135g; Kali clorid 0,2g; Natri clorid 3g; Natri lactat 1,6g',
 'Calci folinat',
 'Calci gluconat',
 'Calci glycerophosphat + Magnesi gluconat',
 'Calci glycerophosphat + magnesi gluconat',
 'Calci glycerophosphat+ magnesi gluconat',
 'Calci lactat',
 'Calci lactat (dưới dạng Calci lactat pentahydrat) 300 mg',
 'Calci lactat pentahydrat',
 'Calcipotriol',
 'Calcipotriol + betamethason dipropionat',
 'Calcitonin',
 'Calcitriol',
 'Calcium chloride dihydrate',
 'Calcium lactate pentahydrate',
 'Candesartan',
 'Candesartan + Hydroclorothiazid',
 'Candesartan + hydrochlorothiazid',
 'Candesartan Cilexetil',
 'Candesartan Cilexetil + Hydrochlorothiazid',
 'Candesartan Cilexetil; Hydrochlorothiazid',
 'Candesartan cilexetil',
 'Candesartan cilexetil + Hydrochlorothiazide',
 'Candesartan cilexetil + Hydroclorothiazid',
 'Cao ginkgo biloba',
 'Cao ginkgo biloba (Dưới dạng ginkgo biloba phytosome)',
 'Cao ginkgo biloba + heptaminol clohydrat + troxerutin',
 'Cao ginkgo biloba+ heptaminol clohydrat+ troxerutin',
 'Cao khô lá bạch quả đã chuẩn hóa [Ginkgonis extractum siccum raffinatum et quantificatum] (39,6 - 49,5:1)',
 'Capsaicin',
 'Captopril',
 'Captopril + Hydroclorothiazid',
 'Captopril + hydroclorothiazid',
 'Captopril+ hydroclorothiazid',
 'Carbamazepin',
 'Carbazochrom',
 'Carbazochrom natri sulfonat',
 'Carbetocin',
 'Carbimazol',
 'Carbocistein',
 'Carbocistein + promethazin',
 'Carbomer',
 'Carboplatin',
 'Carboprost tromethamin',
 'Carvedilol',
 'Caspofungin*',
 'Cefaclor',
 'Cefaclor (dưới dạng Cefaclor monohydrat)',
 'Cefaclor (dưới dạng Cefaclor monohydrate)',
 'Cefaclor (dưới dạng cefaclor monohydrat)',
 'Cefadroxil',
 'Cefadroxil\n(dưới dạng Cefadroxil monohydrat)',
 'Cefadroxil (dưới dạng Cefadroxil monohydrat)',
 'Cefalexin',
 'Cefalothin',
 'Cefamandol',
 'Cefazolin',
 'Cefazolin (dưới dạng Cefazolin natri)',
 'Cefazolin (dưới dạng cefazolin natri)',
 'Cefdinir',
 'Cefepim',
 'Cefepim (dưới dạng Cefepim hydroclorid phối hợp với L-arginin tỷ lệ 1:0,725)',
 'Cefixim',
 'Cefixim (dưới dạng cefixim trihydrat)',
 'Cefixime (dưới dạng cefixime trihydrate)',
 'Cefmetazol',
 'Cefmetazol (dưới dạng Cefmetazol natri)',
 'Cefoperazon',
 'Cefoperazon (dưới dạng Cefoperazon natri)',
 'Cefoperazon (dưới dạng cefoperazon natri)',
 'Cefoperazon (dưới dạng hỗn hợp bột vô khuẩn cefoperazon natri và sulbactam natri tỷ lệ (2:1)) 1g + Sulbactam (dưới dạng hỗn hợp bột vô khuẩn cefoperazon natri và sulbactam natri tỷ lệ (2:1)) 0,5g',
 'Cefoperazon + Sulbactam',
 'Cefoperazon + sulbactam',
 'Cefoperazon + sulbactam*',
 'Cefoperazon*',
 'Cefoperazone sodium và sulbactam sodium vô trùng tương đương cefoperazone và sulbactam 1g : 1g',
 'Cefotaxim',
 'Cefotaxim (dưới dạng cefotaxim natri)',
 'Cefotaxim (dưới dạng cefotaxim sodium)',
 'Cefotaxime (dưới dạng Cefotaxim natri)',
 'Cefotiam',
 'Cefotiam*',
 'Cefoxitin',
 'Cefoxitin (dưới dạng Cefoxitin natri)',
 'Cefoxitin (dưới dạng cefoxitin natri)',
 'Cefpirom',
 'Cefpodoxim',
 'Cefpodoxim (dưới dạng Cefpodoxim proxetil)',
 'Cefpodoxim proxetil',
 'Cefradin',
 'Ceftazidim',
 'Ceftizoxim',
 'Ceftriaxon',
 'Ceftriaxon (dưới dạng Ceftriaxon natri)',
 'Ceftriaxon*',
 'Ceftriaxone (dưới dạng Ceftriaxone natri)',
 'Ceftriaxone (dưới dạng Ceftriaxone sodium)',
 'Ceftriaxone (dưới dạng ceftriaxone sodium)',
 'Cefuroxim',
 'Cefuroxim\n(dưới dạng Cefuroxim axetil)',
 'Cefuroxim (dưới\ndạng Cefuroxim\naxetil)',
 'Cefuroxim (dưới dạng Cefuroxim axetil)',
 'Cefuroxim (dưới dạng cefuroxim axetil)',
 'Cefuroxim (dưới dạng cefuroxim natri)',
 'Celecoxib',
 'Cetirizin',
 'Cetirizin dihydroclorid',
 'Cetirizine hydrochloride',
 'Chai 10g chứa: Glyceryl trinitrate (dưới dạng dung dịch 1% trong cồn)',
 'Chlorpheniramin',
 'Chlorpheniramin (hydrogen maleat)',
 'Chlorpheniramin + dextromethorphan',
 'Chlorpheniramine maleat',
 'Chlorpromazine hydrochloride',
 'Choline Alfoscerate',
 'Choline alfoscerat',
 'Chymotrypsin',
 'Ciclopiroxolamin',
 'Ciclosporin',
 'Cilnidipin',
 'Cilostazol',
 'Cimetidin',
 'Cimetidine',
 'Cinnarizin',
 'Cinnarizine',
 'Ciprofibrat',
 'Ciprofloxacin',
 'Ciprofloxacin \n(dùng dạng ciprofloxacin\nhydroclorid)',
 'Ciprofloxacin (dưới dạng Ciprofloxacin hydrochlorid)',
 'Ciprofloxacin (dưới dạng Ciprofloxacin hydrochloride)',
 'Ciprofloxacin (dưới dạng ciprofloxacin HCl)',
 'Ciprofloxacin (dưới dạng ciprofloxacin hydroclorid monohydrat)',
 'Cisplatin',
 'Citalopram',
 'Citicolin',
 'Citicolin (dưới dạng Citicolin natri)',
 'Clarithromycin',
 'Clindamycin',
 'Clindamycin (dưới dạng Clindamycin HCl)',
 'Clindamycin (dưới dạng clindamycin hydrochlorid)',
 'Clindamycin (dưới dạng clindamycin phosphat)',
 'Clobetasol propionat',
 'Clobetasol propionat micronised 0,05 % (w/w)',
 'Clopidogrel',
 'Clopidogrel (dưới dạng Clopidogrel bisulfat)',
 'Clorpheniramin maleat',
 'Clorpromazin',
 'Clorpromazin (hydroclorid)',
 'Clorpromazin hydroclorid',
 'Clotrimazol',
 'Clotrimazol + betamethason',
 'Clotrimazole',
 'Cloxacilin',
 'Cloxacilin (dưới dạng Cloxacilin natri)',
 'Clozapin',
 'Clozapine',
 'Codein + terpin hydrat',
 'Codein camphosulphonat+ sulfoguaiacol + cao mềm Grindelia',
 'Codein phosphat (dưới dạng Codein phosphat hemihydrat) 10mg ; Terpin hydrat 100mg',
 'Codein phosphat + Terpin hydrat',
 'Colchicin',
 'Colchicine',
 'Colistimethat natri',
 'Colistin',
 'Colistin*',
 'Crotamiton',
 'Cyanocobalamin',
 'Cyclophosphamid',
 'Cyclophosphamide',
 'Cyclosporin',
 'Cytidin monophosphat disodium + Uridin monophasphat disodium',
 'Cytidin-5monophosphat disodium + Uridin monophosphat disodium',
 'Cytidin-5monophosphat disodium + uridin',
 'Cồn 70°',
 'Cồn A.S.A',
 'Cồn BSI',
 'Cồn boric',
 'D-Mannitol',
 'Dabigatran',
 'Dapagliflozin',
 'Dapagliflozin (dưới dạng Dapagliflozin propanediol monohydrat)',
 'Dapagliflozin (dưới dạng dapagliflozin propanediol monohydrat)',
 'Daptomycin*',
 'Deferasirox',
 'Deferipron',
 'Deferoxamin',
 'Dequalinium clorid',
 'Desflurane',
 'Desloratadin',
 'Desmopressin',
 'Desmopressin acetat',
 'Dexamethason',
 'Dexamethason (dưới dạng Dexamethason Natri phosphat) 2mg',
 'Dexamethason (dưới dạng dexamethason natri phosphat) + Neomycin (dưới dạng neomycin sulfat) + Polymyxin B sulfat',
 'Dexamethason + Neomycin + Polymyxin B sulfat',
 'Dexamethason phosphat',
 'Dexamethason phosphat (dưới dạng Dexamethason natri phosphat)',
 'Dexchlorpheniramin',
 'Dexclorpheniramin maleat',
 'Dexibuprofen',
 'Dexpanthenol',
 'Dexpanthenol (panthenol, vitamin B5)',
 'Dextran 40',
 'Dextromethorphan',
 'Dextromethorphan hydrobromid',
 'Dextromethorphan hydrobromid 15mg',
 'Diacerein',
 'Diazepam',
 'Dibencozid',
 'Diclofenac',
 'Diclofenac Natri',
 'Diclofenac natri',
 'Diethylphtalat',
 'Digoxin',
 'Dihydro ergotamin mesylat',
 'Diltiazem',
 'Diltiazem hydroclorid',
 'Dimenhydrinat',
 'Dimenhydrinate',
 'Dinoproston',
 'Dioctahedral smectit',
 'Diosmectit',
 'Diosmectite',
 'Diosmin',
 'Diosmin + Hesperidin',
 'Diosmin + hesperidin',
 'Diphenhydramin',
 'Diphenhydramin HCl',
 'Diphenhydramin hydroclorid',
 'Dobutamin',
 'Dobutamine (dưới dạng Dobutamine hydrochloride)',
 'Docetaxel',
 'Docusate natri',
 'Docusate sodium',
 'Dolutegravir (tương đương Dolutegravir natri 52,6mg) 50mg; Lamivudine 300mg; Tenofovir disoproxil fumarate (tương đương Tenofovir disoproxil 245mg) 300mg',
 'Domperidon',
 'Domperidon (dưới dạng Domperidon maleat)',
 'Domperidon (dưới dạng Domperidone maleate)',
 'Domperidone',
 'Donepezil',
 'Dopamin hydroclorid',
 'Doripenem',
 'Doripenem (dưới dạng Doripenem monohyrat)',
 'Doripenem*',
 'Doxazosin',
 'Doxazosin (dưới dạng Doxazosin mesylat)',
 'Doxorubicin',
 'Doxorubicin Hydroclorid',
 'Doxorubicin hydroclorid',
 'Doxycyclin',
 'Doxycyclin (dưới dạng Doxycyclin hyclat)',
 'Drotaverin',
 'Drotaverin HCl',
 'Drotaverin clohydrat',
 'Drotaverin hydroclorid',
 'Drotaverine hydrochloride',
 'Dung dịch lọc màng bụng',
 'Dung dịch lọc máu dùng trong thận nhân tạo (bicarbonat hoặc acetat)',
 'Dung dịch lọc máu liên tục',
 'Dung dịch lọc máu liên tục (có hoặc không có chống đông bằng citrat; có hoặc không có chứa lactat)',
 'Dung dịch lọc thận bicarbonathoặc acetat',
 'Dutasterid',
 'Dutasteride',
 'Dydrogesteron',
 'Dydrogesterone',
 'Ebastin',
 'Econazol natri',
 'Empagliflozin',
 'Enalapril',
 'Enalapril  maleat + hydrochlorothiazid',
 'Enalapril + Hydrochlorothiazid',
 'Enalapril + hydrochlorothiazid',
 'Enalapril maleat',
 'Enalapril maleat + Hydrochlorothiazid',
 'Enalapril maleat + hydrochlorothiazid',
 'Enalapril maleate',
 'Enalapril maleate + Hydrochlorothiazide',
 'Enalapril maleate + Hydroclorothiazid',
 'Enoxaparin (natri)',
 'Enoxaparin natri',
 'Entecavir',
 'Entecavir (dưới dạng Entecavir monohydrat)',
 'Entecavir (dưới dạng Entecavir monohydrate)',
 'Eperison',
 'Eperison hydrochlorid',
 'Eperison hydroclorid',
 'Ephedrin',
 'Ephedrin (hydroclorid)',
 'Ephedrin hydroclorid',
 'Epinephrin',
 'Epinephrin (adrenalin)',
 'Eprazinon',
 'Erlotinib',
 'Ertapenem*',
 'Erythromycin',
 'Erythromycin (dưới dạng Erythromycin stearat)',
 'Erythropoietin',
 'Esomeprazol',
 'Esomeprazol (dưới dạng Esomeprazol (magnesi dihydrat) vi hạt 22%)',
 'Esomeprazol (dưới dạng Esomeprazole magnesium pellets (dưới dạng esomeprazole magnesium trihydrtae) 22,5%)',
 'Esomeprazol (dạng vi hạt bao tan trong ruột chứa Esomeprazole magnesium (dưới dạng Esomeprazole magnesium trihydrate) 22,5%)',
 'Esomeprazole (dưới dạng Esomeprazole magnesium pellets (dưới dạng esomeprazole magnesium trihydrate) 22,5%',
 'Esomeprazole (dưới dạng esomeprazole (magnesium dihydrate) pellets 22%)',
 'Estradiol valerate',
 'Etamsylat',
 'Ethyl ester của acid béo iod hóa trong dầu hạt thuốc phiện',
 'Etifoxin chlohydrat',
 'Etifoxin hydrochlorid',
 'Etodolac',
 'Etomidat',
 'Etoposid',
 'Etoricoxib',
 'Ezetimibe',
 'Ezetimibe + Simvastatin',
 'Ezetimibe 10 mg + Simvastatin 10 mg',
 'Famotidin',
 'Famotidine',
 'Felodipin',
 'Fenofibrat',
 'Fenofibrate',
 'Fenoterol + ipratropium',
 'Fenspirid',
 'Fentanyl',
 'Fentanyl (dưới dạng fentanyl citrat)',
 'Fentanyl (dưới dạng fentanyl citrat) 0,05mg/ml',
 'Fenticonazol nitrat',
 'Ferrous Sulfate + Acid folic',
 'Fexofenadin',
 'Fexofenadin HCL',
 'Fexofenadin hydroclorid',
 'Filgrastim',
 'Flavoxat',
 'Fluconazol',
 'Fluconazole',
 'Flunarizin',
 'Flunarizin (dưới dạng Flunarizin dihydrochlorid)',
 'Flunarizine',
 'Fluocinolon acetonid',
 'Fluorometholon',
 'Fluorometholon acetat',
 'Fluorouracil (5-FU)',
 'Fluoxetin',
 'Flurbiprofen',
 'Fluticason propionat',
 'Fluticasone Propionate',
 'Fluticasone furoate',
 'Fluticasone propionate; Salmeterol Xinafoate',
 'Fluvastatin',
 'Fluvastatin (dưới dạng fluvastatin natri)',
 'Fluvoxamin',
 'Folic acid',
 'Fosfomycin',
 'Fosfomycin (natri)',
 'Fosfomycin natri',
 'Fosfomycin*',
 'Fructose 1,6 diphosphat',
 'Furosemid',
 'Furosemid + spironolacton',
 'Furosemide',
 'Fusidic acid',
 'Fusidic acid + Betamethason',
 'Fusidic acid + betamethason',
 'Fusidic acid + hydrocortison',
 'Fusidic acid 2% (w/w) + Betamethasone',
 'Gabapentin',
 'Gadobenic acid',
 'Gadobutrol',
 'Gadoteric acid',
 'Galantamin',
 'Gefitinib',
 'Gelatin succinyl + natri clorid +natri hydroxyd',
 'Gemcitabin',
 'Gemfibrozil',
 'Gentamicin',
 'Gentamicin (dưới dạng gentamicin sulfat)',
 'Ginkgo biloba',
 'Glibenclamid + Metformin hydroclorid',
 'Glibenclamid + metformin',
 'Glibenclamide + Metformin hydrochloride',
 'Gliclazid',
 'Gliclazid + metformin',
 'Gliclazide',
 'Gliclazide + Metformin hydrochloride',
 'Gliclazide 30mg',
 'Glimepirid',
 'Glimepirid + Metformin hydroclorid',
 'Glimepirid + metformin',
 'Glimepirid+Metformin',
 'Glimepiride',
 'Glimepiride + Metformin Hydrochloride',
 'Glimepiride + Metformin hydrochloride',
 'Glipizid',
 'Glucosamin',
 'Glucosamin (dưới dạng Glucosamin hydroclorid)',
 'Glucosamin (dưới dạng glucosamin sulfat kali clorid)',
 'Glucosamin hydroclorid',
 'Glucosamin sulfat',
 'Glucosamin sulfat (dưới dạng D- Glucosamin sulfat.2KCl tương đương Glucosamin base 392,6mg)',
 'Glucosamin sulfat (dưới dạng D-Glucosamin sulfat 2 KCl tương đương Glucosamin base 392,6mg)',
 'Glucosamin sulfat (dưới dạng glucosamin sulfat kali clorid tương đương 392,6mg glucosamin base)',
 'Glucosamin sulfat hoặc Glucosamin hydroclorid',
 'Glucosamine Sulfate',
 'Glucose',
 'Glucose (dưới dạng Glucose monohydrat)',
 'Glucose khan',
 'Glucose khan (dưới dạng Glucose monohydrat)',

In [295]:
sorted([str(x) for x in unmatched['hoatchat'].unique().tolist() if not None])

['100ml nhũ tương chứa: Dầu đậu nành tinh chế 6 gam + Triglycerid mạch trung bình 6 gam + Dầu ô-liu tinh chế 5 gam + Dầu cá tinh chế 3 gam',
 'Acetylleucin (N-Acetyl-DL-Leucin)',
 'Acid Ascorbic',
 'Acid acetylsalicylic',
 'Acid amin + chất điện giải',
 'Acid amin + glucose + lipid + điện giải',
 'Acid amin + glucose + lipid + điện giải (*)',
 'Acid amin + điện giải',
 'Acid amin + điện giải (*)',
 'Acid ascorbic',
 'Acid ascorbic 500 mg',
 'Alanine + Arginine + Aspartic acid + Glutamic acid + Glycine + Histidine + Isoleucine + Leucine + Lysine (dưới dạng Lysine acetate) + Methionine + Phenylalanine + Proline + Serine + Threonine + Tryptophan + Tyrosine + Valine + Natri acetat trihydrat + Natri glycerophosphate hydrat + Kali clorid + Magnesi clorid hexahydrat + Calci clorid dihydrat + Glucose anhydrous + Dầu oliu tinh khiết và dầu đậu nành tinh khiết',
 'Aspirin',
 'Aspirin (Acetylsalicylic acid)',
 'Calci 250mg dưới dạng (Calci lactat gluconat + calci carbonat)',
 'Calci clorid',
 'Calci clorid dihydrat',
 'Cephalexin',
 'Cephalexin (dưới \ndạng Cephalexin \nmonohydrat \ncompacted)',
 'Cephalexin (dưới dạng Cephalexin monohydrat)',
 'Codein camphosulfonat + Sulfogaiacol + Cao mềm Grindelia',
 'Dầu đậu nành tinh chế; triglycerid mạch trung bình; dầu oliu tinh chế; dầu cá tinh chế',
 'Dầu đậu nành; Glycerol; Phospholipid từ trứng',
 'Glucose khan (dưới dạng glucose monohydrate) + Natri clorid + Kali clorid + Trinatri citrat khan (dưới dạng Trinatri citrat. 2H2O)',
 'Glucose khan + Natri clorid + Kali clorid + Tri Natricitrat dihydrat',
 'Irbersatan + hydroclorthiazid',
 'Isosorbid-5-mononitrat',
 'Khoang A: Mỗi 1000ml chứa Calcium clorid dihydrat 5,145g + Magnesium clorid hexahydrat 2,033g + Acid lactic 5,4g; Khoang B: Mỗi 1000ml chứa Sodium Chlorid 6,45g + Sodium hydrogen carbonat 3,09g; Dung dịch sau khi phối hợp chứa: Calcium 1,75mmol/l + Magnesium 0,5mmol/l + Sodium 140mmol/l + Chlorid 109,5mmol/l + Lactat 3mmol/l + hydrogen carbonat 32mmol/l',
 'L-Alanin 1,575g + L-Arginin 1,225g + Amino-acetic acid (Glycin) 0,80g + L-Histidin 1,075g + L-Isoleucin 1,275g + L-Leucin 2,575g + L-Lysin monoacetat 2,5025g (tương đương 1,775g L-Lysin) + L-Methionin 0,70g + L-Phenylalanin 0,95g + L-Prolin 1,075g + L-Serin 1,125g + L-Threonin 1,20g + L-Tryptophan 0,475g + L-Valin 1,55g + Acetylcystein 0,125g (tương đương 0,0925g L-Cystein) + L-Malic acid 0,375g + Acid acetic 99% (acid acetic băng) 0,345g',
 'Magnesi hydroxyd (dưới dạng Magnesi hydroxyd 30% past) + nhôm oxyd (dưới dạng Nhôm Hydroxyd gel)',
 'Manitol',
 'Meclofenoxate hydroclorid',
 'Mỗi 250ml nhũ tương chứa: Dầu đậu nành tinh chế 25g + Glycerol 6,25g + Phospholipid tinh chế từ trứng 1,5g',
 'Mỗi 500ml chứa: Natri clorid 3g + Kali clorid 0,2g + Natri lactat 1,6g + Calci clorid.2H20 0,135g',
 'Mỗi 500ml chứa: Natri clorid 3g; Kali clorid 0,2g; Natri lactat 1,6g; Calci clorid.2H20 0,135g',
 'Mỗi gói 3g chứa: Acetylcystein 200mg',
 'N - Acetylcystein',
 'N-Acetyl DL-Leucin',
 'N-Acetyl-DL-Leucin',
 'N-Acetylcystein',
 'N-acetyl-dl- leucin',
 'N-acetylcystein',
 'Natri clorid + Kali clorid + Natri lactat + Calci clorid.2H2O',
 'Natri clorid + Natri citrat dihydrat + Kali clorid + Glucose khan',
 'Natri clorid + natri citrat + kali clorid + glucose khan',
 'Natri clorid ;  Natri lactat; Kali clorid ; Calci clorid dihydrat',
 'Natri clorid, Kali clorid, Natri lactat, Calci clorid.2H2O',
 'Nhũ dịch lipid',
 'Nhũ dịch lipid (Dầu đậu nành; Lecithin trứng; Glycerol)',
 'Nor- adrenalin',
 'Sắt sulfat + folic acid',
 'Tropicamid + Phenylephrin hydroclorid',
 'Vitamin A (Retinol palmitat) + Vitamin D3 (cholecalciferol)',
 'Vitamin B1 (Thiamin mononitrat) + Vitamin B12 (Cyanocobalamin) + Vitamin B6 (Pyridoxin hydroclorid)',
 'Vitamin B12',
 'Vitamin B12 (cyanocobalamin, hydroxocobalamin)',
 'Vitamin B12(Cyanocobalamin, Hydroxocobalamin)',
 'Vitamin B6 + magnesi (lactat)',
 'Vitamin D3 (cholecalciferol)']