In [1]:
'''
Chỉnh working directory, k cần quan tâm lắm :))
'''

import sys
from pathlib import Path
# Add the project root directory (one level up from tests/)
sys.path.append(str(Path.cwd().parent))
import pandas as pd
import os

In [48]:
'''
Load các thư viện, function cần thiết.
    producer_config: cài đặt filter do chuyên viên nhập và điều chỉnh
    LoadMedicalData: class sử dụng để load, xử lý và tính toán
'''
%load_ext autoreload
%autoreload 2

from config.filter_config import producer_config, country_config, active_ingred_config
from src.utils.data_loader import LoadMedicalData

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [49]:
'''
Đoạn này thử đưa một đoạn dữ liệu vào để load. Sau khi chạy xong thì dữ liệu raw sẽ được lưu trong 'test_data'. Người dùng có thể thực hiện filter hoặc tính tổng từ đây.
'''

test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls' # đưa PATH đến data ở đây. 
test_data = LoadMedicalData(
    test_path, 
    # config=producer_config # có thể thay đổi các config để tùy chỉnh bộ lọc
    config=active_ingred_config
    # config=country_config
)

In [61]:
# Hiển thị toàn bộ dữ liệu raw
test_data.show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,loai,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd
0,3.thau_rieng_le,40.162,SM.Cefadroxil 500,Cefadroxil,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.162,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-11,NaT,2025-04-11,2025-04-11,2025-07-10
1,3.thau_rieng_le,40.883,"Natri Clorid 0,9%",Natri clorid,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-11,NaT,2025-04-11,2025-04-11,2025-07-10
2,3.thau_rieng_le,40.883,"Natri Clorid 0,9%",Natri clorid,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-11,NaT,2025-04-11,2025-04-11,2025-07-10
3,3.thau_rieng_le,40.512,SaVi Losartan 50,Losartan Kali,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.512,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-11,NaT,2025-04-11,2025-04-11,2025-07-10
4,3.thau_rieng_le,40.883,"Natri Clorid 0,9%",Natri clorid,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-11,NaT,2025-04-11,2025-04-11,2025-07-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41467,3.thau_rieng_le,40.219,Azicine 250mg,Azithromycin,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.219,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-04,2026-04-03,2025-04-04,2025-04-04,2027-04-04
41468,3.thau_rieng_le,40.521,Amlessa 4mg/10mg Tablets,Perindopril + amlodipin,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.521,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-04,2026-04-03,2025-04-04,2025-04-04,2027-04-04
41469,3.thau_rieng_le,40.609,Fucidin H,Fusidic acid + hydrocortison,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.609,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-04,2026-04-03,2025-04-04,2025-04-04,2027-04-04
41470,3.thau_rieng_le,40.609,Fucidin H,Fusidic acid + hydrocortison,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.609,...,Tân dược,None,1,1,2025-10-25 22:21:51,2025-04-04,2026-04-03,2025-04-04,2025-04-04,2027-04-04
41471,3.thau_rieng_le,笂Ѐ騖ʹ,Tobradex,Tobramycin + dexamethason,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.207,...,NaN,None,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT

In [62]:
# Filter dữ liệu tùy theo config đưa vào
test_data.filter().show_data() # Nếu để trống phần filter sẽ trả về toàn bộ các mục mà được liệt kê trong config

c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:210: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = clean_series.str.contains(include_pat, na=False)
c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:212: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = cond & (~clean_series.str.contains(exclude_pat, na=False))

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd,active_ingredient
0,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,NaT,NaT,Acarbose
1,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,Acarbose
2,3.thau_rieng_le,40.798,Savi Acarbose 25,Acarbose,10,Tỉnh Lào Cai,Bvđk Khu Vực Văn Bàn-Lào Cai,10008,Bvđk Khu Vực Văn Bàn-Lào Cai,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-16,2027-05-16,2025-05-16,2025-05-16,2027-05-16,Acarbose
3,2.thau_tinh,40.798,Arbosnew 50,Acarbose,79,Thành phố Hồ Chí Minh,Thành phố Hồ Chí Minh,NaN,NaN,NaN,...,None,1,1,2025-10-25 22:18:22,2025-04-01,2026-12-31,NaT,NaT,NaT,Acarbose
4,2.thau_tinh,40.48,Gyoryg,Acarbose,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,None,1,1,2025-10-25 22:18:22,2025-04-11,2027-04-11,NaT,NaT,NaT,Acarbose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41393,3.thau_rieng_le,40.1025,Smoflipid 20%,Nhũ dịch lipid,37,Tỉnh Ninh Bình,Bv Quân Y 5/Cục Hậu Cần-Kỹ Thuật/Quân Đoàn 12,37102,Bv Quân Y 5/Cục Hậu Cần-Kỹ Thuật/Quân Đoàn 12,40.1025,...,None,1,3,2025-10-25 22:21:51,2025-04-21,NaT,2025-04-21,2025-04-21,2026-04-19,Nhũ dịch lipid
41394,3.thau_rieng_le,40.1025,SMOFlipid 20%,Nhũ dịch lipid,31,Thành phố Hải Phòng,Bv Nhi Hải Phòng,31032,Bv Nhi Hải Phòng,40.1025,...,None,1,1,2025-10-25 22:21:51,2025-04-09,NaT,2025-04-09,2025-04-09,2025-09-08,Nhũ dịch lipid
41395,3.thau_rieng_le,40.1025,SMOFlipid 20%,Nhũ dịch lipid,26,Tỉnh Vĩnh Phúc,Ttyt Khu Vực Tam Đảo,26026,Ttyt Khu Vực Tam Đảo,40.1025,...,None,1,1,2025-10-25 22:21:51,2025-04-03,NaT,2025-04-03,2025-04-03,2026-04-02,Nhũ dịch lipid
41396,3.thau_rieng_le,40.1025,Lipofundin MCT/LCT 10%-250ml,Nhũ dịch lipid,38,Tỉnh Thanh Hóa,Bv Điều Dưỡng Phcn Tw,38034,Bv Điều Dưỡng Phcn Tw,40.1025,...,None,1,5,2025-10-25 22:21:51,2025-04-15,NaT,2025-04-15,2025-04-15,2026-04-14,Nhũ dịch lipid
41397,3.thau_rieng_le,40.1025,SMOFlipid 20%,Nhũ dịch lipid,44,Tỉnh Quảng Bình,Bv Hữu Nghị Việt Nam-Cuba Đồng Hới,44005,Bv Hữu Nghị Việt Nam-Cuba Đồng Hới,40.1025,...,None,1,1,2025-10-25 22:21:51,2025-04-14,NaT,2025-04-14,2025-04-14,2026-01-14,Nhũ dịch lipid

In [ ]:
# Filter ra một mục tùy chọn
test_data.filter(by='IMP').show_data()

In [ ]:
# Tính tổng số lượng
print(f'Tổng số lượng của IMP: {test_data.filter(by='IMP').sum(value_col='soluong'):,.0f}') # Cái ':,.0f' là để hiển thị dấu phẩy hàng nghìn
 
# Tính tổng giá trị
print(f'Tổng giá trị của IMP: {test_data.filter(by='IMP').sum(value_col='thanhtien'):,.0f}')

Tổng số lượng của IMP: 25,647,070
Tổng giá trị của IMP: 288,706,927,665

# Test

In [5]:
%load_ext autoreload
%autoreload 2

from config.filter_config import producer_config, country_config, active_ingred_config
from src.utils.data_loader import read_xml, filter_data

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
# test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls' # đưa PATH đến data ở đây. 
# test_data = read_xml(test_path)

In [ ]:
# sorted([str(x) for x in test_data['hoatchat'].unique().tolist() if not None])

In [50]:
matched, unmatched = filter_data(
    test_data.show_data(), 
    active_ingred_config, 
    verbose=True, 
    return_unmatched=True
)

c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:210: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = clean_series.str.contains(include_pat, na=False)
c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:212: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = cond & (~clean_series.str.contains(exclude_pat, na=False))

=== BÁO CÁO MATCH DỮ LIỆU ===
Cột gán nhãn:       'active_ingredient'
Tổng số dòng:       41,472
Đã match (gán nhãn): 40,821 (98.43%)
Chưa match:         651 (1.57%)

Chi tiết theo 'active_ingredient':
active_ingredient
Acetaminophen                                                                                     1157
Paracetamol                                                                                       1121
Amoxicilin + Acid clavulanic                                                                      1024
Vitamin B1 + B6 + B12                                                                              872
Natri clorid                                                                                       801
Nhôm hydroxyd + Magnesi hydroxyd + Simethicon                                                      721
Piracetam                                                                                          490
Enalapril + Hydroclorothiazid                                                                      482
Trimetazidin                                                                                       467
Metformin                                                                                          465
Ambroxol                                                                                           459
Salbutamol                                                                                         443
Bromhexin                                                                                          420
Cefalexin                                                                                          411
Sắt sulfat + acid folic                                                                            395
Nhôm hydroxyd + Magnesi hydroxyd                                                                   388
Vitamin A + D2 (Vitamin A + D3)                                                                    371
Drotaverin                                                                                         368
Amoxicilin                                                                                         357
Lactobacillus acidophilus                                                                          334
Cinnarizin                                                                                         333
Acetyl leucin                                                                                      331
Vitamin C                                                                                          321
Diosmin + Hesperidin                                                                               311
Tobramycin                                                                                         310
Aciclovir                                                                                          309
Bacillus subtilis                                                                                  303
Gliclazid                                                                                          299
Glimepirid + Metformin                                                                             296
Glibenclamid + Metformin                                                                           294
Glucose                                                                                            290
Methylprednisolon                                                                                  288
Nifedipin                                                                                          287
Omeprazol                                                                                          287
Acetylsalicylic acid (DL-lysin-acetylsalicylat)                                                    286
Losartan                                                                                           284
Cefuroxim                                                                                          267
Esomeprazol                                                                                        266
Vitamin B6 + magnesi lactat                                                                        266
Amlodipin                                                                                          265
Cefradin                                                                                           264
Bacillus clausii                                                                                   262
Meloxicam                                                                                          258
Natri clorid + natri lactat + kali clorid + calcium clorid + glucose (Ringer lactat + glucose)     256
Cefadroxil                                                                                         253
Kẽm                                                                                                249
Diclofenac                                                                                         231
Spiramycin + Metronidazol                                                                          231
Chlorpheniramin                                                                                    229
Saccharomyces boulardii                                                                            228
Telmisartan + Hydroclorothiazid                                                                    228
Sorbitol                                                                                           222
Cetirizin                                                                                          218
Atorvastatin                                                                                       217
Indapamid + Perindopril                                                                            212
Paracetamol + Chlorpheniramin                                                                      212
Dexamethason + Neomycin + Polymyxin B                                                              205
Captopril + Hydroclorothiazid                                                                      203
Metronidazol                                                                                       203
Bisoprolol                                                                                         202
Diosmectit                                                                                         202
Ampicilin + Sulbactam                                                                              200
Neomycin + Nystatin + Polymyxin B                                                                  199
Domperidon                                                                                         196
Simethicon                                                                                         193
Calci lactat + Calci carbonat                                                                      192
Codein + Terpin hydrat                                                                             192
Ciprofloxacin                                                                                      186
Ofloxacin                                                                                          185
Cefaclor                                                                                           179
Colchicin                                                                                          176
Dexamethason + Tobramycin                                                                          174
Gliclazid + Metformin                                                                              174
Perindopril                                                                                        171
Rotundin                                                                                           171
Perindopril + Amlodipin                                                                            168
Lisinopril + Hydroclorothiazid                                                                     166
Calci lactat                                                                                       164
Attapulgit + Magnesi carbonat + Nhôm hydroxyd                                                      163
Lisinopril                                                                                         163
Ramipril                                                                                           162
Alimemazin                                                                                         159
Alphachymotrypsin                                                                                  158
Phenobarbital                                                                                      150
Felodipin                                                                                          148
Thiamin (Vitamin B1)                                                                               144
Irbesartan                                                                                         141
Acid tranexamic                                                                                    139
Famotidin                                                                                          139
Candesartan                                                                                        138
Metronidazol + Neomycin + Nystatin                                                                 135
Lovastatin                                                                                         133
Insulin người                                                                                      132
Chlorpromazin                                                                                      131
Glimepirid                                                                                         131
Losartan + Hydroclorothiazid                                                                       130
Eperison                                                                                           127
Bisoprolol + Hydroclorothiazid                                                                     125
Kali clorid                                                                                        125
Loratadin                                                                                          122
Fenofibrat                                                                                         118
Acid valproic / Natri valproat                                                                     117
Dextromethorphan                                                                                   115
Nicotinamid (Vitamin PP)                                                                           115
Thiocolchicosid                                                                                    114
Levomepromazin                                                                                     111
Nước cất pha tiêm                                                                                  111
Paracetamol + Ibuprofen                                                                            110
Acid salicylic + Betamethason dipropionat                                                          109
Phytomenadion (Vitamin K1)                                                                         108
Alverin + Simethicon                                                                               107
Metoprolol                                                                                         107
Paracetamol + Codein                                                                               106
Loxoprofen                                                                                         105
Povidon iod                                                                                        103
Trimebutin                                                                                          99
Allopurinol                                                                                         97
Dexchlorpheniramin                                                                                  97
Diosmin                                                                                             97
Budesonid                                                                                           96
Valsartan + Hydroclorothiazid                                                                       94
Pravastatin                                                                                         93
Telmisartan                                                                                         93
Pyridoxin (Vitamin B6)                                                                              92
Sulfamethoxazol + Trimethoprim                                                                      92
Ibuprofen                                                                                           91
Candesartan + Hydroclorothiazid                                                                     90
Cefixim                                                                                             89
Enalapril                                                                                           89
Nor-epinephrin (Nor- adrenalin)                                                                     89
Valsartan                                                                                           89
Diazepam                                                                                            88
Vitamin B12 (cyanocobalamin, hydroxocobalamin)                                                      87
Erythromycin                                                                                        87
Rosuvastatin                                                                                        86
Flunarizin                                                                                          84
Insulin analog                                                                                      84
Lidocain                                                                                            84
Levothyroxin                                                                                        81
Irbesartan + Hydroclorothiazid                                                                      80
Tinidazol                                                                                           80
Sucralfat                                                                                           78
Nhôm phosphat                                                                                       77
Cloxacilin                                                                                          77
Ipratropium bromid + Salbutamol                                                                     77
Clopidogrel                                                                                         76
Xylometazolin                                                                                       76
Glucosamin                                                                                          74
Khoáng chất đa lượng và vi lượng                                                                    74
Haloperidol                                                                                         72
Prednisolon                                                                                         72
Levofloxacin                                                                                        71
Spiramycin                                                                                          71
Dimenhydrinat                                                                                       70
Morphin                                                                                             69
Dung dịch Ringer lactat                                                                             68
Cefpodoxim                                                                                          67
Adrenalin                                                                                           66
Oxytocin                                                                                            65
Calci carbonat + Vitamin D3                                                                         64
Moxifloxacin                                                                                        64
Clotrimazol                                                                                         63
Promethazin                                                                                         63
Vitamin A                                                                                           63
Vitamin E                                                                                           63
Acid amin                                                                                           62
Fluvastatin                                                                                         62
Fluticason + Salmeterol                                                                             61
Furosemid                                                                                           61
Calci clorid                                                                                        60
Isosorbid                                                                                           60
Amlodipin + Atorvastatin                                                                            59
Glyceryl trinitrat                                                                                  59
Propranolol                                                                                         59
Chlorpheniramin + Dextromethorphan                                                                  58
Fexofenadin                                                                                         58
Amlodipin + Lisinopril                                                                              57
Glipizid                                                                                            56
Bisacodyl                                                                                           55
Cefazolin                                                                                           55
Cefoperazon                                                                                         55
Desloratadin                                                                                        55
Nystatin                                                                                            55
Metoclopramid                                                                                       54
Azithromycin                                                                                        53
Betahistin                                                                                          53
Cồn                                                                                                 53
Etoricoxib                                                                                          53
Nicorandil                                                                                          53
Captopril                                                                                           52
Amlodipin + Indapamid                                                                               50
Clindamycin                                                                                         50

In [ ]:
# Các mục đã match
sorted([str(x) for x in matched['hoatchat'].unique().tolist() if not None])

In [51]:
# Các mục chưa match

sorted([str(x) for x in unmatched['hoatchat'].unique().tolist() if not None])

['100ml nhũ tương chứa: Dầu đậu nành tinh chế 6 gam + Triglycerid mạch trung bình 6 gam + Dầu ô-liu tinh chế 5 gam + Dầu cá tinh chế 3 gam',
 'Acetylleucin (N-Acetyl-DL-Leucin)',
 'Acid Ascorbic',
 'Acid amin + chất điện giải',
 'Acid amin + glucose + lipid + điện giải',
 'Acid amin + glucose + lipid + điện giải (*)',
 'Acid ascorbic',
 'Acid ascorbic 500 mg',
 'Alanine + Arginine + Aspartic acid + Glutamic acid + Glycine + Histidine + Isoleucine + Leucine + Lysine (dưới dạng Lysine acetate) + Methionine + Phenylalanine + Proline + Serine + Threonine + Tryptophan + Tyrosine + Valine + Natri acetat trihydrat + Natri glycerophosphate hydrat + Kali clorid + Magnesi clorid hexahydrat + Calci clorid dihydrat + Glucose anhydrous + Dầu oliu tinh khiết và dầu đậu nành tinh khiết',
 'Calci 250mg dưới dạng (Calci lactat gluconat + calci carbonat)',
 'Cephalexin',
 'Cephalexin (dưới \ndạng Cephalexin \nmonohydrat \ncompacted)',
 'Cephalexin (dưới dạng Cephalexin monohydrat)',
 'Codein camphosulfonat + Sulfogaiacol + Cao mềm Grindelia',
 'Cyanocobalamin',
 'Dầu đậu nành tinh chế; triglycerid mạch trung bình; dầu oliu tinh chế; dầu cá tinh chế',
 'Dầu đậu nành; Glycerol; Phospholipid từ trứng',
 'Glucose khan (dưới dạng glucose monohydrate) + Natri clorid + Kali clorid + Trinatri citrat khan (dưới dạng Trinatri citrat. 2H2O)',
 'Glucose khan + Natri clorid + Kali clorid + Tri Natricitrat dihydrat',
 'Irbersatan + hydroclorthiazid',
 'Isosorbid-5-mononitrat',
 'Khoang A: Mỗi 1000ml chứa Calcium clorid dihydrat 5,145g + Magnesium clorid hexahydrat 2,033g + Acid lactic 5,4g; Khoang B: Mỗi 1000ml chứa Sodium Chlorid 6,45g + Sodium hydrogen carbonat 3,09g; Dung dịch sau khi phối hợp chứa: Calcium 1,75mmol/l + Magnesium 0,5mmol/l + Sodium 140mmol/l + Chlorid 109,5mmol/l + Lactat 3mmol/l + hydrogen carbonat 32mmol/l',
 'L-Alanin 1,575g + L-Arginin 1,225g + Amino-acetic acid (Glycin) 0,80g + L-Histidin 1,075g + L-Isoleucin 1,275g + L-Leucin 2,575g + L-Lysin monoacetat 2,5025g (tương đương 1,775g L-Lysin) + L-Methionin 0,70g + L-Phenylalanin 0,95g + L-Prolin 1,075g + L-Serin 1,125g + L-Threonin 1,20g + L-Tryptophan 0,475g + L-Valin 1,55g + Acetylcystein 0,125g (tương đương 0,0925g L-Cystein) + L-Malic acid 0,375g + Acid acetic 99% (acid acetic băng) 0,345g',
 'Meclofenoxate hydroclorid',
 'Mỗi 250ml nhũ tương chứa: Dầu đậu nành tinh chế 25g + Glycerol 6,25g + Phospholipid tinh chế từ trứng 1,5g',
 'Mỗi 500ml chứa: Natri clorid 3g + Kali clorid 0,2g + Natri lactat 1,6g + Calci clorid.2H20 0,135g',
 'Mỗi 500ml chứa: Natri clorid 3g; Kali clorid 0,2g; Natri lactat 1,6g; Calci clorid.2H20 0,135g',
 'Mỗi 8ml chứa: Natri clorid 72mg',
 'Mỗi gói 3g chứa: Acetylcystein 200mg',
 'N - Acetylcystein',
 'N-Acetyl DL-Leucin',
 'N-Acetyl-DL-Leucin',
 'N-Acetylcystein',
 'N-acetyl-dl- leucin',
 'N-acetylcystein',
 'Natri clorid + Kali clorid + Natri lactat + Calci clorid.2H2O',
 'Natri clorid + Natri citrat dihydrat + Kali clorid + Glucose khan',
 'Natri clorid + natri citrat + kali clorid + glucose khan',
 'Tropicamid + Phenylephrin hydroclorid']

# Drug type matching

In [30]:
drug_types = pd.read_excel('../data/template/drug_type.xlsx').dropna(how='all').reset_index(drop=True)[1:]
drug_types.columns = drug_types.iloc[0].values
drug_types = drug_types[1:].reset_index(drop=True).dropna(axis=1, how='all').assign(
    STT = lambda x: pd.to_numeric(x['STT'], errors='coerce')
)
drug_types['Loại thuốc 1'] = drug_types['Loại thuốc 1'].ffill()
drug_types['Loại thuốc 2'] = drug_types['Loại thuốc 2'].ffill()

In [40]:
test_data.filter().show_data()

c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:210: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = clean_series.str.contains(include_pat, na=False)
c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:212: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = cond & (~clean_series.str.contains(exclude_pat, na=False))

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd,active_ingredient
0,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,NaT,NaT,Acarbose
1,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,Acarbose
2,3.thau_rieng_le,40.798,Savi Acarbose 25,Acarbose,10,Tỉnh Lào Cai,Bvđk Khu Vực Văn Bàn-Lào Cai,10008,Bvđk Khu Vực Văn Bàn-Lào Cai,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-16,2027-05-16,2025-05-16,2025-05-16,2027-05-16,Acarbose
3,2.thau_tinh,40.798,Arbosnew 50,Acarbose,79,Thành phố Hồ Chí Minh,Thành phố Hồ Chí Minh,NaN,NaN,NaN,...,None,1,1,2025-10-25 22:18:22,2025-04-01,2026-12-31,NaT,NaT,NaT,Acarbose
4,2.thau_tinh,40.48,Gyoryg,Acarbose,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,None,1,1,2025-10-25 22:18:22,2025-04-11,2027-04-11,NaT,NaT,NaT,Acarbose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41500,3.thau_rieng_le,40.655,Gysudo,Đồng sulfat,82,Tỉnh Tiền Giang,Điểm Y Tế Châu Thành 2,82129,Điểm Y Tế Châu Thành 2,40.655,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,Đồng sulfat
41501,3.thau_rieng_le,40.655,Gysudo,Đồng sulfat,82,Tỉnh Tiền Giang,Điểm Y Tế Xã Bình Trưng 1,82136,Điểm Y Tế Xã Bình Trưng 1,40.655,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,Đồng sulfat
41502,3.thau_rieng_le,40.655,Gynocare,Đồng sulfat,66,Tỉnh Đắk Lắk,Ttyt Ea Hleo,66019,Ttyt Ea Hleo,40.655,...,None,1,1,2025-10-25 22:21:51,2025-05-05,NaT,2025-05-05,2025-05-05,2026-05-05,Đồng sulfat
41503,3.thau_rieng_le,40.655,Gysudo,Đồng sulfat,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.655,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2026-11-14,Đồng sulfat
41504,3.thau_rieng_le,40.655,Gynocare,Đồng sulfat,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.655,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2026-11-14,Đồng sulfat

In [41]:
data = test_data.filter().show_data()

c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:210: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = clean_series.str.contains(include_pat, na=False)
c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:212: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = cond & (~clean_series.str.contains(exclude_pat, na=False))

['Atropin sulfat',
 'Bupivacain hydroclorid',
 'Desfluran',
 'Dexmedetomidin',
 'Diazepam',
 'Etomidat',
 'Fentanyl',
 'Halothan',
 'Isofluran',
 'Ketamin',
 'Levobupivacain',
 'Lidocain hydroclodrid',
 'Lidocain + epinephrin (adrenalin)',
 'Lidocain+ prilocain',
 'Midazolam',
 'Morphin',
 'Oxy dược dụng',
 'Pethidin',
 'Procain hydroclorid',
 'Proparacain hydroclorid',
 'Propofol',
 'Ropivacain hydroclorid',
 'Sevofluran',
 'Sufentanil',
 'Thiopental (muối natri)',
 'Atracurium besylat',
 'Neostigmin metylsulfat (bromid)',
 'Pancuronium bromid',
 'Pipecuronium bromid',
 'Rocuronium bromid',
 'Suxamethonium clorid',
 'Vecuronium bromid',
 'Aceclofenac',
 'Aescin',
 'Celecoxib',
 'Dexibuprofen',
 'Diclofenac',
 'Etodolac',
 'Etoricoxib',
 'Floctafenin',
 'Flurbiprofen natri',
 'Ibuprofen',
 'Ibuprofen + codein',
 'Ketoprofen',
 'Ketorolac',
 'Loxoprofen',
 'Meloxicam',
 'Methyl salicylat + dl-camphor + thymol + l-menthol + glycol salicylat + tocopherol acetat',
 'Nabumeton',
 'Naproxen',
 'Naproxen + esomeprazol',
 'Nefopam hydroclorid',
 'Oxycodone',
 'Paracetamol (acetaminophen)',
 'Paracetamol + chlorpheniramin',
 'Paracetamol + codein phosphat',
 'Paracetamol + diphenhydramin',
 'Paracetamol + ibuprofen',
 'Paracetamol + methocarbamol',
 'Paracetamol + phenylephrin',
 'Paracetamol + pseudoephedrin',
 'Paracetamol + tramadol',
 'Paracetamol + chlorpheniramin + dextromethorphan',
 'Paracetamol + chlorpheniramin + phenylephrin',
 'Paracetamol + chlorpheniramin + pseudoephedrin',
 'Paracetamol + diphenhydramin + phenylephrin',
 'Paracetamol + phenylephrin + dextromethorphan',
 'Paracetamol + chlorpheniramin + phenylephrine + dextromethorphan',
 'Pethidin hydroclorid',
 'Piroxicam',
 'Tenoxicam',
 'Tiaprofenic acid',
 'Tramadol',
 'Allopurinol',
 'Colchicin',
 'Probenecid',
 'Diacerein',
 'Glucosamin',
 'Adalimumab',
 'Alendronat',
 'Alendronat natri + cholecalciferol (Vitamin D3)',
 'Alpha chymotrypsin',
 'Calcitonin',
 'Etanercept',
 'Golimumab',
 'Infliximab',
 'Leflunomid',
 'Methocarbamol',
 'Risedronat',
 'Tocilizumab',
 'Zoledronic acid',
 'Alimemazin',
 'Bilastine',
 'Cetirizin',
 'Cinnarizin',
 'Chlorpheniramin (hydrogen maleat)',
 'Chlorpheniramin + dextromethorphan',
 'Chlorpheniramin + phenylephrin',
 'Desloratadin',
 'Dexchlorpheniramin',
 'Diphenhydramin',
 'Ebastin',
 'Epinephrin (adrenalin)',
 'Fexofenadin',
 'Ketotifen',
 'Levocetirizin',
 'Loratadin',
 'Loratadin + pseudoephedrin',
 'Mequitazin',
 'Promethazin hydroclorid',
 'Rupatadine',
 'Acetylcystein',
 'Atropin',
 'Calci gluconat',
 'Dantrolen',
 'Deferoxamin',
 'Dimercaprol',
 'Edetat natri calci (EDTA Ca- Na)',
 'Ephedrin',
 'Esmolol',
 'Flumazenil',
 'Fomepizol',
 'Glucagon',
 'Glutathion',
 'Hydroxocobalamin',
 'Calci folinat (folinic acid, leucovorin)',
 'Naloxon hydroclorid',
 'Naltrexon',
 'Natri hydrocarbonat (natri bicarbonat)',
 'Natri nitrit',
 'Natri thiosulfat',
 'Nor-epinephrin (Nor- adrenalin)',
 'Penicilamin',
 'Phenylephrin',
 'Polystyren',
 'Pralidoxim',
 'Protamin sulfat',
 'Meglumin natri succinat',
 'Sorbitol',
 'Silibinin',
 'Succimer',
 'Sugammadex',
 'Than hoạt',
 'Than hoạt + sorbitol',
 'Xanh methylen',
 'Carbamazepin',
 'Gabapentin',
 'Lamotrigine',
 'Levetiracetam',
 'Oxcarbazepin',
 'Phenobarbital',
 'Phenytoin',
 'Pregabalin',
 'Topiramat',
 'Valproat natri',
 'Valproat natri + valproic acid',
 'Valproic acid',
 'Albendazol',
 'Diethylcarbamazin (dihydrogen citrat)',
 'Ivermectin',
 'Mebendazol',
 'Niclosamid',
 'Praziquantel',
 'Pyrantel',
 'Triclabendazol',
 'Amoxicilin',
 'Amoxicilin + acid clavulanic',
 'Amoxicilin + sulbactam',
 'Ampicilin (muối natri)',
 'Ampicilin + sulbactam',
 'Benzathin benzylpenicilin',
 'Benzylpenicilin',
 'Cefaclor',
 'Cefadroxil',
 'Cefalexin',
 'Cefalothin',
 'Cefamandol',
 'Cefazolin',
 'Cefdinir',
 'Cefepim',
 'Cefixim',
 'Cefmetazol',
 'Cefoperazon',
 'Cefoperazon + sulbactam',
 'Cefotaxim',
 'Cefotiam',
 'Cefoxitin',
 'Cefpirom',
 'Cefpodoxim',
 'Cefradin',
 'Ceftazidim',
 'Ceftazidim + avibactam',
 'Ceftibuten',
 'Ceftizoxim',
 'Ceftolozan + tazobactam',
 'Ceftriaxon',
 'Cefuroxim',
 'Cloxacilin',
 'Doripenem*',
 'Ertapenem*',
 'Imipenem + cilastatin*',
 'Meropenem*',
 'Oxacilin',
 'Piperacilin',
 'Piperacilin + tazobactam',
 'Phenoxy methylpenicilin',
 'Procain benzylpenicilin',
 'Sultamicillin (Ampicilin + sulbactam)',
 'Ticarcillin + acid clavulanic',
 'Amikacin',
 'Gentamicin',
 'Neomycin (sulfat)',
 'Neomycin + polymyxin B',
 'Neomycin + polymyxin B + dexamethason',
 'Netilmicin sulfat',
 'Tobramycin',
 'Tobramycin + dexamethason',
 'Cloramphenicol',
 'Metronidazol',
 'Metronidazol + neomycin + nystatin',
 'Secnidazol',
 'Tinidazol',
 'Clindamycin',
 'Azithromycin',
 'Clarithromycin',
 'Erythromycin',
 'Roxithromycin',
 'Spiramycin',
 'Spiramycin + metronidazol',
 'Tretinoin + erythromycin',
 'Ciprofloxacin',
 'Levofloxacin',
 'Lomefloxacin',
 'Moxifloxacin',
 'Nalidixic acid',
 'Norfloxacin',
 'Ofloxacin',
 'Pefloxacin',
 'Sulfadiazin bạc',
 'Sulfadimidin (muối natri)',
 'Sulfadoxin + pyrimethamin',
 'Sulfaguanidin',
 'Sulfamethoxazol + trimethoprim',
 'Sulfasalazin',
 'Doxycyclin',
 'Minocyclin',
 'Tigecyclin*',
 'Tetracyclin hydroclorid',
 'Argyrol',
 'Colistin*',
 'Daptomycin',
 'Fosfomycin*',
 'Linezolid*',
 'Nitrofurantoin',
 'Rifampicin',
 'Teicoplanin*',
 'Vancomycin',
 'Abacavir (ABC)',
 'Darunavir',
 'Efavirenz (EFV hoặc EFZ)',
 'Lamivudin',
 'Nevirapin (NVP)',
 'Raltegravir',
 'Ritonavir',
 'Tenofovir (TDF)',
 'Zidovudin (ZDV hoặc AZT)',
 'Lamivudin + tenofovir',
 'Lamivudine+ zidovudin',
 'Lopinavir + ritonavir (LPV/r)',
 'Tenofovir + lamivudin + efavirenz',
 'Tenoforvir + lamivudine + dolutegravir',
 'Zidovudin (ZDV hoặc AZT) + lamivudin + nevirapin (NVP)',
 'Daclatasvir',
 'Sofosbuvir',
 'Sofosbuvir + ledipasvir',
 'Sofosbuvir + velpatasvir',
 'Pegylated interferon (peginterferon) alpha (2a hoặc 2b)',
 'Aciclovir',
 'Entecavir',
 'Gancyclovir*',
 'Oseltamivir',
 'Ribavirin',
 'Valganciclovir*',
 'Zanamivir',
 'Molnupiravir',
 'Amphotericin B*',
 'Anidulafungin',
 'Butoconazol nitrat',
 'Caspofungin*',
 'Ciclopiroxolamin',
 'Clotrimazol',
 'Dequalinium clorid',
 'Econazol',
 'Fluconazol',
 'Fenticonazol nitrat',
 'Flucytosin',
 'Griseofulvin',
 'Itraconazol',
 'Ketoconazol',
 'Micafungin',
 'Miconazol',
 'Natamycin',
 'Nystatin',
 'Policresulen',
 'Posaconazol*',
 'Terbinafin (hydroclorid)',
 'Voriconazol*',
 'Clotrimazol + betamethason',
 'Clorquinaldol + promestrien',
 'Miconazol + hydrocortison',
 'Nystatin + metronidazol + neomycin',
 'Nystatin + neomycin + polymyxin B',
 'Diiodohydroxyquinolin',
 'Hydroxy cloroquin',
 'Ethambutol',
 'Isoniazid',
 'Isoniazid + ethambutol',
 'Pyrazinamid',
 'Rifampicin + isoniazid',
 'Rifampicin + isoniazid + pyrazinamid',
 'Rifampicin + isoniazid + pyrazinamid + ethambutol',
 'Streptomycin',
 'Bedaquiline',
 'Capreomycin',
 'Clofazimine',
 'Cycloserin',
 'Delamanid',
 'Ethionamid',
 'Kanamycin',
 'PAS- Na',
 'Prothionamid',
 'Artesunat',
 'Cloroquin',
 'Piperaquin + dihydroartemisinin',
 'Primaquin',
 'Quinin',
 'Dihydro ergotamin mesylat',
 'Ergotamin (tartrat)',
 'Flunarizin',
 'Sumatriptan',
 'Arsenic trioxid',
 'Bendamustine',
 'Bleomycin',
 'Bortezomib',
 'Busulfan',
 'Capecitabin',
 'Carboplatin',
 'Carmustin',
 'Cisplatin',
 'Cyclophosphamid',
 'Cytarabin',
 'Dacarbazin',
 'Dactinomycin',
 'Daunorubicin',
 'Decitabin',
 'Docetaxel',
 'Doxorubicin',
 'Epirubicin hydroclorid',
 'Etoposid',
 'Everolimus',
 'Fludarabin',
 'Fluorouracil (5-FU)',
 'Gemcitabin',
 'Hydroxyurea (Hydroxycarbamid)',
 'Idarubicin',
 'Ifosfamid',
 'Irinotecan',
 'L-asparaginase',
 'Melphalan',
 'Mercaptopurin',
 'Mesna',
 'Methotrexat',
 'Mitomycin',
 'Mitoxantron',
 'Oxaliplatin',
 'Paclitaxel',
 'Pemetrexed',
 'Procarbazin',
 'Tegafur-uracil (UFT hoặc UFUR)',
 'Tegafur + gimeracil + oteracil kali',
 'Temozolomid',
 'Tretinoin (All-trans retinoic acid)',
 'Vinblastin sulfat',
 'Vincristin sulfat',
 'Vinorelbin',
 'Afatinib dimaleate',
 'Bevacizumab',
 'Cetuximab',
 'Erlotinib',
 'Gefitinib',
 'Imatinib',
 'Nilotinib',
 'Nimotuzumab',
 'Pazopanib',
 'Rituximab',
 'Sorafenib',
 'Trastuzumab',
 'Abiraterone acetate',
 'Anastrozol',
 'Bicalutamid',
 'Degarelix',
 'Exemestan',
 'Flutamid',
 'Fulvestrant',
 'Goserelin acetat',
 'Letrozol',
 'Leuprorelin acetat',
 'Tamoxifen',
 'Triptorelin',
 'Anti thymocyte globulin',
 'Azathioprin',
 'Các kháng thể gắn với interferon ở người',
 'Ciclosporin',
 'Basiliximab',
 'Glycyl funtumin (hydroclorid)',
 'Lenalidomid',
 'Mycophenolat',
 'Tacrolimus',
 'Thalidomid',
 'Clodronat disodium',
 'Pamidronat',
 'Alfuzosin',
 'Dutasterid',
 'Flavoxat',
 'Lipidosterol serenoarepense (Lipid-sterol của Sercnoa repens)',
 'Pinene + camphene + cineol + fenchone + borneol + anethol',
 'Solifenacin succinate',
 'Tamsulosin hydroclorid',
 'Levodopa + carbidopa',
 'Levodopa + carbidopa monohydrat + entacapone',
 'Levodopa + benserazid',
 'Piribedil',
 'Pramipexol',
 'Tolcapon',
 'Rotigotine',
 'Trihexyphenidyl hydroclorid',
 'Acid folic (vitamin B9)',
 'Sắt fumarat',
 'Sắt (III) hydroxyd polymaltose',
 'Sắt protein succinylat',
 'Sắt sucrose (hay dextran)',
 'Sắt sulfat',
 'Sắt ascorbat + acid folic',
 'Sắt fumarat + acid folic',
 'Sắt (III) hydroxyd polymaltose + acid folic',
 'Sắt sulfat + acid folic',
 'Carbazochrom',
 'Cilostazol',
 'Enoxaparin (natri)',
 'Etamsylat',
 'Heparin (natri)',
 'Nadroparin',
 'Phytomenadion (vitamin K1)',
 'Tranexamic acid',
 'Triflusal',
 'Warfarin (muối natri)',
 'Albumin',
 'Albumin + immuno globulin',
 'Huyết tương',
 'Khối bạch cầu',
 'Khối hồng cầu',
 'Khối tiểu cầu',
 'Máu toàn phần',
 'Phức hợp kháng yếu tố ức chế yếu tố VIII bắc cầu (Factor Eight Inhibitor Bypassing Activity - FEIBA)',
 'Yếu tố VIla',
 'Yếu tố VIII',
 'Yếu tố IX',
 'Yếu tố VIII + yếu tố von Willebrand',
 'Dextran 40',
 'Dextran 60',
 'Dextran 70',
 'Gelatin',
 'Gelatin succinyl + natri clorid + natri hydroxyd',
 'Tinh bột este hóa (hydroxyethyl starch)',
 'Deferasirox',
 'Deferipron',
 'Eltrombopag',
 'Erythropoietin',
 'Filgrastim',
 'Methoxy polyethylene glycol epoetin beta',
 'Pegfilgrastim',
 'Diltiazem',
 'Glyceryl trinitrat (Nitroglycerin)',
 'Isosorbid (dinitrat hoặc mononitrat)',
 'Nicorandil',
 'Trimetazidin',
 'Adenosin triphosphat',
 'Amiodaron hydroclorid',
 'Isoprenalin',
 'Propranolol hydroclorid',
 'Sotalol',
 'Verapamil hydroclorid',
 'Acebutolol',
 'Amlodipin',
 'Amlodipin + atorvastatin',
 'Amlodipin + losartan',
 'Amlodipin + lisinopril',
 'Amlodipin + indapamid',
 'Amlodipin + indapamid + perindopril',
 'Amlodipin + telmisartan',
 'Amlodipin + valsartan',
 'Amlodipin + valsartan + hydrochlorothiazid',
 'Atenolol',
 'Benazepril hydroclorid',
 'Bisoprolol',
 'Bisoprolol + hydroclorothiazid',
 'Candesartan',
 'Candesartan + hydrochlorothiazid',
 'Captopril',
 'Captopril + hydroclorothiazid',
 'Carvedilol',
 'Cilnidipin',
 'Clonidin',
 'Doxazosin',
 'Enalapril',
 'Enalapril + hydrochlorothiazid',
 'Felodipin',
 'Felodipin + metoprolol tartrat',
 'Hydralazin',
 'Imidapril',
 'Indapamid',
 'Irbesartan',
 'Irbesartan + hydroclorothiazid',
 'Lacidipin',
 'Lercanidipin hydroclorid',
 'Lisinopril',
 'Lisinopril + hydroclorothiazid',
 'Losartan',
 'Losartan + hydroclorothiazid',
 'Methyldopa',
 'Metoprolol',
 'Nebivolol',
 'Nicardipin',
 'Nifedipin',
 'Perindopril',
 'Perindopril + amlodipin',
 'Perindopril + indapamid',
 'Quinapril',
 'Ramipril',
 'Rilmenidin',
 'Telmisartan',
 'Telmisartan + hydroclorothiazid',
 'Valsartan',
 'Valsartan + hydroclorothiazid',
 'Heptaminol hydroclorid',
 'Digoxin',
 'Dobutamin',
 'Dopamin hydroclorid',
 'Ivabradin',
 'Milrinon',
 'Acenocoumarol',
 'Acetylsalicylic acid (DL-lysin-acetylsalicylat)',
 'Acetylsalicylic acid + clopidogrel',
 'Alteplase',
 'Apixaban',
 'Ciopidogrel',
 'Dabigatran',
 'Dipyridamol + acetylsalicylic acid',
 'Eptifibatid',
 'Fondaparinux sodium',
 'Rivaroxaban',
 'Streptokinase',
 'Tenecteplase',
 'Ticagrelor',
 'Urokinase',
 'Atorvastatin',
 'Atorvastatin + ezetimibe',
 'Bezafibrat',
 'Ciprofibrat',
 'Ezetimibe',
 'Fenofibrat',
 'Fluvastatin',
 'Gemfibrozil',
 'Lovastatin',
 'Pravastatin',
 'Rosuvastatin',
 'Simvastatin',
 'Simvastatin + ezetimibe',
 'Bosentan',
 'Iloprost',
 'Prostaglandin E1',
 'Fructose 1,6 diphosphat',
 'Indomethacin',
 'Magnesi clorid + kali clorid + procain hydroclorid',
 'Naftidrofuryl',
 'Nimodipin',
 'Nitric oxid (nitrogen monoxid) (NO)',
 'Succinic acid + nicotinamid + inosine + riboflavin natri phosphat',
 'Sulbutiamin',
 'Tolazolin',
 'Acitretin',
 'Adapalen',
 'Alpha - terpineol',
 'Amorolfin',
 'Azelaic acid',
 'Benzoic acid + salicylic acid',
 'Benzoyl peroxid',
 'Bột talc',
 'Calcipotriol',
 'Calcipotriol + betamethason dipropionat',
 'Capsaicin',
 'Clobetasol propionat',
 'Clobetasol butyrat',
 'Cortison',
 'Cồn A.S.A',
 'Cồn boric',
 'Cồn BSI',
 'Crotamiton',
 'Dapson',
 'Desonid',
 'Dexpanthenol (panthenol, vitamin B5)',
 'Diethylphtalat',
 'S-bioallethrin + piperonyl butoxid',
 'Flumethason + clioquinol',
 'Fusidic acid',
 'Fusidic acid + betamethason',
 'Fusidic acid + hydrocortison',
 'Isotretinoin',
 'Kẽm oxid',
 'Mometason furoat',
 'Mometason furoat + salicylic acid',
 'Mupirocin',
 'Natri hydrocarbonat',
 'Nepidermin',
 'Nước oxy già',
 'Para aminobenzoic acid',
 'Recombinant human Epidermal Growth Factor (rhEGF)',
 'Salicylic acid',
 'Salicylic acid + betamethason dipropionat',
 'Secukinumab',
 'Tretinoin',
 'Trolamin',
 'Tyrothricin',
 'Urea',
 'Ustekinumab',
 'Fluorescein (natri)',
 'Adipiodon (meglumin)',
 'Amidotrizoat',
 'Bari sulfat',
 'Ethyl ester của acid béo iod hóa trong dầu hạt thuốc phiện',
 'Gadobenic acid (dimeglumin)',
 'Gadobutrol',
 'Gadoteric acid',
 'lobitridol',
 'Iodixanol',
 'Iohexol',
 'lopamidol',
 'Iopromid acid',
 'Ioxitalamat natri + ioxitalamat meglumin',
 'Muối natri và meglumin của acid ioxaglic',
 'Polidocanol',
 'Cồn 70°',
 'Cồn iod',
 'Đồng sulfat',
 'Povidon iodin',
 'Natri hypoclorid đậm đặc',
 'Natri clorid',
 'Furosemid',
 'Furosemid + spironolacton',
 'Hydroclorothiazid',
 'Spironolacton',
 'Aluminum phosphat',
 'Attapulgit mormoiron hoạt hóa + hỗn hợp magnesi carbonat-nhôm hydroxyd',
 'Bismuth',
 'Cimetidin',
 'Famotidin',
 'Guaiazulen + dimethicon',
 'Lansoprazol',
 'Magnesi hydroxyd + nhôm hydroxyd',
 'Magnesi hydroxyd + nhôm hydroxyd + simethicon',
 'Magnesi trisilicat + nhôm hydroxyd',
 'Nizatidin',
 'Omeprazol',
 'Esomeprazol',
 'Pantoprazol',
 'Rabeprazol',
 'Ranitidin',
 'Ranitidin + bismuth + sucralfat',
 'Rebamipid',
 'Sucralfat',
 'Dimenhydrinat',
 'Domperidon',
 'Granisetron hydroclorid',
 'Metoclopramid',
 'Ondansetron',
 'Palonosetron hydroclorid',
 'Alverin citrat',
 'Alverin cifrat + simethicon',
 'Drotaverin clohydrat',
 'Hyoscin butylbromid',
 'Mebeverin hydroclorid',
 'Papaverin hydroclorid',
 'Phloroglucinol hydrat + trimethyl phloroglucinol',
 'Tiemonium methylsulfat',
 'Tiropramid hydroclorid',
 'Bisacodyl',
 'Docusate natri',
 'Glycerol',
 'Lactulose',
 'Macrogol',
 'Macrogol + natri sulfat + natri bicarbonat + natri clorid + kali clorid',
 'Magnesi sulfat',
 'Monobasic natri phosphat + dibasic natri phosphat',
 'Sorbitol + natri citrat',
 'Attapulgit mormoiron hoạt hóa',
 'Bacillus subtilis',
 'Bacillus clausii',
 'Berberin (hydroclorid)',
 'Dioctahedral smectit',
 'Diosmectit',
 'Gelatin tannat',
 'Kẽm sulfat',
 'Kẽm gluconat',
 'Lactobacillus acidophilus',
 'Loperamid',
 'Nifuroxazid',
 'Racecadotril',
 'Saccharomyces boulardii',
 'Cao ginkgo biloba + heptaminol clohydrat + troxerutin',
 'Diosmin',
 'Diosmin + hesperidin',
 'Amylase + lipase + protease',
 'Citrullin malat',
 'Itoprid',
 'L-Omithin - L- aspartat',
 'Mesalazin (mesalamin)',
 'Octreotid',
 'Simethicon',
 'Silymarin',
 'Somatostatin',
 'Terlipressin',
 'Trimebutin maleat',
 'Ursodeoxycholic acid',
 'Otilonium bromide',
 'Beclometason (dipropionat)',
 'Betamethason',
 'Danazol',
 'Dexamethason',
 'Dexamethason phosphat + neomycin',
 'Betamethasone + dexchlorpheniramin',
 'Fludrocortison acetat',
 'Fluocinolon acetonid',
 'Hydrocortison',
 'Methyl prednisolon',
 'Prednisolon acetat (natri phosphate)',
 'Prednison',
 'Triamcinolon acetonid',
 'Triamcinolon',
 'Triamcinolon + econazol',
 'Cyproteron acetat',
 'Somatropin',
 'Dydrogesteron',
 'Estradiol valerate',
 'Estriol',
 'Estrogen + norgestrel',
 'Ethinyl estradiol',
 'Ethinyl estradiol + cyproterone acetate',
 'Lynestrenol',
 'Nandrolon decanoat',
 'Norethisteron',
 'Nomegestrol acetat',
 'Promestrien',
 'Progesteron',
 'Raloxifen',
 'Testosteron (acetat, propionat, undecanoat)',
 'Acarbose',
 'Dapagliflozin',
 'Empagliflozin',
 'Glibenclamid + metformin',
 'Gliclazid',
 'Gliclazid + metformin',
 'Glimepirid',
 'Glimepirid + metformin',
 'Glipizid',
 'Insulin analog tác dụng nhanh, ngắn (Aspart, Lispro, Glulisine)',
 'Insulin analog tác dụng chậm, kéo dài (Glargine, Detemir, Degludec)',
 'Insulin analog trộn, hỗn hợp',
 'Insulin người tác dụng nhanh, ngắn',
 'Insulin người tác dụng trung bình, trung gian',
 'Insulin người trộn, hỗn hợp',
 'Linagliptin',
 'Linagliptin + metformin',
 'Liraglutide',
 'Metformin',
 'Repaglinid',
 'Saxagliptin',
 'Saxagliptin + metformin',
 'Sitagliptin',
 'Sitagliptin + metformin',
 'Vildagliptin',
 'Vildagliptin + metformin',
 'Carbimazol',
 'Levothyroxin (muối natri)',
 'Propylthiouracil (PTU)',
 'Thiamazol',
 'Desmopressin',
 'Vasopressin',
 'Alglucosidase alfa',
 'Immune globulin',
 'Huyết thanh kháng bạch hầu',
 'Huyết thanh kháng dại',
 'Huyết thanh kháng nọc rắn',
 'Huyết thanh kháng uốn ván',
 'Baclofen',
 'Botulinum toxin',
 'Eperison',
 'Mephenesin',
 'Pyridostigmin bromid',
 'Rivastigmine',
 'Tizanidin hydroclorid',
 'Thiocolchicosid',
 'Tolperison',
 'Acetazolamid',
 'Besifloxacin',
 'Betaxolol',
 'Bimatoprost',
 'Bimatoprost + timolol',
 'Brimonidin tartrat',
 'Brimonidin tartrat + timolol',
 'Brinzolamid',
 'Brinzolamid + timolol',
 'Bromfenac',
 'Carbomer',
 'Cyclosporin',
 'Dexamethason + framycetin',
 'Dexpanthenol',
 'Dinatri inosin monophosphat',
 'FluoromethoIon',
 'Glycerin',
 'Hexamidine di-isetionat',
 'Hyaluronidase',
 'Hydroxypropylmethylcellulose',
 'Kali iodid + natri iodid',
 'Latanoprost',
 'Latanoprost + Timolol maleat',
 'Loteprednol etabonat',
 'Moxifloxacin + dexamethason',
 'Natri carboxymethylcellulose (natri CMC)',
 'Natri carboxymethylcellulose + glycerin',
 'Natri diquafosol',
 'Natri hyaluronat',
 'Nepafenac',
 'Olopatadin hydroclorid',
 'Pemirolast kali',
 'Pilocarpin',
 'Pirenoxin',
 'Polyethylen glycol + propylen glycol',
 'Ranibizumab',
 'Tafluprost',
 'Tetracain',
 'Tetryzolin',
 'Timolol',
 'Travoprost',
 'Travoprost + timolol',
 'Tropicamid',
 'Tropicamide + phenylephrine hydroclorid',
 'Betahistin',
 'Fluticason furoat',
 'Fluticason propionat',
 'Naphazolin',
 'Natri borat',
 'Phenazon + lidocain hydroclorid',
 'Rifamycin',
 'Tixocortol pivalat',
 'Triprolidin hydroclorid + pseudoephedrin',
 'Tyrothricin + benzocain+ benzalkonium',
 'Xylometazolin',
 'Carbetocin',
 'Carboprost tromethamin',
 'Dinoproston',
 'Levonorgestrel',
 'Methyl ergometrin maleat',
 'Oxytocin',
 'Ergometrin (hydrogen maleat)',
 'Misoprostol',
 'Atosiban',
 'Papaverin',
 'Salbutamol sulfat',
 'Dung dịch lọc màng bụng',
 'Dung dịch lọc máu dùng trong thận nhân tạo (bicarbonat hoặc acetat)',
 'Dung dịch lọc máu liên tục (có hoặc không có chống đông bằng citrat; có hoặc không có chứa lactat)',
 'Bromazepam',
 'Clorazepat',
 'Etifoxin chlohydrat',
 'Hydroxyzin',
 'Lorazepam',
 'Rotundin',
 'Zolpidem',
 'Zopiclon',
 'Acid thioctic (Meglumin thioctat)',
 'Alprazolam',
 'Amisulprid',
 'Clorpromazin',
 'Clozapin',
 'Clonazepam',
 'Donepezil',
 'Flupentixol',
 'Fluphenazin decanoat',
 'Haloperidol',
 'Levomepromazin',
 'Levosulpirid',
 'Meclophenoxat',
 'Olanzapin',
 'Quetiapin',
 'Risperidon',
 'Sulpirid',
 'Thioridazin',
 'Tofisopam',
 'Ziprasidon',
 'Zuclopenthixol',
 'Amitriptylin hydroclorid',
 'Citalopram',
 'Clomipramin',
 'Fluoxetin',
 'Fluvoxamin',
 'Methylphenidate hydrochloride',
 'Mirtazapin',
 'Paroxetin',
 'Sertralin',
 'Tianeptin',
 'Venlafaxin',
 'Acetyl leucin',

In [52]:
data['hoatchat'].unique().tolist()

['Acarbose',
 'Aceclofenac',
 'Acenocoumarol',
 'Paracetamol',
 'Acetaminophen',
 'Paracetamol (acetaminophen)',
 'Acetazolamid',
 'Acetyl leucin',
 'Acetyl leucine',
 'Acetylcystein',
 'Acetylcysteine',
 'Acetylsalicylic acid',
 'Acetylsalicylic acid (DL-lysin-acetylsalicylat)',
 'Acetylsalicylic Acid',
 'Acetylsalicylic acid+ clopidogrel',
 'Acetylsalicylic acid + clopidogrel',
 'Acid amin + glucose + điện giải',
 'Acid amin + glucose+ điện giải (*)',
 'Acid amin + glucose + lipid (*)',
 'Acid amin + glucose + lipid',
 'Acid amin',
 'Acid amin*',
 'Aciclovir',
 'Acyclovir',
 'Vitamin C',
 'Fusidic acid',
 'Acid Fusidic',
 'Fusidic acid + betamethason',
 'Fusidic acid 2% (w/w) + Betamethasone',
 'Fusidic acid + Betamethason',
 'Fusidic acid + hydrocortison',
 'Folic acid',
 'Acid folic (vitamin B9)',
 'Acid folinic',
 'Calci folinat',
 'Gadoteric acid',
 'Acid gadoteric',
 'Salicylic acid + betamethason dipropionat',
 'Salicylic acid + Betamethason dipropionat',
 'Acid salicylic + Betamethason dipropionat',
 'Acid thioctic (Meglumin thioctat)',
 'Tranexamic acid',
 'Acid tranexamic',
 'Mỗi 5ml dung dịch chứa: Acid tranexamic 250mg',
 'Acitretin',
 'Adalimumab',
 'Adenosine',
 'Adenosin triphosphat',
 'Adrenalin',
 'Epinephrin (adrenalin)',
 'Epinephrin',
 'Aescinat natri',
 'Aescin',
 'Albendazol',
 'Albumin người',
 'Human Albumin',
 'Albumin',
 'Protein huyết tương trong đó albumin tối thiểu 95%',
 'Alendronic acid (dưới dạng Natri alendronat trihydrat)',
 'Alfuzosin',
 'Alfuzosin HCL',
 'Alfuzosin hydroclorid',
 'Alfuzosin HCl',
 'Alimemazin',
 'Alimemazin tartrat',
 'Alimemazin (dưới dạng Alimemazin tartrat)',
 'Allopurinol',
 'Alpha chymotrypsin',
 'Alphachymotrypsine (tương đương alphachymotrypsine 21 microkatal)',
 'Chymotrypsin',
 'Alphachymotrypsin',
 'Alteplase',
 'Aluminum phosphat',
 'Alverin (citrat) + simethicon',
 'Alverin citrat + simethicon',
 'Simethicone + Alverine citrate',
 'Alverine citrate + Simethicone',
 'Alverin citrat',
 'Alverin (citrat)',
 'Ambroxol',
 'Ambroxol hydroclorid',
 'Ambroxol HCl',
 'Ambroxol hydrochlorid',
 'Ambroxol HCL',
 'Ambroxol (dưới dạng Ambroxol HCl)',
 'Amikacin',
 'Amikacin*',
 'Amikacin (dưới dạng Amikacin sulphat)',
 'Amikacin (dưới dạng Amikacin sulfate 667,5mg)',
 'Amikacin ( dưới dạng Amikacin sulfat)',
 'Aminophylin',
 'Theophylin-ethylendiamin',
 'Amiodaron hydroclorid',
 'Amiodaron (hydroclorid)',
 'Amiodarone hydrochloride',
 'Amisulprid',
 'Amitriptylin hydroclorid',
 'Amitriptylin (hydroclorid)',
 'Amlodipin + atorvastatin',
 'Amlodipin + Atorvastatin',
 'Amlodipin+ atorvastatin',
 'Amlodipin (dưới dạng Amlodipin besilat) 5mg + Atorvastatin (dưới dạng Atorvastatin calci trihydrat) 10mg',
 'Amlodipin + indapamid + perindopril',
 'Amlodipine +  Indapamide + Perindopril arginine',
 'Perindopril Arginine; Indapamide ; Amlodipine (dưới dạng Amlodipine besylate);',
 'Amlodipin + indapamid',
 'Amlodipine + Indapamide',
 'Amlodipine+ indapamide',
 'Amlodipin + lisinopril',
 'Amlodipine + Lisinopril',
 'Amlodipine (dưới dạng Amlodipine besilate) + Lisinopril (dưới dạng Lisinopril dihydrat)',
 'Amlodipin+ lisinopril',
 'Amlodipin + losartan',
 'Losartan Kali + Amlodipine (dưới dạng Amlodipine besilate)',
 'Amlodipine (dưới dạng Amlodipine besilate) + Losartan kali',
 'Amlodipin+ losartan',
 'Amlodipine (dưới dạng Amlodipine besilate ) + Losartan kali',
 'Telmisartan + Amlodipine (dưới dạng Amlodipine besilate 6,935mg)',
 'Amlodipin + telmisartan',
 'Telmisartan 40mg + Amlodipine besilate tương đương với Amlodipine 5mg',
 'Telmisartan + Amlodipine',
 'Telmisartan + Amlodipine (dưới dạng Amlodipine besilat 6,935mg)',
 'Amlodipin + valsartan + hydrochlorothiazid',
 'Amlodipin + valsartan',
 'Amlodipine + Valsartan',
 'Amlodipin + Valsartan',
 'Amlodipin (dưới dạng amlodipin besilat) + valsartan',
 'Amlodipin (dưới dạng Amlodipin besylat) + Valsartan',
 'Amlodipin',
 'Amlodipin (dưới dạng Amlodipin besylate) 5mg',
 'Amlodipin (dưới dạng Amlodipin besilat)',
 'Amlodipin (dưới dạng Amlodipin besylat)',
 'Amoxicilin + acid clavulanic',
 'Amoxicilin (dưới dạng Amoxicilin trihydrat compacted) + Acid Clavulanic (dưới dạng Kali Clavulanat - Avicel (1:1))',
 'Amoxicilin + Acid clavulanic',
 'Amoxicilin  + Acid clavulanic',
 'Amoxicilin (dưới dạng amoxicilin natri)+ Acid clavulanic (dưới dạng Kali clavulanat)',
 'Amoxicilin \n+ Acid clavulanic',
 'Amoxicilin (dưới dạng amoxicilin trihydrat)\n+ Acid clavulanic (dưới\ndạng kali clavulanat; avicel (1 :1))',
 'Amoxicilin (dùng dạng amoxicilin trihydrat)\n+ Acid clavulanic (dùng\ndạng kali clavulanat; avicel (1 :1))',
 'Amoxicilin (Dưới dạng Amoxillin trihydrate)+\xa0acid\xa0clavulanic (Dưới dạng Kali clavulanat)',
 'Amoxicilin\nAcid clavulanic',
 'Amoxicilin + sulbactam',
 'Amoxicilin',
 'Amoxicilin (dưới dạng Amoxicilin trihydrat compacted)',
 'Amoxicillin',
 'Amoxicillin (dưới dạng Amoxicillin trihydrat compacted) 500mg',
 'Amoxicilin (dưới dạng Amoxicilin trihydrat)',
 'Amoxicilin (dưói dạng Amoxicilin trihydrat)',
 'Amoxicilin (dưới dạng Amoxicillin trihydrat)',
 'Amoxicillin (dưới dạng Amoxicillin trihydrat compacted)',
 'Amoxicillin (dưới dạng Amoxicillin trihydrat compacted 500mg)',
 'Amoxicillin (dưới dạng Amoxicillin trihydrat)',
 'Amoxicilin (dưới dạng amoxicilin trihydrat comacted) 500mg',
 'Amoxicilin (dưói dang Amoxicilin trihydrat)',
 'Amoxicillin (dưới dạng Amoxicillin trihydrate) 500mg',
 'Ampicilin + sulbactam',
 'Sultamicillin (Ampicilin + sulbactam)',
 'Ampicilin + Sulbactam',
 'Ampicillin (dưới dạng Ampicillin natri) + Sulbactam (dưới dạng Sulbactam natri)',
 'Sultamicillin',
 'Ampicilin (dưới dạng Ampicilin natri) + Sulbactam (dưới dạng Sulbactam natri)',
 'Ampicilin (muối natri)',
 'Ampicilin (dưới dạng Ampicilin natri)',
 'Amylase + lipase + protease',
 'Pancreatin 170mg (tương ứng với Protease 238IU, Lipase 3400IU, Amylase 4080IU)',
 'Anastrozol',
 'Apixaban',
 'Atenolol',
 'Atorvastatin + ezetimibe',
 'Atorvastatin (dưới dạng Atorvastatin calcium trihydrate) + Ezetimibe',
 'Atorvastatin (dưới dạng Atorvastatin calci) 20mg + Ezetimibe 10mg',
 'Atorvastatin',
 'Atorvastatin (dưới dạng Atorvastatin calci trihydrat)',
 'Atorvastatin (dưới dạng Atorvastatin calci)',
 'Atorvastatin (dưới dạng Atorvastatin calcium)',
 'Atosiban',
 'Atracurium besylat',
 'Atropin sulfat',
 'Atropin (sulfat)',
 'Attapulgit mormoiron hoạt hóa + hỗn hợp magnesi carbonat-nhôm hydroxyd',
 'Attapulgit mormoiron hoạt hoá + Hỗn hợp gel khô magnesi carbonat và nhôm hydroxyd',
 'Attapulgit hoạt tính + Magnesi carbonat + Nhôm hydroxyd',
 'Attapulgit mormoiron hoạt hóa',
 'Azithromycin',
 'Bacillus clausii',
 'Bacillus claussii',
 'Gói 1g chứa: Bào tử kháng đa kháng sinh Bacillus clausii 1 x 109 – 2 x 109 CFU',
 'Bacillus subtilis',
 'Baclofen',
 'Bambuterol',
 'Bambuterol hydrochloride',
 'Beclometason (dipropionat)',
 'Benazepril hydroclorid',
 'Benzylpenicilin',
 'Berberin (hydroclorid)',
 'Berberin clorid',
 'Betahistin',
 'Betahistin dihydrochlorid',
 'Betahistine dihydrochloride',
 'Betahistin.2HCl',
 'Betahistin dihydroclorid',
 'Betahistine.2HCL',
 'Betahistine\ndihydrochloride\n24mg',
 'Betamethason dipropionat + clotrimazol + gentamicin',
 'Betamethasone + dexchlorpheniramin',
 'Betamethason dipropionat 19,2mg',
 'Betamethason',
 'Betamethason dipropionat',
 'Betamethasone (Betamethasone dipropionate), Betamethasone (dưới dạng Betamethasone disodium phosphate)',
 'Bevacizumab',
 'Bezafibrat',
 'Bicalutamid',
 'Bilastine',
 'Bimatoprost',
 'Bisacodyl',
 'Bismuth subsalicylate',
 'Bismuth',
 'Bismuth subsalicylat',
 'Bismuth tripotassium dicitrate (tương đương Bismuth trioxid 120mg)',
 'Bismuth trioxid (dưới dạng bismuth subcitrat dạng keo)',
 'Bisoprolol fumarat + Hydrochlorothiazid',
 'Bisoprolol + hydroclorothiazid',
 'Bisoprolol fumarat + hydroclorothiazid',
 'Bisoprolol',
 'Bisoprolol fumarat',
 'Bisoprolol Fumarat',
 'Bisoprolol fumarate',
 'Bleomycin',
 'Botulinum toxin',
 'Brimonidine tartrate + Timolol',
 'Brimonidin tartrat + timolol',
 'Brimonidin tartrat',
 'Brinzolamid + timolol',
 'Brinzolamid',
 'Brinzolamide',
 'Bromfenac',
 'Bromhexin (hydroclorid)',
 'Bromhexin hydroclorid',
 'Bromhexin hydrochlorid',
 'Bromhexin \nhydroclorid',
 'Budesonid + formoterol',
 'Budesonid +Formoterol fumarate dihydrate',
 'Mỗi liều hít chứa Budesonide 200mcg + Formoterol fumarat dihydrat 6mcg',
 'Budesonid + Formoterol fumarate dihydrate',
 'Budesonid',
 'Budesonide',
 'Mỗi lọ 2ml chứa Budesonid 0.5mg',
 'Bupivacain hydroclorid',
 'Bupivacaine hydrochloride',
 'Magnesi hydroxyd + nhôm hydroxyd + simethicon',
 'Nhôm hydroxyd + Magnesi hydroxyd + Simethicon',
 'Magnesi hydroxyd + Nhôm hydroxyd + simethicon',
 'Mỗi 10 ml hỗn dịch chứa: Nhôm hydroxyd gel khô (tương đương Nhôm hydroxyd) + Magnesi hydroxyd (dưới dạng magnesi hydroxyd paste 30% 1.333,34 mg) + Simethicon (dưới dạng simethicon emulsion 30% 166,66mg)',
 'Magnesi hydroxyd + Nhôm hydroxyd + Simethicon',
 'Magnesi hydroxyd (dưới dạng Magnesi hydroxyd 30% paste) + nhôm hydroxyd (dưới dạng Nhôm Hydroxyd gel) + simethicon (dưới dạng Simethicon 30% emulsion)',
 'Hydroxyd nhôm + Magnesi hydroxyd +  Simethicon',
 'Bột dập thẳng Codried (chứa Nhôm hydroxyd 306mg tương đương với Nhôm oxyd 200mg + magnesi hydroxyd 400 mg) + Bột simethicon 70% (tương đương với simethicon 30mg)',
 'Magnesi hydroxyd + nhôm hydroxyd',
 'Magnesi hydroxyd + Nhôm hydroxyd gel khô',
 'Mỗi 10ml chứa: Nhôm hydroxyd (dưới dạng nhôm hydroxyd gel khô) + Magnesi hydroxyd (dưới dạng Magnesi hydroxyd paste 30%)',
 'Cafein (citrat)',
 'Cafein citrat',
 'Calci carbonat + vitamin D3',
 'Calci carbonat (tương ứng với 300 mg calci) + Vitamin D3',
 'Calci carbonat+ calci gluconolactat',
 'Calci carbonat + calci gluconolactat',
 'Calci carbonat + Calci lactat gluconat',
 'Calci carbonat',
 'Ringer lactat',
 'Calci clorid.2H20 0,135g; Kali clorid 0,2g; Natri clorid 3g; Natri lactat 1,6g',
 'Calcium chloride dihydrate',
 'Calci gluconat',
 'Calci glycerophosphat + magnesi gluconat',
 'Calci glycerophosphat+ magnesi gluconat',
 'Calci glycerophosphat + Magnesi gluconat',
 'Calci lactat',
 'Calcium lactate pentahydrate',
 'Calci lactat pentahydrat',
 'Calci lactat (dưới dạng Calci lactat pentahydrat) 300 mg',
 'Calcipotriol + betamethason dipropionat',
 'Calcipotriol',
 'Calcitonin',
 'Calcitriol',
 'Candesartan + hydrochlorothiazid',
 'Candesartan cilexetil + Hydroclorothiazid',
 'Candesartan + Hydroclorothiazid',
 'Candesartan cilexetil + Hydrochlorothiazide',
 'Candesartan Cilexetil + Hydrochlorothiazid',
 'Candesartan Cilexetil; Hydrochlorothiazid',
 'Candesartan',
 'Candesartan cilexetil',
 'Candesartan Cilexetil',
 'Cao ginkgo biloba + heptaminol clohydrat + troxerutin',
 'Cao ginkgo biloba+ heptaminol clohydrat+ troxerutin',
 'Ginkgo biloba',
 'Cao ginkgo biloba',
 'Cao khô lá bạch quả đã chuẩn hóa [Ginkgonis extractum siccum raffinatum et quantificatum] (39,6 - 49,5:1)',
 'Cao ginkgo biloba (Dưới dạng ginkgo biloba phytosome)',
 'Capsaicin',
 'Captopril+ hydroclorothiazid',
 'Captopril + hydroclorothiazid',
 'Captopril + Hydroclorothiazid',
 'Captopril',
 'Carbamazepin',
 'Carbazochrom natri sulfonat',
 'Carbazochrom',
 'Carbetocin',
 'Carbimazol',
 'Carbocistein + promethazin',
 'Carbocistein',
 'Carbomer',
 'Carboplatin',
 'Carboprost tromethamin',
 'Carvedilol',
 'Caspofungin*',
 'Cefaclor',
 'Cefaclor (dưới dạng Cefaclor monohydrate)',
 'Cefaclor (dưới dạng cefaclor monohydrat)',
 'Cefaclor (dưới dạng Cefaclor monohydrat)',
 'Cefadroxil',
 'Cefadroxil (dưới dạng Cefadroxil monohydrat)',
 'Cefadroxil\n(dưới dạng Cefadroxil monohydrat)',
 'Cefalexin',
 'Cefalothin',
 'Cefamandol',
 'Cefazolin',
 'Cefazolin (dưới dạng cefazolin natri)',
 'Cefazolin (dưới dạng Cefazolin natri)',
 'Cefdinir',
 'Cefepim',
 'Cefepim (dưới dạng Cefepim hydroclorid phối hợp với L-arginin tỷ lệ 1:0,725)',
 'Cefixim',
 'Cefixim (dưới dạng cefixim trihydrat)',
 'Cefixime (dưới dạng cefixime trihydrate)',
 'Cefmetazol',
 'Cefmetazol (dưới dạng Cefmetazol natri)',
 'Cefoperazon + sulbactam*',
 'Cefoperazon + Sulbactam',
 'Cefoperazon (dưới dạng hỗn hợp bột vô khuẩn cefoperazon natri và sulbactam natri tỷ lệ (2:1)) 1g + Sulbactam (dưới dạng hỗn hợp bột vô khuẩn cefoperazon natri và sulbactam natri tỷ lệ (2:1)) 0,5g',
 'Cefoperazon + sulbactam',
 'Cefoperazone sodium và sulbactam sodium vô trùng tương đương cefoperazone và sulbactam 1g : 1g',
 'Cefoperazon',
 'Cefoperazon*',
 'Cefoperazon (dưới dạng cefoperazon natri)',
 'Cefoperazon (dưới dạng Cefoperazon natri)',
 'Cefotaxim',
 'Cefotaxim (dưới dạng cefotaxim sodium)',
 'Cefotaxime (dưới dạng Cefotaxim natri)',
 'Cefotaxim (dưới dạng cefotaxim natri)',
 'Cefotiam',
 'Cefotiam*',
 'Cefoxitin',
 'Cefoxitin (dưới dạng cefoxitin natri)',
 'Cefoxitin (dưới dạng Cefoxitin natri)',
 'Cefpirom',
 'Cefpodoxim',
 'Cefpodoxim (dưới dạng Cefpodoxim proxetil)',
 'Cefpodoxim proxetil',
 'Cefradin',
 'Ceftazidim',
 'Ceftizoxim',
 'Ceftriaxon',
 'Ceftriaxon (dưới dạng Ceftriaxon natri)',
 'Ceftriaxone (dưới dạng Ceftriaxone natri)',
 'Ceftriaxone (dưới dạng ceftriaxone sodium)',
 'Ceftriaxon*',
 'Ceftriaxone (dưới dạng Ceftriaxone sodium)',
 'Cefuroxim',
 'Cefuroxim (dưới dạng cefuroxim natri)',
 'Cefuroxim (dưới dạng cefuroxim axetil)',
 'Cefuroxim (dưới dạng Cefuroxim axetil)',
 'Cefuroxim (dưới\ndạng Cefuroxim\naxetil)',
 'Cefuroxim\n(dưới dạng Cefuroxim axetil)',
 'Celecoxib',
 'Cetirizin',
 'Cetirizine hydrochloride',
 'Cetirizin dihydroclorid',
 'Chlorpheniramin + dextromethorphan',
 'Chlorpheniramin (hydrogen maleat)',
 'Chlorpheniramin',
 'Chlorpheniramine maleat',
 'Clorpheniramin maleat',
 'Clorpromazin (hydroclorid)',
 'Chlorpromazine hydrochloride',
 'Clorpromazin hydroclorid',
 'Clorpromazin',
 'Choline Alfoscerate',
 'Choline alfoscerat',
 'Ciclopiroxolamin',
 'Ciclosporin',
 'Cyclosporin',
 'Cilnidipin',
 'Cilostazol',
 'Cimetidin',
 'Cimetidine',
 'Cinnarizin',
 'Cinnarizine',
 'Ciprofibrat',
 'Ciprofloxacin',
 'Ciprofloxacin (dưới dạng ciprofloxacin HCl)',
 'Ciprofloxacin (dưới dạng ciprofloxacin hydroclorid monohydrat)',
 'Ciprofloxacin \n(dùng dạng ciprofloxacin\nhydroclorid)',
 'Ciprofloxacin (dưới dạng Ciprofloxacin hydrochlorid)',
 'Ciprofloxacin (dưới dạng Ciprofloxacin hydrochloride)',
 'Cisplatin',
 'Citalopram',
 'Citicolin',
 'Citicolin (dưới dạng Citicolin natri)',
 'Clarithromycin',
 'Clindamycin',
 'Clindamycin (dưới dạng clindamycin hydrochlorid)',
 'Clindamycin (dưới dạng clindamycin phosphat)',
 'Clindamycin (dưới dạng Clindamycin HCl)',
 'Clobetasol propionat micronised 0,05 % (w/w)',
 'Clobetasol propionat',
 'Clopidogrel',
 'Clopidogrel (dưới dạng Clopidogrel bisulfat)',
 'Clotrimazol + betamethason',
 'Clotrimazol',
 'Clotrimazole',
 'Cloxacilin',
 'Cloxacilin (dưới dạng Cloxacilin natri)',
 'Clozapin',
 'Clozapine',
 'Codein camphosulphonat+ sulfoguaiacol + cao mềm Grindelia',
 'Codein + terpin hydrat',
 'Terpin hydrat + Codein phosphat',
 'Codein phosphat + Terpin hydrat',
 'Codein phosphat (dưới dạng Codein phosphat hemihydrat) 10mg ; Terpin hydrat 100mg',
 'Colchicin',
 'Colchicine',
 'Colistimethat natri',
 'Colistin',
 'Colistin*',
 'Crotamiton',
 'Cyanocobalamin',
 'Cyclophosphamide',
 'Cyclophosphamid',
 'Cytidin-5monophosphat disodium + uridin',
 'Cytidin monophosphat disodium + Uridin monophasphat disodium',
 'Cytidin-5monophosphat disodium + Uridin monophosphat disodium',
 'Cồn 70°',
 'Cồn boric',
 'Cồn A.S.A',
 'Cồn BSI',
 'D-Mannitol',
 'Dabigatran',
 'Dapagliflozin',
 'Dapagliflozin (dưới dạng dapagliflozin propanediol monohydrat)',
 'Dapagliflozin (dưới dạng Dapagliflozin propanediol monohydrat)',
 'Daptomycin*',
 'Deferasirox',
 'Deferipron',
 'Deferoxamin',
 'Dequalinium clorid',
 'Desflurane',
 'Desloratadin',
 'Desmopressin acetat',
 'Desmopressin',
 'Mỗi 5ml chứa:Dexamethasonphosphat 5mg + Moxifloxacin 25mg',
 'Mỗi 5ml chứa: Dexamethason phosphat 5mg + Moxifloxacin 25mg',
 'Moxifloxacin + dexamethason',
 'Neomycin + polymyxin B + dexamethason',
 'Mỗi 10ml chứa: Dexamethason (dưới dạng dexamethason natri phosphat) + Neomycin (dưới dạng neomycin sulfat) + Polymyxin B sulfat',
 'Mỗi 100ml chứa: Neomycin sulphat + Polymycin B sulphat + Dexamethason natri metasulfobenzoat',
 'Dexamethason + Neomycin + Polymyxin B sulfat',
 'Mỗi 1ml chứa: Dexamethason + Neomycin sulfat + Polymyxin B sulfat',
 'Neomycin sulfat + Polymycin B sulfat + Dexamethason',
 'Dexamethason (dưới dạng dexamethason natri phosphat) + Neomycin (dưới dạng neomycin sulfat) + Polymyxin B sulfat',
 'Tobramycin + dexamethason',
 'Tobramycin + Dexamethasone',
 'Tobramycin + dexamethason natri phosphat',
 'Tobramycin (dưới dạng Tobramycin sulfat) + Dexamethason natri phosphat',
 'Dexamethason',
 'Dexamethason (dưới dạng Dexamethason Natri phosphat) 2mg',
 'Dexamethason phosphat (dưới dạng Dexamethason natri phosphat)',
 'Dexamethason phosphat',
 'Dexchlorpheniramin',
 'Dexclorpheniramin maleat',
 'Dexibuprofen',
 'Dexpanthenol (panthenol, vitamin B5)',
 'Dexpanthenol',
 'Vitamin B5',
 'Dextran 40',
 'Dextromethorphan',
 'Dextromethorphan hydrobromid',
 'Dextromethorphan hydrobromid 15mg',
 'Diacerein',
 'Diazepam',
 'Dibencozid',
 'Diclofenac',
 'Diclofenac Natri',
 'Diclofenac natri',
 'Diethylphtalat',
 'Digoxin',
 'Dihydro ergotamin mesylat',
 'Diltiazem',
 'Diltiazem hydroclorid',
 'Dimenhydrinat',
 'Dimenhydrinate',
 'Dinoproston',
 'Diosmectit',
 'Dioctahedral smectit',
 'Mỗi gói 20ml chứa: Dioctahedral smectit',
 'Diosmectite',
 'Diosmin + hesperidin',
 'Diosmin + Hesperidin',
 'Phân đoạn flavonoid vi hạt tinh chế tương ứng với: Diosmin +\ncác flavonoid biểu thị bằng hesperidin',
 'Diosmin',
 'Diphenhydramin',
 'Diphenhydramin hydroclorid',
 'Diphenhydramin HCl',
 'Dobutamin',
 'Dobutamine (dưới dạng Dobutamine hydrochloride)',
 'Docetaxel',
 'Docusate sodium',
 'Docusate natri',
 'Dolutegravir (tương đương Dolutegravir natri 52,6mg) 50mg; Lamivudine 300mg; Tenofovir disoproxil fumarate (tương đương Tenofovir disoproxil 245mg) 300mg',
 'Domperidon',
 'Domperidone',
 'Domperidon (dưới dạng Domperidon maleat)',
 'Domperidon (dưới dạng Domperidone maleate)',
 'Donepezil',
 'Dopamin hydroclorid',
 'Doripenem*',
 'Doripenem',
 'Doripenem (dưới dạng Doripenem monohyrat)',
 'Doxazosin (dưới dạng Doxazosin mesylat)',
 'Doxazosin',
 'Doxorubicin Hydroclorid',
 'Doxorubicin hydroclorid',
 'Doxorubicin',
 'Doxycyclin',
 'Doxycyclin (dưới dạng Doxycyclin hyclat)',
 'Drotaverin clohydrat',
 'Drotaverin hydroclorid',
 'Drotaverine hydrochloride',
 'Drotaverin HCl',
 'Drotaverin',
 'Dung dịch lọc máu dùng trong thận nhân tạo (bicarbonat hoặc acetat)',
 'Dung dịch lọc máu liên tục (có hoặc không có chống đông bằng citrat; có hoặc không có chứa lactat)',
 'Dung dịch lọc màng bụng',
 'Dung dịch lọc máu liên tục',
 'Dung dịch lọc thận bicarbonathoặc acetat',
 'Dutasterid',
 'Dutasteride',
 'Dydrogesteron',
 'Dydrogesterone',
 'Ebastin',
 'Econazol natri',
 'Empagliflozin',
 'Enalapril + hydrochlorothiazid',
 'Enalapril maleate + Hydrochlorothiazide',
 'Enalapril maleat + hydrochlorothiazid',
 'Enalapril + Hydrochlorothiazid',
 'Enalapril  maleat + hydrochlorothiazid',
 'Enalapril maleate + Hydroclorothiazid',
 'Enalapril maleat + Hydrochlorothiazid',
 'Enalapril',
 'Enalapril maleate',
 'Enalapril maleat',
 'Enoxaparin (natri)',
 'Enoxaparin natri',
 'Entecavir',
 'Entecavir (dưới dạng Entecavir monohydrat)',
 'Entecavir (dưới dạng Entecavir monohydrate)',
 'Eperison',
 'Eperison hydroclorid',
 'Eperison hydrochlorid',
 'Ephedrin hydroclorid',
 'Ephedrin (hydroclorid)',
 'Ephedrin',
 'Eprazinon',
 'Erlotinib',
 'Ertapenem*',
 'Erythromycin',
 'Erythromycin (dưới dạng Erythromycin stearat)',
 'Erythropoietin',
 'Recombinant Human Erythropoietin alfa',
 'Esomeprazol',
 'Esomeprazole (dưới dạng esomeprazole (magnesium dihydrate) pellets 22%)',
 'Esomeprazol (dạng vi hạt bao tan trong ruột chứa Esomeprazole magnesium (dưới dạng Esomeprazole magnesium trihydrate) 22,5%)',
 'Esomeprazole (dưới dạng Esomeprazole magnesium pellets (dưới dạng esomeprazole magnesium trihydrate) 22,5%',

In [50]:
list(set(data['active_ingredient']) - set(drug_types['Tên hoạt chất']))

['Benazepril',
 'Estradiol',
 'Netilmicin',
 'Calci glycerophosphat + Magnesi gluconat',
 'Enzym tiêu hóa (Amylase + Lipase + Protease)',
 'Chlorpromazin',
 'Teicoplanin',
 'Enalapril + Hydroclorothiazid',
 'Dầu hạt thuốc phiện iod hóa',
 'Fluorouracil',
 'Ertapenem',
 'Palonosetron',
 'Otilonium bromid',
 'Cyanocobalamin (Vitamin B12)',
 'Sofosbuvir + Velpatasvir',
 'Tizanidin',
 'Acid tiaprofenic',
 'Acid thioctic',
 'Bạc sulfadiazin',
 'Rocuronium',
 'Acid amin + glucose + lipid',
 'Perindopril + Amlodipin',
 'Clopidogrel',
 'Doripenem',
 'Alphachymotrypsin',
 'Insulin Glargine',
 'Ampicilin + Sulbactam',
 'Paracetamol + Methocarbamol',
 'Brimonidin',
 'Travoprost + Timolol',
 'Levothyroxin',
 'Atracurium',
 'Sitagliptin + Metformin',
 'Amiodaron',
 'Dung dịch Natri clorid',
 'Acid alendronic',
 'Acid valproic / Natri valproat',
 'Lidocain',
 'Betamethason + Dexchlorpheniramin',
 'Beclometason',
 'Brinzolamid + Timolol',
 'Guaiazulen + Dimethicon',
 'Natri bicarbonat',
 'Verapamil',
 'Acid tranexamic',
 'Acid amin + glucose + điện giải',
 'Ampicilin',
 'Tiropramid',
 'Alverin',
 'Vitamin A + Vitamin D',
 'Phloroglucinol + Trimethylphloroglucinol',
 'Paracetamol + Diphenhydramin + Phenylephrin',
 'Budesonid + Formoterol',
 'Attapulgit + Magnesi carbonat + Nhôm hydroxyd',
 'Imipenem + Cilastatin',
 'Amlodipin + Indapamid',
 'Insulin người',
 'Trimebutin',
 'Cồn',
 'Vildagliptin + Metformin',
 'Valsartan + Hydroclorothiazid',
 'Rupatadin',
 'Ciclopirox',
 'Paracetamol + Ibuprofen',
 'Methylprednisolon',
 'Candesartan + Hydroclorothiazid',
 'Paracetamol + Chlorpheniramin',
 'Macrogol + Điện giải',
 'Cytidin + Uridin',
 'Lidocain + Prilocain',
 'Acid ursodeoxycholic',
 'Fructose 1,6-diphosphat',
 'Dihydroergotamin',
 'Acid gadoteric',
 'Propranolol',
 'Biotin (Vitamin H / B8)',
 'Flurbiprofen',
 'Dexamethason + Moxifloxacin',
 'Succinic acid + Hỗn hợp vitamin/nucleotid',
 'Docusat natri',
 'Tropicamid + Phenylephrin',
 'Ibuprofen + Codein',
 'Iobitridol',
 'Hydroxyurea',
 'Meclofenoxat',
 'Montelukast',
 'Betamethason + Clotrimazol + Gentamicin',
 'Etifoxin',
 'Magnesi lactat + Pyridoxin (Vitamin B6)',
 'Lamivudin + Tenofovir',
 'Paracetamol + Tramadol',
 'Fosfomycin',
 'Insulin analog',
 'Lidocain + Adrenalin',
 'Acid risedronic',
 'Paracetamol + Chlorpheniramin + Phenylephrin + Dextromethorphan',
 'Dextran',
 'Methylphenidat',
 'Sắt (nguyên chất / phức hợp đơn chất)',
 'Gelatin succinyl',
 'Acid salicylic + Betamethason dipropionat',
 'Codein + Sulfogaiacol + Grindelia',
 'Paracetamol + Chlorpheniramin + Phenylephrin',
 'Procain',
 'Immunoglobulin người',
 'Insulin Degludec',
 'Chlorpheniramin + Dextromethorphan',
 'Dung dịch bù nước và điện giải (Oresol)',
 'Isosorbid mononitrat',
 'Kẽm',
 'Proparacain',
 'Mebeverin',
 'Lipidosterol',
 'Dexamethason + Tobramycin',
 'Fusidic Acid + Betamethason',
 'Mometason + Acid salicylic',
 'Adrenalin',
 'Insulin Degludec + Insulin Aspart',
 'Sulfamethoxazol + Trimethoprim',
 'Glimepirid + Metformin',
 'Pyridoxin (Vitamin B6)',
 'Nhôm hydroxyd + Magnesi hydroxyd + Simethicon',
 'Amlodipin + Losartan',
 'Naproxen + Esomeprazol',
 'Bromhexin',
 'Lercanidipin',
 'Cerebrolysin',
 'Mycophenolat mofetil',
 'Clotrimazol + Betamethason',
 'Methylergometrin',
 'Tenofovir',
 'Amlodipin + Telmisartan',
 'Terbinafin',
 'Paracetamol',
 'Goserelin',
 'Sắt + Acid folic',
 'Salbutamol',
 'Bupivacain',
 'Heparin',
 'Tricalci phosphat',
 'Magnesi trisilicat + Nhôm hydroxyd',
 'Furosemid + Spironolacton',
 'Losartan + Hydroclorothiazid',
 'Nefopam',
 'Dopamin',
 'Amlodipin + Valsartan + Hydrochlorothiazid',
 'Cao Ginkgo biloba',
 'Fenoterol + Ipratropium bromid',
 'Pipecuronium',
 'Cao Ginkgo biloba + Heptaminol + Troxerutin',
 'Insulin Glulisine',
 'Phytomenadion (Vitamin K1)',
 'Amlodipin + Valsartan',
 'Khoáng chất đa lượng và vi lượng',
 'Amoxicilin + Sulbactam',
 'L-Ornithin L-Aspartat',
 'Amlodipin + Indapamid + Perindopril',
 'Polyethylen glycol + Propylen glycol',
 'Ticarcilin + Acid clavulanic',
 'Colistin',
 'Fluticason',
 'Metronidazol + Neomycin + Nystatin',
 'Vincristin',
 'Paracetamol + Diphenhydramin',
 'Propylthiouracil',
 'Acid amin',
 'Lisinopril + Hydroclorothiazid',
 'Neostigmin',
 'Amoxicilin + Acid clavulanic',
 'Bisoprolol + Hydroclorothiazid',
 'Olopatadin',
 'Fluorometholon',
 'Hydro peroxyd',
 'Levodopa + Carbidopa',
 'Amlodipin + Lisinopril',
 'Neomycin + Nystatin + Polymyxin B',
 'Saxagliptin + Metformin',
 'Calci lactat + Calci carbonat',
 'Indacaterol + Glycopyrronium',
 'Fusidic Acid',
 'Atorvastatin + Ezetimibe',
 'Isosorbid',
 'Attapulgit',
 'Carbocistein + Promethazin',
 'Carboprost',
 'Codein + Terpin hydrat',
 'Promethazin',
 'Povidon iod',
 'Amlodipin + Atorvastatin',
 'Nhôm phosphat',
 'Naloxon',
 'Indapamid + Perindopril',
 'Paracetamol + Codein',
 'Iopromid',
 'Caspofungin',
 'Acetylsalicylic acid',
 'Tretinoin + Erythromycin',
 'Fusidic Acid + Hydrocortison',
 'Glyceryl trinitrat',
 'Irbesartan + Hydroclorothiazid',
 'Gliclazid + Metformin',
 'Natri carboxymethylcellulose',
 'Insulin Lispro',
 'Meropenem',
 'Dung dịch lọc ngoài thận',
 'Amitriptylin',
 'Alverin + Simethicon',
 'Mometason',
 'Fenticonazol',
 'Acetaminophen',
 'Linezolid',
 'Diosmin + Hesperidin',
 'Mesalazin',
 'Dolutegravir + Lamivudin + Tenofovir',
 'Surfactant',
 'Telmisartan + Hydroclorothiazid',
 'Nicotinamid (Vitamin PP)',
 'Hỗn hợp Terpen (Pinene + Camphene + Cineol...)',
 'Dequalinium',
 'Trihexyphenidyl',
 'Calcipotriol + Betamethason',
 'Isosorbid dinitrat',
 'Dung dịch Ringer lactat',
 'Thiamin (Vitamin B1)',
 'Clobetasol',
 'Enoxaparin',
 'Granisetron',
 'Ezetimibe + Simvastatin',
 'Natri phosphat',
 'Sofosbuvir + Ledipasvir',
 'Nhôm hydroxyd + Magnesi hydroxyd',
 'Hydroxychloroquin',
 'Prednisolon',
 'Berberin',
 'Dung dịch đa điện giải',
 'Calci carbonat + Vitamin D3',
 'Magnesi aspartat + Kali aspartat',
 'Heptaminol',
 'Tamsulosin',
 'Spiramycin + Metronidazol',
 'Acid pamidronic',
 'Ropivacain',
 'Tetracyclin',
 'Acetylsalicylic acid + Clopidogre',
 'Ipratropium bromid + Salbutamol',
 'Polystyren sulfonat',
 'Loteprednol',
 'Iopamidol',
 'Pemirolast',
 'Drotaverin',
 'Hydroxypropyl methylcellulose',
 'Dexamethason + Neomycin + Polymyxin B',
 'Fluticason + Salmeterol',
 'Piperacilin + Tazobactam',
 'Noradrenalin',
 'Kali iodid + Natri iodid',
 'Brimonidin + Timolol',
 'Gadobenic acid',
 'Paracetamol + Phenylephrin + Dextromethorphan',
 'Suxamethonium',
 'Tigecyclin',
 'Calci folinat (folinic acid, leucovorin',
 'Chlorpheniramin',
 'Cefoperazon + Sulbactam',
 'Hydroxyethyl starch',
 'Captopril + Hydroclorothiazid',
 'Glibenclamid + Metformin',
 'Acid zoledronic',
 'Tyrothricin + Benzocain + Benzalkonium',
 'Methimazol',
 'Mannitol']