In [1]:
'''
Chỉnh working directory, k cần quan tâm lắm :))
'''

import sys
from pathlib import Path
# Add the project root directory (one level up from tests/)
sys.path.append(str(Path.cwd().parent))
import pandas as pd
import os

In [7]:
'''
Load các thư viện, function cần thiết.
    producer_config: cài đặt filter do chuyên viên nhập và điều chỉnh
    LoadMedicalData: class sử dụng để load, xử lý và tính toán
'''
%load_ext autoreload
%autoreload 2

from config.filter_config import config
from src.utils.data_loader import LoadMedicalData

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
'''
Đoạn này thử đưa một đoạn dữ liệu vào để load. Sau khi chạy xong thì dữ liệu raw sẽ được lưu trong 'test_data'. Người dùng có thể thực hiện filter hoặc tính tổng từ đây.
'''

test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls' # đưa PATH đến data ở đây. 
test_data = LoadMedicalData(
    test_path, 
    config=config,
    drug_types_path='../data/template/drug_type.xlsx'
)

c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:210: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = clean_series.str.contains(include_pat, na=False)
c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:212: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = cond & (~clean_series.str.contains(exclude_pat, na=False))

In [ ]:
# Hiện toàn bộ dữ liệu

test_data.show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.798,...,NaT,2025-05-15,NaT,NaT,None,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
1,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.798,...,NaT,2025-05-15,2025-05-15,2027-05-14,None,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
2,3.thau_rieng_le,40.798,Savi Acarbose 25,Acarbose,10,Tỉnh Lào Cai,Bvđk Khu Vực Văn Bàn-Lào Cai,10008,Bvđk Khu Vực Văn Bàn-Lào Cai,40.798,...,2027-05-16,2025-05-16,2025-05-16,2027-05-16,None,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
3,2.thau_tinh,40.798,Arbosnew 50,Acarbose,79,Thành phố Hồ Chí Minh,Thành phố Hồ Chí Minh,NaN,NaN,NaN,...,2026-12-31,NaT,NaT,NaT,None,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
4,2.thau_tinh,40.48,Gyoryg,Acarbose,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2027-04-11,NaT,NaT,NaT,None,Việt Nam,Acarbose,18. Hocmoon và các thuốc tác động vào hệ thống...,18.3. Insulin và nhóm thuốc hạ đường huyết,Acarbose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82679,3.thau_rieng_le,40.1057,SaVi C 500,Acid ascorbic 500 mg,10,Tỉnh Lào Cai,Pkđkkv Bản Khoang-Lào Cai,10053,Pkđkkv Bản Khoang-Lào Cai,40.1057,...,2026-04-03,2025-04-04,2025-04-04,2027-04-04,None,Việt Nam,None,NaN,NaN,NaN
82680,3.thau_rieng_le,40.1026.1,Ringer lactate,Mỗi 500ml chứa: Natri clorid 3g; Kali clorid 0...,42,Tỉnh Hà Tĩnh,Ttyt Thạch Hà,42008,Ttyt Thạch Hà,40.1026.1,...,NaT,2025-05-26,2025-05-26,2025-07-30,None,Việt Nam,None,NaN,NaN,NaN
82681,3.thau_rieng_le,40.1026.1,Ringer lactate,Mỗi 500ml chứa: Natri clorid 3g + Kali clorid ...,66,Tỉnh Đắk Lắk,Bv Phổi Đắklắk,66233,Bv Phổi Đắklắk,40.1026.1,...,NaT,2025-05-05,2025-05-05,2026-05-05,None,Việt Nam,None,NaN,NaN,NaN
82682,3.thau_rieng_le,40.1026.1,Ringer lactate,Mỗi 500ml chứa: Natri clorid 3g + Kali clorid ...,66,Tỉnh Đắk Lắk,Bv Phổi Đắklắk,66233,Bv Phổi Đắklắk,40.1026.1,...,NaT,2025-05-05,2025-05-05,2026-05-05,None,Việt Nam,None,NaN,NaN,NaN
82683,3.thau_rieng_le,40.1057,SaVi C 500,Acid ascorbic 500 mg,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.1057,...,2026-04-03,2025-04-04,2025-04-04,2027-04-04,None,Việt Nam,None,NaN,NaN,NaN

In [ ]:
# Lọc dữ liệu
### Filter theo nhà sx
test_data.filter(column='ticker', value='IMP').show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,2.thau_tinh,40.49,Cobimol,Paracetamol + chlorpheniramin,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,NaT,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
1,2.thau_tinh,40.30.66,Andol S,Paracetamol + Chlorpheniramin + Phenylephrin,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,NaT,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
2,2.thau_tinh,40.49,Cobimol,Paracetamol + chlorpheniramin,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,NaT,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
3,2.thau_tinh,40.30.66,Andol S,Paracetamol + Chlorpheniramin + Phenylephrin,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,NaT,NaT,NaT,IMP,Việt Nam,Paracetamol (acetaminophen),"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Paracetamol (acetaminophen)
4,2.thau_tinh,40.27,Aescinat natri 5 mg,Aescinat natri,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,NaT,NaT,NaT,IMP,Việt Nam,Aescin,"2. Thuốc giảm đau, hạ sốt, chống viêm không st...","2.1. Thuốc giảm đau, hạ sốt, chống viêm không ...",Aescin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1531,2.thau_tinh,40.196,"Ticarlinat 3,2 g",Ticarcilin + Acid clavulanic,52,Tỉnh Bình Định,Tỉnh Bình Định,NaN,NaN,NaN,...,2026-12-31,NaT,NaT,NaT,IMP,Việt Nam,Ticarcillin + acid clavulanic,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.1. Thuốc KS nhóm betalactam,Ticarcillin + acid clavulanic
1532,2.thau_tinh,40.196,"Ticarlinat 3,2 g",Ticarcilin + Acid clavulanic,52,Tỉnh Bình Định,Tỉnh Bình Định,NaN,NaN,NaN,...,2026-12-31,2025-04-15,NaT,NaT,IMP,Việt Nam,Ticarcillin + acid clavulanic,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.1. Thuốc KS nhóm betalactam,Ticarcillin + acid clavulanic
1533,3.thau_rieng_le,40.196,"Ticarlinat 1,6g",Ticarcillin + acid clavulanic,40,Tỉnh Nghệ An,Bvđk Kv Tây Bắc Nghệ An,40011,Bvđk Kv Tây Bắc Nghệ An,40.196,...,NaT,2025-05-06,2025-05-06,2027-05-06,IMP,Việt Nam,Ticarcillin + acid clavulanic,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.1. Thuốc KS nhóm betalactam,Ticarcillin + acid clavulanic
1534,3.thau_rieng_le,40.196,"Ticarlinat 3,2 g",Ticarcillin + acid clavulanic,01,Thành phố Hà Nội,Bvđk Đống Đa,01004,Bvđk Đống Đa,40.196,...,NaT,2025-04-03,2025-04-03,2026-04-02,IMP,Việt Nam,Ticarcillin + acid clavulanic,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.1. Thuốc KS nhóm betalactam,Ticarcillin + acid clavulanic
1535,3.thau_rieng_le,40.196,"Ticarlinat 3,2 g",Ticarcillin + acid clavulanic,01,Thành phố Hà Nội,Bvđk Đống Đa,01004,Bvđk Đống Đa,40.196,...,NaT,2025-04-03,2025-04-03,2026-04-02,IMP,Việt Nam,Ticarcillin + acid clavulanic,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.1. Thuốc KS nhóm betalactam,Ticarcillin + acid clavulanic

In [ ]:
### Filter theo quốc gia sản xuất
test_data.filter(column='country', value='Hoa Kỳ').show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,2.thau_tinh,40.455,Flexbumin 20%,Albumin người,24,Tỉnh Bắc Giang,Tỉnh Bắc Giang,NaN,NaN,NaN,...,2026-02-28,2025-05-30,NaT,NaT,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
1,2.thau_tinh,40.455,Albutein,Albumin người,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,2025-05-15,NaT,NaT,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
2,2.thau_tinh,40.455,Albutein,Albumin người,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,2026-11-15,NaT,NaT,NaT,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
3,3.thau_rieng_le,40.455,Albutein 20%,Albumin,26,Tỉnh Vĩnh Phúc,Pkđk Trực Thuộc Bv Sản-Nhi Tỉnh Vĩnh Phúc,26117,Pkđk Trực Thuộc Bv Sản-Nhi Tỉnh Vĩnh Phúc,40.455,...,NaT,2025-05-09,2025-05-09,2026-05-09,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
4,3.thau_rieng_le,40.455,Flexbumin 20%,Albumin người,02,Tỉnh Hà Giang,Bvđk Huyện Mèo Vạc,02012,Bvđk Huyện Mèo Vạc,40.455,...,NaT,2025-04-09,2025-04-09,2026-04-09,None,Hoa Kỳ,Albumin,11. Thuốc tác dụng với máu,11.3. Máu và chế phẩm máu,Albumin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,3.thau_rieng_le,40.22,Seaoflura,Sevofluran,40,Tỉnh Nghệ An,Bv Đại Học Y Khoa Vinh,40550,Bv Đại Học Y Khoa Vinh,40.22,...,NaT,2025-05-12,2025-05-12,2027-05-11,None,Hoa Kỳ,Sevofluran,"1. Gây tê, gây mê, giãn cơ",1.1. Thuốc gây tê gây mê,Sevofluran
166,3.thau_rieng_le,40.22,Seaoflura,Sevofluran,31,Thành phố Hải Phòng,Bv Nhi Hải Phòng,31032,Bv Nhi Hải Phòng,40.22,...,NaT,2025-04-09,2025-04-09,2025-09-08,None,Hoa Kỳ,Sevofluran,"1. Gây tê, gây mê, giãn cơ",1.1. Thuốc gây tê gây mê,Sevofluran
167,2.thau_tinh,40.30.144,Bridion,Sugammadex,75,Tỉnh Đồng Nai,Tỉnh Đồng Nai,NaN,NaN,NaN,...,2027-02-27,NaT,NaT,NaT,None,Hoa Kỳ,Sugammadex,4. Thuốc giải độc và các thuốc dùng trong trườ...,4. Thuốc giải độc và các thuốc dùng trong trườ...,Sugammadex
168,3.thau_rieng_le,40.30.144,Bridion,Sugammadex,01,Thành phố Hà Nội,Ct Bv Gtvt,01010,Ct Bv Gtvt,40.30.144,...,NaT,2025-04-26,2025-04-26,2026-04-25,None,Hoa Kỳ,Sugammadex,4. Thuốc giải độc và các thuốc dùng trong trườ...,4. Thuốc giải độc và các thuốc dùng trong trườ...,Sugammadex
169,3.thau_rieng_le,40.1004,Survanta,Surfactant (Phospholipid chiết xuất từ phổi bò),37,Tỉnh Ninh Bình,Bv Sản Nhi Tỉnh,37074,Bv Sản Nhi Tỉnh,40.1004,...,NaT,2025-05-20,2025-05-20,2025-06-20,None,Hoa Kỳ,Surfactant (Phospholipid chiết xuất từ phổi lợ...,25. Thuốc tác dụng trên đường hô hấp,25.3. Thuốc khác,Surfactant (Phospholipid chiết xuất từ phổi lợ...

In [30]:
### Filter theo loại thuốc
test_data.filter(
    column='Loại thuốc 1', 
    value='6. Thuốc điều trị ký sinh trùng, chống nhiễm khuẩn'
).filter(
    column='country',
    value='Hoa Kỳ'
).show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,denngay,congbo,tungay_hd,denngay_hd,ticker,country,active_ingredient,Loại thuốc 1,Loại thuốc 2,Tên hoạt chất
0,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,79,Thành phố Hồ Chí Minh,Bvđk Kv Củ Chi,79040,Bvđk Kv Củ Chi,40.232,...,NaT,2025-05-23,2025-05-23,2026-05-29,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.7. Thuốc KS nhóm quinolon,Moxifloxacin
1,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,79,Thành phố Hồ Chí Minh,Bvđk Kv Củ Chi,79040,Bvđk Kv Củ Chi,40.232,...,NaT,2025-05-23,2025-05-23,2026-05-29,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.6. (cont) Thuốc điều trị lao kháng thuốc,Moxifloxacin
2,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,79,Thành phố Hồ Chí Minh,Bvđk Tân Bình,79033,Bvđk Tân Bình,40.232,...,NaT,2025-04-15,2025-04-15,2026-04-28,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.7. Thuốc KS nhóm quinolon,Moxifloxacin
3,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,79,Thành phố Hồ Chí Minh,Bvđk Tân Bình,79033,Bvđk Tân Bình,40.232,...,NaT,2025-04-15,2025-04-15,2026-04-28,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.6. (cont) Thuốc điều trị lao kháng thuốc,Moxifloxacin
4,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,48,Thành phố Đà Nẵng,Bv Mắt Đà Nẵng,48009,Bv Mắt Đà Nẵng,40.232,...,NaT,2025-04-23,2025-04-23,2025-10-23,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.7. Thuốc KS nhóm quinolon,Moxifloxacin
5,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,48,Thành phố Đà Nẵng,Bv Mắt Đà Nẵng,48009,Bv Mắt Đà Nẵng,40.232,...,NaT,2025-04-23,2025-04-23,2025-10-23,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.6. (cont) Thuốc điều trị lao kháng thuốc,Moxifloxacin
6,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,40,Tỉnh Nghệ An,Bvđk Nghi Lộc,40009,Bvđk Nghi Lộc,40.232,...,NaT,2025-04-15,2025-04-15,2027-03-25,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.7. Thuốc KS nhóm quinolon,Moxifloxacin
7,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,40,Tỉnh Nghệ An,Bvđk Nghi Lộc,40009,Bvđk Nghi Lộc,40.232,...,NaT,2025-04-15,2025-04-15,2027-03-25,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.6. (cont) Thuốc điều trị lao kháng thuốc,Moxifloxacin
8,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,01,Thành phố Hà Nội,Ct Bv Gtvt,01010,Ct Bv Gtvt,40.232,...,NaT,2025-04-26,2025-04-26,2026-04-25,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.2.7. Thuốc KS nhóm quinolon,Moxifloxacin
9,3.thau_rieng_le,40.232,Vigamox,Moxifloxacin,01,Thành phố Hà Nội,Ct Bv Gtvt,01010,Ct Bv Gtvt,40.232,...,NaT,2025-04-26,2025-04-26,2026-04-25,None,Hoa Kỳ,Moxifloxacin,"6. Thuốc điều trị ký sinh trùng, chống nhiễm k...",6.6. (cont) Thuốc điều trị lao kháng thuốc,Moxifloxacin

In [32]:
# Tính giá trung bình theo nhóm
test_data.average(
    value_col='gia',
    groupby='Loại thuốc 2'
)

Loại thuốc 2
1.1. Thuốc gây tê gây mê                       1.788695e+05
10. Thuốc chống parkinson                      1.067775e+04
11.1. Thuốc chống thiếu máu                    9.507248e+02
11.2. Thuốc tác dụng lên quá trình đông máu    2.039030e+04
11.3. Máu và chế phẩm máu                      8.682206e+05
                                                   ...
8.1. Hóa chất                                  2.672811e+05
8.2. Thuốc điều trị đích                       2.964832e+06
8.3. Thuốc điều trị nội tiết                   1.173762e+06
8.4. Thuốc điều hòa miễn dịch                  4.892872e+04
9. Thuốc điều trị bệnh đường tiết niệu         7.181130e+03
Name: gia, Length: 78, dtype: float64

In [21]:
test_data.get_unmatched(config_type='ingred')

['Cephalexin',
 'Cephalexin (dưới \ndạng Cephalexin \nmonohydrat \ncompacted)',
 'Cephalexin (dưới dạng Cephalexin monohydrat)',
 'Natri clorid + Natri citrat dihydrat + Kali clorid + Glucose khan',
 'Natri clorid + natri citrat + kali clorid + glucose khan',
 'N-Acetyl DL-Leucin',
 'Glucose khan (dưới dạng glucose monohydrate) + Natri clorid + Kali clorid + Trinatri citrat khan (dưới dạng Trinatri citrat. 2H2O)',
 'Glucose khan + Natri clorid + Kali clorid + Tri Natricitrat dihydrat',
 'Irbersatan + hydroclorthiazid',
 'Acetylleucin (N-Acetyl-DL-Leucin)',
 'Isosorbid-5-mononitrat',
 'Paracetamol micronized',
 'Meclofenoxate hydroclorid',
 'Acid ascorbic 500 mg',
 'Natri clorid + Kali clorid + Natri lactat + Calci clorid.2H2O',
 'Acid Ascorbic',
 'N-acetyl-dl- leucin',
 'Calci 250mg dưới dạng (Calci lactat gluconat + calci carbonat)',
 'Mỗi 500ml chứa: Natri clorid 3g + Kali clorid 0,2g + Natri lactat 1,6g + Calci clorid.2H20 0,135g',
 'Mỗi 8ml chứa: Natri clorid 72mg',
 'N-Acetyl-DL-Leucin',
 'Mỗi 500ml chứa: Natri clorid 3g; Kali clorid 0,2g; Natri lactat 1,6g; Calci clorid.2H20 0,135g',
 'Acid amin + glucose + lipid + điện giải',
 'Acid amin + chất điện giải',
 'Mỗi gói 3g chứa: Acetylcystein 200mg',
 '100ml nhũ tương chứa: Dầu đậu nành tinh chế 6 gam + Triglycerid mạch trung bình 6 gam + Dầu ô-liu tinh chế 5 gam + Dầu cá tinh chế 3 gam',
 'Dầu đậu nành; Glycerol; Phospholipid từ trứng',
 'Dầu đậu nành tinh chế; triglycerid mạch trung bình; dầu oliu tinh chế; dầu cá tinh chế',
 'L-Alanin 1,575g + L-Arginin 1,225g + Amino-acetic acid (Glycin) 0,80g + L-Histidin 1,075g + L-Isoleucin 1,275g + L-Leucin 2,575g + L-Lysin monoacetat 2,5025g (tương đương 1,775g L-Lysin) + L-Methionin 0,70g + L-Phenylalanin 0,95g + L-Prolin 1,075g + L-Serin 1,125g + L-Threonin 1,20g + L-Tryptophan 0,475g + L-Valin 1,55g + Acetylcystein 0,125g (tương đương 0,0925g L-Cystein) + L-Malic acid 0,375g + Acid acetic 99% (acid acetic băng) 0,345g',
 'Mỗi 250ml nhũ tương chứa: Dầu đậu nành tinh chế 25g + Glycerol 6,25g + Phospholipid tinh chế từ trứng 1,5g',
 'Alanine + Arginine + Aspartic acid + Glutamic acid + Glycine + Histidine + Isoleucine + Leucine + Lysine (dưới dạng Lysine acetate) + Methionine + Phenylalanine + Proline + Serine + Threonine + Tryptophan + Tyrosine + Valine + Natri acetat trihydrat + Natri glycerophosphate hydrat + Kali clorid + Magnesi clorid hexahydrat + Calci clorid dihydrat + Glucose anhydrous + Dầu oliu tinh khiết và dầu đậu nành tinh khiết',
 'Acid ascorbic',
 'Acid amin + glucose + lipid + điện giải (*)',
 'Tropicamid + Phenylephrin hydroclorid',
 'Codein camphosulfonat + Sulfogaiacol + Cao mềm Grindelia',
 'Khoang A: Mỗi 1000ml chứa Calcium clorid dihydrat 5,145g + Magnesium clorid hexahydrat 2,033g + Acid lactic 5,4g; Khoang B: Mỗi 1000ml chứa Sodium Chlorid 6,45g + Sodium hydrogen carbonat 3,09g; Dung dịch sau khi phối hợp chứa: Calcium 1,75mmol/l + Magnesium 0,5mmol/l + Sodium 140mmol/l + Chlorid 109,5mmol/l + Lactat 3mmol/l + hydrogen carbonat 32mmol/l']

In [10]:
# Hiển thị toàn bộ dữ liệu raw
test_data.average(value_col='gia', groupby='Loại thuốc 1')

Loại thuốc 1
1. Gây tê, gây mê, giãn cơ                                                                         178869.486842
10. Thuốc chống parkinson                                                                           10677.750000
11. Thuốc tác dụng với máu                                                                          53259.311443
12. Thuốc tim mạch                                                                                  16522.228325
13. Thuốc điều trị bệnh da liễu                                                                     23617.532468
14. Thuốc dùng chẩn đoán                                                                           398754.421053
15. Thuốc tẩy trùng và sát khuẩn                                                                     7182.117647
16. Thuốc lợi tiểu                                                                                   1199.398990
17. Thuốc đường tiêu hóa                                                                             4540.172523
18. Hocmoon và các thuốc tác động vào hệ thống nội tiết                                              3445.608217
19. Huyết thanh và globulin miễn dịch                                                              180497.785714
2. Thuốc giảm đau, hạ sốt, chống viêm không steroid; thuốc điều trị gút và các bệnh xương khớp      11174.608661
20. Thuốc làm mềm cơ và ức chế cholinesterase                                                       11753.622607
21. Thuốc điều trị bệnh mắt, tai mũi họng                                                           19626.265731
22. Thuốc có tác dụng thúc đẻ, cầm máu sau đẻ và chống đẻ non                                      122507.114583
24. Thuốc chống rối loạn tâm thần và thuốc tác động lên hệ thần kinh                                 2715.740202
25. Thuốc tác dụng trên đường hô hấp                                                                86398.909898
26. Dung dịch điều chỉnh nước, điện giải, cân bằng acid-based và các dung dịch tiêm truyển khác      7810.703271
27. Khoáng chất và vitamin                                                                           1941.476740
3. Thuốc chống dị ứng và dùng trong các trường hợp quá mẫn                                           1378.263894
4. Thuốc giải độc và các thuốc dùng trong trường hợp ngộ độc                                        24540.394704
5. Thuốc chống co giật, chống động kinh                                                              3621.832061
6. Thuốc điều trị ký sinh trùng, chống nhiễm khuẩn                                                  17581.978947
7. Thuốc điều trị đau nửa đầu                                                                        1336.908046
8. Thuốc ung thư                                                                                   543868.988806
9. Thuốc điều trị bệnh đường tiết niệu                                                               7181.130435
Name: gia, dtype: float64

In [5]:
# Filter dữ liệu tùy theo config đưa vào
test_data.filter().show_data() # Nếu để trống phần filter sẽ trả về toàn bộ các mục mà được liệt kê trong config

c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:210: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = clean_series.str.contains(include_pat, na=False)
c:\Users\ducngh\OneDrive - fpts.com.vn\work\Dược\src\utils\data_loader.py:212: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond = cond & (~clean_series.str.contains(exclude_pat, na=False))

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd,active_ingredient
0,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,NaT,NaT,Acarbose
1,3.thau_rieng_le,40.798,SaVi Acarbose 25,Acarbose,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,Acarbose
2,3.thau_rieng_le,40.798,Savi Acarbose 25,Acarbose,10,Tỉnh Lào Cai,Bvđk Khu Vực Văn Bàn-Lào Cai,10008,Bvđk Khu Vực Văn Bàn-Lào Cai,40.798,...,None,1,1,2025-10-25 22:21:51,2025-05-16,2027-05-16,2025-05-16,2025-05-16,2027-05-16,Acarbose
3,2.thau_tinh,40.798,Arbosnew 50,Acarbose,79,Thành phố Hồ Chí Minh,Thành phố Hồ Chí Minh,NaN,NaN,NaN,...,None,1,1,2025-10-25 22:18:22,2025-04-01,2026-12-31,NaT,NaT,NaT,Acarbose
4,2.thau_tinh,40.48,Gyoryg,Acarbose,68,Tỉnh Lâm Đồng,Tỉnh Lâm Đồng,NaN,NaN,NaN,...,None,1,1,2025-10-25 22:18:22,2025-04-11,2027-04-11,NaT,NaT,NaT,Acarbose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39705,3.thau_rieng_le,40.1020,Manitol 20%,Manitol,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.1020,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2026-11-14,Manitol
39706,3.thau_rieng_le,40.1020,Manitol 20%,Manitol,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.1020,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2026-11-14,Manitol
39707,3.thau_rieng_le,40.1020,Mannitol,Manitol,83,Tỉnh Bến Tre,Bv Phổi Bến Tre,83040,Bv Phổi Bến Tre,40.1020,...,None,1,3,2025-10-25 22:21:51,2025-05-22,NaT,2025-05-22,2025-05-22,2026-02-20,Manitol
39708,3.thau_rieng_le,40.1020,Mannitol,Manitol,01,Thành phố Hà Nội,Bvđk Đống Đa,01004,Bvđk Đống Đa,40.1020,...,None,1,1,2025-10-25 22:21:51,2025-04-03,NaT,2025-04-03,2025-04-03,2026-04-02,Manitol
39709,3.thau_rieng_le,40.1020,Mannitol,Manitol,40,Tỉnh Nghệ An,Bv Đại Học Y Khoa Vinh,40550,Bv Đại Học Y Khoa Vinh,40.1020,...,None,1,1,2025-10-25 22:21:51,2025-05-12,NaT,2025-05-12,2025-05-12,2027-05-11,Manitol