In [ ]:
'''
Chỉnh working directory, k cần quan tâm lắm :))
'''

import sys
from pathlib import Path
# Add the project root directory (one level up from tests/)
sys.path.append(str(Path.cwd().parent))
import pandas as pd
import os

In [ ]:
'''
Load các thư viện, function cần thiết.
    producer_config: cài đặt filter do chuyên viên nhập và điều chỉnh
    LoadMedicalData: class sử dụng để load, xử lý và tính toán
'''
%load_ext autoreload
%autoreload 2

from config.filter_config import producer_config
from src.utils.data_loader import LoadMedicalData

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
'''
Đoạn này thử đưa một đoạn dữ liệu vào để load. Sau khi chạy xong thì dữ liệu raw sẽ được lưu trong 'test_data'. Người dùng có thể thực hiện filter hoặc tính tổng từ đây.
'''

test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls'
test_data = LoadMedicalData(
    test_path, 
    config=producer_config # Phần config này về sau sẽ cần mở rộng cho các dạng filter khác, hiện tại đang mới có filter dành cho 'nhasx'
)

In [26]:
# Hiển thị toàn bộ dữ liệu raw
test_data.show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,loai,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd
0,3.thau_rieng_le,40.162,SM.Cefadroxil 500,Cefadroxil,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.162,...,Tân dược,None,1,1,None,None,None,None,None,None
1,3.thau_rieng_le,40.883,"Natri Clorid 0,9%",Natri clorid,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,...,Tân dược,None,1,1,None,None,None,None,None,None
2,3.thau_rieng_le,40.883,"Natri Clorid 0,9%",Natri clorid,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,...,Tân dược,None,1,1,None,None,None,None,None,None
3,3.thau_rieng_le,40.512,SaVi Losartan 50,Losartan Kali,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.512,...,Tân dược,None,1,1,None,None,None,None,None,None
4,3.thau_rieng_le,40.883,"Natri Clorid 0,9%",Natri clorid,27,Tỉnh Bắc Ninh,Tyt An Bình,27112,Tyt An Bình,40.883,...,Tân dược,None,1,1,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41467,3.thau_rieng_le,40.219,Azicine 250mg,Azithromycin,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.219,...,Tân dược,None,1,1,None,None,None,None,None,None
41468,3.thau_rieng_le,40.521,Amlessa 4mg/10mg Tablets,Perindopril + amlodipin,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.521,...,Tân dược,None,1,1,None,None,None,None,None,None
41469,3.thau_rieng_le,40.609,Fucidin H,Fusidic acid + hydrocortison,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.609,...,Tân dược,None,1,1,None,None,None,None,None,None
41470,3.thau_rieng_le,40.609,Fucidin H,Fusidic acid + hydrocortison,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.609,...,Tân dược,None,1,1,None,None,None,None,None,None
41471,3.thau_rieng_le,笂Ѐ騖ʹ,Tobradex,Tobramycin + dexamethason,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.207,...,NaN,None,NaN,NaN,None,None,None,None,None,None

In [27]:
# Filter dữ liệu tùy theo config đưa vào
test_data.filter().show_data() # Nếu để trống phần filter sẽ trả về toàn bộ các mục mà được liệt kê trong config

KeyError: 'producer'

In [ ]:
# Filter ra một mục tùy chọn
test_data.filter(by='IMP').show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd,ticker
0,3.thau_rieng_le,40.158,"Nerusyn 1,5g",Ampicilin + sulbactam,11,Tỉnh Điện Biên,Ttyt Điện Biên Phủ,11002,Ttyt Điện Biên Phủ,40.158,...,None,1,1,None,None,None,None,None,None,IMP
1,3.thau_rieng_le,40.161,Imeclor 125,Cefaclor,60,Tỉnh Bình Thuận,Tyt Đa Mi,60097,Tyt Đa Mi,40.161,...,None,1,5,None,None,None,None,None,None,IMP
2,3.thau_rieng_le,40.162,Imedroxil 500mg,Cefadroxil,94,Tỉnh Sóc Trăng,Tyt Trường Khánh,94132,Tyt Trường Khánh,40.162,...,None,1,4,None,None,None,None,None,None,IMP
3,3.thau_rieng_le,40.169,Imexime 100,Cefixim,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.169,...,None,1,1,None,None,None,None,None,None,IMP
4,3.thau_rieng_le,40.155,"Amoxicillin 250 mg/ 31,25 mg",Amoxicilin + acid clavulanic,01,Thành phố Hà Nội,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,01839,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,40.155,...,None,1,1,None,None,None,None,None,None,IMP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,3.thau_rieng_le,40.169,Imexime 100,Cefixim,26,Tỉnh Vĩnh Phúc,Ttyt Khu Vực Tam Đảo,26026,Ttyt Khu Vực Tam Đảo,40.169,...,None,1,1,None,None,None,None,None,None,IMP
758,3.thau_rieng_le,40.172,Bacsulfo 1g/1g,Cefoperazon + sulbactam*,01,Thành phố Hà Nội,Bvđk Vân Đình,01817,Bvđk Vân Đình,40.172,...,None,1,1,None,None,None,None,None,None,IMP
759,3.thau_rieng_le,40.155,"Amoxicillin/ Acid clavulanic 250 mg/ 31,25 mg",Amoxicilin + acid clavulanic,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.155,...,None,1,1,None,None,None,None,None,None,IMP
760,3.thau_rieng_le,40.171,"Cefoperazone 0,5g",Cefoperazon*,01,Thành phố Hà Nội,Bvđk Nông Nghiệp,01013,Bvđk Nông Nghiệp,40.171,...,None,1,1,None,None,None,None,None,None,IMP
761,3.thau_rieng_le,40.174,Cefotiam1g,Cefotiam*,01,Thành phố Hà Nội,Bvđk Nông Nghiệp,01013,Bvđk Nông Nghiệp,40.174,...,None,1,1,None,None,None,None,None,None,IMP

In [ ]:
# Tính tổng số lượng
print(f'Tổng số lượng của IMP: {test_data.filter(by='IMP').sum(value_col='soluong'):,.0f}') # Cái ':,.0f' là để hiển thị dấu phẩy hàng nghìn
 
# Tính tổng giá trị
print(f'Tổng giá trị của IMP: {test_data.filter(by='IMP').sum(value_col='thanhtien'):,.0f}')

Tổng số lượng của IMP: 25,647,070
Tổng giá trị của IMP: 288,706,927,665